(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_109=" ^ (wrap (fn () => let val t = ((if ((String.size (if (8 < 8) then (Bool.toString true) else (Bool.toString false))) <= (List.foldl (fn (x, v1) => (let val v2 = (let val t = buildTree (Int.abs (6) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs ((~7)) mod 40000 + 40000) in sumTree t end) in (let val n = Int.abs (v2) mod 1000 + 500 val rs = List.tabulate (n, fn i => ref (i * 3)) val () = List.app (fn r => r := !r + 1) rs in List.foldl (fn (r,acc) => acc + !r) 0 rs end) end)) (List.length (List.tabulate (Int.abs (9) mod 12, (fn i => (#2 (9, 3)))))) (List.take (List.rev (List.tabulate (Int.abs ((Int.min ((~4), (~7)))) mod 2000 + 1000, (fn i => (Int.max ((~5), 10))))), 5)))) then (mirrorTree (buildTree (Int.abs (3) mod 6 + 6))) else (mapTree (fn x => (~ (Int.min ((~2), x)))) (buildTree (Int.abs (((10 - (~5)) mod (~10))) mod 6 + 6))))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
