(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_147=" ^ (wrap (fn () => pr2s ((let val v1 = (let val v2 = (if ((#1 (6, 7)) > ((~3) - 10)) then ((let val v3 = (Lf 4) in true end) orelse (let val n = Int.abs (6) mod 2000 + 500 in List.tabulate (n, fn i => i mod 7) = List.tabulate (n, fn i => i mod 7) end)) else ((List.null []) orelse (not false))) in (Int.toString (let val n = Int.abs (((~3) - 0)) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end)) end) in (let val (a, b) = ((let val n = Int.abs ((Int.max ((~6), 10))) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end), (#2 (let val v4 = (Lf 0) in ((~1), 2) end))) in (b, a) end) end)))) ^ "\n");
