(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_149=" ^ (wrap (fn () => let val t = ((let val v1 = (let val v2 = (let fun loop k acc = if k <= 0 then acc else loop (k-1) (acc + List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j + k))) in loop (Int.abs (((~ 5) div (7 - 9))) mod 4000 + 3000) 0 end) in (String.substring ((Int.toString (let val t = buildTree (Int.abs (v2) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs (3) mod 40000 + 40000) in sumTree t end)), 0, 1)) end) in (buildTree (Int.abs ((Int.abs ((~6) mod (~1)))) mod 6 + 6)) end)) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
