(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_132=" ^ (wrap (fn () => let val t = ((mapTree (fn x => (((~7) mod 0) * (Int.abs x))) (Br ((Br ((Lf (String.size "k")), (List.length (List.filter (fn x => (List.exists (fn x => (false andalso false)) [])) [1])), (Lf (10 div 9)))), ((case (let val v1 = (Lf (~7)) in [5, 3, 5, 7, 1] end) of [] => 0 | [a] => a | (a :: b :: _) => a + b) - (let val t = buildTree (Int.abs (((~3) * (~2))) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs ((Int.abs (~1))) mod 40000 + 40000) in sumTree t end)), (let val v2 = (mapTree (fn x => (4 mod 4)) (mirrorTree (Lf (~7)))) in (Br ((mirrorTree v2), (if true then 7 else (~10)), (mirrorTree v2))) end))))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
