(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_116=" ^ (wrap (fn () => ((let val v1 = (let val p = (if (not ((~3) <= (~10))) then ((~ (~1)), (Int.abs 6)) else (if ((~3) < 6) then (if false then (8, (~6)) else (8, (~2))) else (let val xs = List.tabulate (Int.abs (1) mod 3000 + 1000, fn i => i mod 13) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end))) in (#2 p, #1 p) end) in (Bool.toString (((let val n = Int.abs (1) mod 1000 + 500 val rs = List.tabulate (n, fn i => ref (i * 3)) val () = List.app (fn r => r := !r + 1) rs in List.foldl (fn (r,acc) => acc + !r) 0 rs end) * (List.length [10, 8, 10, (~6)])) < (let val n = Int.abs ((Int.min (6, (~7)))) mod 1000 + 500 val rs = List.tabulate (n, fn i => ref (i * 3)) val () = List.app (fn r => r := !r + 1) rs in List.foldl (fn (r,acc) => acc + !r) 0 rs end))) end)))) ^ "\n");
