(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_140=" ^ (wrap (fn () => let val t = ((Lf (List.foldl (fn (x, v1) => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((String.size ("b55" ^ "c"))) mod 1000) 0 end)) (let val dpth = Int.abs (((1 div (~10)) - (7 - (~8)))) mod 6 + 8 in sumTree (buildTree dpth) end) (let val v2 = ((false andalso false) andalso (if true then false else false)) in (List.take (List.rev (List.tabulate (Int.abs ((6 mod 10)) mod 2000 + 1000, (fn i => ((~7) - (~4))))), 5)) end)))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
