(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_135=" ^ (wrap (fn () => let val t = ((Br ((Br ((buildTree (Int.abs ((Int.max (6, ((~3) mod (~4))))) mod 6 + 6)), (let val v1 = (let val v2 = (List.map (fn x => (List.length [])) [9, 8, (~5), (~6)]) in (let val p = ((~4), (~9)) in (#2 p, #1 p) end) end) in (let fun loop k acc = if k <= 0 then acc else loop (k-1) (acc + List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j + k))) in loop (Int.abs ((7 * 4)) mod 4000 + 3000) 0 end) end), (mirrorTree (mirrorTree (Lf 7))))), (#1 ((sumTree (let val v3 = 4 in (Lf (~10)) end)), (let val dpth = Int.abs ((~ (~5))) mod 6 + 8 in sumTree (buildTree dpth) end))), (let val v4 = (if ((#2 (9, 0)) > (Int.abs 6)) then (List.all (fn x => (false andalso false)) (let val v5 = (~5) in [(~4), (~8), 7, (~9), 4] end)) else ((let val keep = List.tabulate (Int.abs (4) mod 4000 + 5000, fn i => i) fun churn k = if k <= 0 then 0 else (List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j+k)); churn (k-1)) val _ = churn (Int.abs ((~8)) mod 40000 + 40000) in List.foldl (fn (a,b) => a + b) 0 keep end) > (if false then 7 else (~7)))) in (if (((~3) + 4) = (~ 8)) then (Lf (let val n = Int.abs ((~1)) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end)) else (mapTree (fn x => ((~2) * x)) (if v4 then (Lf 1) else (Lf (~3))))) end)))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
