(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_130=" ^ (wrap (fn () => Int.toString (((if (let val n = Int.abs (((Int.abs (~6)) - ((~5) * (~5)))) mod 2000 + 500 in List.tabulate (n, fn i => i mod 7) = List.tabulate (n, fn i => i mod 7) end) then (let val n = Int.abs (((~1) + (Int.max ((~6), (~2))))) mod 4000 + 2000 in List.foldl (fn (a,b) => a + b) 0 (List.tabulate (n, (fn i => ((Int.max ((~10), i)) * (~ 3))))) end) else (~ (sumTree (mirrorTree (Lf 3))))) + (let val n = Int.abs (((~9) + (Int.max ((~10), (~7))))) mod 1000 + 500 val rs = List.tabulate (n, fn i => ref (i * 3)) val () = List.app (fn r => r := !r + 1) rs in List.foldl (fn (r,acc) => acc + !r) 0 rs end))))) ^ "\n");
