(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_100=" ^ (wrap (fn () => let val t = ((if (not (not (let val v1 = ((~10), (~9)) in ((~1) = (~5)) end))) then (let val v2 = (List.take (List.map (fn x => ((~ x) - (x - x))) (List.tabulate (Int.abs ((~ (Int.max (4, 1)))) mod 1500 + 500, fn i => i)), 4)) in (Br ((if (8 = (~3)) then (mirrorTree (Lf (~8))) else (if false then (Lf (~10)) else (Lf (~10)))), (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((Int.min ((~7), (~9)))) mod 1000) 0 end), (mapTree (fn x => (x + 1)) (mapTree (fn x => (x - x)) (Lf (~6)))))) end) else (let val v3 = (((List.length [3, 9, (~6), 8]) - (let val n = Int.abs ((~6)) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end)) <= (let val n = Int.abs ((Int.max ((~1), 1))) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end)) in (mirrorTree (Lf (let val t = buildTree (Int.abs (4) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs (0) mod 40000 + 40000) in sumTree t end))) end))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
