(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_128=" ^ (wrap (fn () => Bool.toString (((if (not (List.null (List.filter (fn x => (x <= x)) [8, 9, 5, 2, (~9)]))) then (Bool.toString (List.all (fn x => (List.null [(~9), (~5)])) (List.map (fn x => (let val n = Int.abs ((~8)) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end)) [2, (~1), (~5), (~6)]))) else (String.substring (String.concatWith "-" (List.map Int.toString (List.tabulate (Int.abs (((Int.min ((~9), (~7))) + 3)) mod 1000 + 500, fn i => i mod 10))), 0, 9))) = (let val v1 = (if ((Int.min ((~4), 3)) > (let fun loop k acc = if k <= 0 then String.size acc else loop (k-1) (acc ^ Int.toString (k mod 100)) in loop (Int.abs ((~10)) mod 500 + 300) "" end)) then (List.map (fn x => (List.length [9, (~2), 3, (~2)])) ([5, (~3)] @ [(~2), 3, (~3), 9, (~10)])) else (if (List.null [(~2), (~1), (~4), (~9), 6]) then (case [(~3), 0, (~5)] of [] => [] | (a :: rest) => rest @ [a]) else (List.take (treeLeaves (Lf 5) @ [0,0,0,0,0], 5)))) in (Int.toString ((if false then 5 else (~1)) * (let val dpth = Int.abs (6) mod 6 + 8 in sumTree (buildTree dpth) end))) end))))) ^ "\n");
