(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_148=" ^ (wrap (fn () => Int.toString ((List.foldl (fn (x, v1) => (case (List.take (List.map (fn x => (~6)) (List.tabulate (Int.abs ((Int.min ((~2), (Int.abs v1)))) mod 1500 + 500, fn i => i)), 4)) of [] => 0 | [a] => a | (a :: b :: _) => a + b)) (sumTree (buildTree (Int.abs ((((~2) - (~10)) div ((~10) - (~3)))) mod 6 + 6))) (if (((let val dpth = Int.abs (4) mod 6 + 8 in sumTree (buildTree dpth) end) < (let val n = Int.abs ((~8)) mod 1000 + 500 val rs = List.tabulate (n, fn i => ref (i * 3)) val () = List.app (fn r => r := !r + 1) rs in List.foldl (fn (r,acc) => acc + !r) 0 rs end)) andalso (let val n = Int.abs ((Int.max ((~8), (~7)))) mod 2000 + 500 in List.tabulate (n, fn i => i mod 7) = List.tabulate (n, fn i => i mod 7) end)) then ((List.foldl (fn (x, v2) => (if true then v2 else 10)) ((~4) * (~2)) (let val v3 = false in [1, 6, 9, 9] end)) :: (List.filter (fn x => (not false)) (case [] of [] => [] | (a :: rest) => rest @ [a]))) else (List.map (fn x => (Int.max ((List.foldl (fn (x, v4) => (Int.max (10, v4))) x []), (0 mod x)))) (List.take (List.rev (List.tabulate (Int.abs (((~9) mod (~4))) mod 2000 + 1000, (fn i => (~ i)))), 5)))))))) ^ "\n");
