(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_123=" ^ (wrap (fn () => il2s (((let val v1 = (if ((true orelse true) andalso ((~8) < (~10))) then (case ([(~2)] @ [8, 3, (~1), (~1)]) of [] => 0 | [a] => a | (a :: b :: _) => a + b) else ((#2 (7, 3)) * (3 * (~4)))) in (List.filter (fn x => ((Int.abs (~10)) < (let val dpth = Int.abs (x) mod 6 + 8 in sumTree (buildTree dpth) end))) (List.filter (fn x => ((~1) > x)) (List.tabulate (Int.abs (v1) mod 12, (fn i => (let fun loop k acc = if k <= 0 then String.size acc else loop (k-1) (acc ^ Int.toString (k mod 100)) in loop (Int.abs (1) mod 500 + 300) "" end)))))) end) @ (List.take (treeLeaves (if (if ((~5) < 0) then (2 < 8) else (List.null [8, (~9), 5, 4])) then (mirrorTree (mirrorTree (Lf 0))) else (mapTree (fn x => (Int.min ((~1), 1))) (Lf (~8)))) @ [0,0,0,0,0], 5)))))) ^ "\n");
