(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_139=" ^ (wrap (fn () => pr2s (((List.foldl (fn (x, v1) => (~ (List.length (List.tabulate (Int.abs (v1) mod 12, (fn i => (let val keep = List.tabulate (Int.abs ((~9)) mod 4000 + 5000, fn i => i) fun churn k = if k <= 0 then 0 else (List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j+k)); churn (k-1)) val _ = churn (Int.abs ((~8)) mod 40000 + 40000) in List.foldl (fn (a,b) => a + b) 0 keep end))))))) (let val t = buildTree (Int.abs ((Int.min (((~1) * 7), 2))) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs (((Int.min (2, 8)) - (~4))) mod 40000 + 40000) in sumTree t end) (List.take (List.map (fn x => ((x * x) mod x)) (List.tabulate (Int.abs (((Int.max (10, (~6))) mod (Int.abs 2))) mod 1500 + 500, fn i => i)), 4))), (depthTree (mapTree (fn x => (Int.min (x, (3 - x)))) (Lf ((~4) div (~5))))))))) ^ "\n");
