(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_117=" ^ (wrap (fn () => pr2s ((let val p = (let val v1 = (let val v2 = (List.take (treeLeaves (mapTree (fn x => (x * x)) (Lf (~4))) @ [0,0,0,0,0], 5)) in (Int.toString (List.foldl (fn (x, v3) => (let val t = buildTree (Int.abs ((~3)) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs (v3) mod 40000 + 40000) in sumTree t end)) (~4) [(~8), 1, (~7), (~3), (~4)])) end) in ((#1 (if true then (9, 0) else (5, 7))), ((sumTree (Lf (~8))) div (let val dpth = Int.abs (4) mod 6 + 8 in sumTree (buildTree dpth) end))) end) in (#2 p, #1 p) end)))) ^ "\n");
