(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_151=" ^ (wrap (fn () => ((if (let val v1 = (let val p = (let val xs = List.tabulate (Int.abs ((~8)) mod 3000 + 1000, fn i => i mod 13) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) in (#2 p, #1 p) end) in (List.exists (fn x => ((Bool.toString false) = (if false then "sqa" else "9v"))) (List.rev (let val v2 = "cid3" in [6, (~3), (~10), 4, 5] end))) end) then (String.substring (((String.map Char.toUpper (if false then "c0" else "y")) ^ (let val v3 = (not false) in (Bool.toString true) end)), 0, 1)) else (Bool.toString ((List.null (List.tabulate (Int.abs ((~5)) mod 12, (fn i => (Int.max (7, (~1))))))) andalso (((~4) + 2) > (depthTree (Lf (~9)))))))))) ^ "\n");
