(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_137=" ^ (wrap (fn () => Bool.toString (((#1 (let val p = (let val (a, b) = (let val xs = List.tabulate (Int.abs (1) mod 3000 + 1000, fn i => i mod 13) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) in (b, a) end) in (#2 p, #1 p) end)) = (((let val n = Int.abs ((Int.max ((~1), 4))) mod 1000 + 500 val rs = List.tabulate (n, fn i => ref (i * 3)) val () = List.app (fn r => r := !r + 1) rs in List.foldl (fn (r,acc) => acc + !r) 0 rs end) - (let val keep = List.tabulate (Int.abs (((~2) * 2)) mod 4000 + 5000, fn i => i) fun churn k = if k <= 0 then 0 else (List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j+k)); churn (k-1)) val _ = churn (Int.abs ((5 div 9)) mod 40000 + 40000) in List.foldl (fn (a,b) => a + b) 0 keep end)) + (((List.foldl (fn (x, v1) => (x mod (~8))) 0 [9, (~9), (~8), 7]) + (List.length [(~7), (~3), 2])) * (List.length (List.take (treeLeaves (Lf (~1)) @ [0,0,0,0,0], 5))))))))) ^ "\n");
