(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_142=" ^ (wrap (fn () => let val t = ((Br ((mapTree (fn x => (~ (x + (~2)))) (let val v1 = (("o " ^ "e") = (Bool.toString false)) in (Br ((Br ((Lf 7), (~5), (Lf 8))), (3 * 5), (mapTree (fn x => (9 - 0)) (Lf 6)))) end)), ((List.foldl (fn (x, v2) => ((List.foldl (fn (x, v3) => (Int.abs (~3))) x [9, 3, (~8)]) div (let val n = Int.abs (3) mod 4000 + 2000 in List.foldl (fn (a,b) => a + b) 0 (List.tabulate (n, (fn i => (1 mod i)))) end))) (let fun loop k acc = if k <= 0 then String.size acc else loop (k-1) (acc ^ Int.toString (k mod 100)) in loop (Int.abs ((7 div 9)) mod 500 + 300) "" end) (List.map (fn x => ((~8) - x)) (if false then [7, (~2), 7] else []))) - (let val v4 = (Int.max ((List.length [(~8), (~5)]), (sumTree (Lf 1)))) in (let val n = Int.abs ((Int.max (8, v4))) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end) end)), (Br ((mirrorTree (if (let val v5 = "kbc" in true end) then (if true then (Lf (~3)) else (Lf (~7))) else (if false then (Lf 0) else (Lf (~8))))), (let val t = buildTree (Int.abs (((Int.min (5, (~9))) * (Int.abs 10))) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs ((9 mod 1)) mod 40000 + 40000) in sumTree t end), (if (List.null (case [(~2), (~7), (~3), (~10)] of [] => [] | (a :: rest) => rest @ [a])) then (buildTree (Int.abs (((~6) div 6)) mod 6 + 6)) else (let val v6 = (7 - 8) in (Lf v6) end))))))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
