(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_114=" ^ (wrap (fn () => ((if (((if (List.exists (fn x => (x > (~9))) [(~8)]) then (~ 2) else (#1 (2, (~2)))) + (#1 (let val p = ((~1), 3) in (#2 p, #1 p) end))) > (let val keep = List.tabulate (Int.abs (((Int.min (8, (~3))) * ((~8) - (~2)))) mod 4000 + 5000, fn i => i) fun churn k = if k <= 0 then 0 else (List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j+k)); churn (k-1)) val _ = churn (Int.abs ((((~2) div 7) + ((~3) + (~10)))) mod 40000 + 40000) in List.foldl (fn (a,b) => a + b) 0 keep end)) then (if ((let val n = Int.abs (((~3) mod (~1))) mod 2000 + 500 in List.tabulate (n, fn i => i mod 7) = List.tabulate (n, fn i => i mod 7) end) andalso (("w" ^ "2x") = (String.map Char.toUpper "4g"))) then ((String.substring (String.concatWith "-" (List.map Int.toString (List.tabulate (Int.abs ((Int.abs 7)) mod 1000 + 500, fn i => i mod 10))), 0, 9)) ^ (String.substring ((String.substring (String.concatWith "-" (List.map Int.toString (List.tabulate (Int.abs ((~9)) mod 1000 + 500, fn i => i mod 10))), 0, 9)), 0, 1))) else (String.substring ((Int.toString (List.length [7, (~9), (~6)])), 0, 1))) else (String.map Char.toUpper (Bool.toString ((#2 ((~2), (~5))) > (6 + (~6))))))))) ^ "\n");
