(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_122=" ^ (wrap (fn () => let val t = ((mirrorTree (Br ((mirrorTree (mirrorTree (if true then (Lf (~2)) else (Lf 3)))), (if ((let fun loop k acc = if k <= 0 then String.size acc else loop (k-1) (acc ^ Int.toString (k mod 100)) in loop (Int.abs ((~1)) mod 500 + 300) "" end) < (Int.min ((~8), 9))) then ((let val n = Int.abs ((~8)) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end) div ((~5) - 3)) else ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (0) mod 1000) 0 end) - (#2 (9, (~10))))), (Br ((if (let val v1 = (~6) in false end) then (let val v2 = (7, 2) in (Lf 4) end) else (let val v3 = [(~1), 4, (~4)] in (Lf 6) end)), (String.size ("rrhl1" ^ "yt")), (Br ((Br ((Lf 2), 1, (Lf 3))), (#2 ((~1), 5)), (Lf 9))))))))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
