(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_141=" ^ (wrap (fn () => il2s (((if (List.all (fn x => ((let val v1 = (8, (~2)) in (~9) end) > (List.foldl (fn (x, v2) => (List.length [(~5), (~7)])) 2 []))) (if (if true then true else false) then (List.take (List.map (fn x => ((~3) * x)) (List.tabulate (Int.abs ((~5)) mod 1500 + 500, fn i => i)), 4)) else (List.filter (fn x => (x < x)) [(~4), (~9)]))) then (let val v3 = (String.substring ((Bool.toString false), 0, 1)) in (let val n = Int.abs ((1 div (~6))) mod 4000 + 2000 in List.foldl (fn (a,b) => a + b) 0 (List.tabulate (n, (fn i => (Int.min (i, i))))) end) end) else ((Int.max ((List.length [5]), (List.foldl (fn (x, v4) => (~ 0)) 7 []))) + (List.length (List.tabulate (Int.abs (7) mod 12, (fn i => (~ i))))))) :: (case (let val v5 = (Lf (let fun loop k acc = if k <= 0 then String.size acc else loop (k-1) (acc ^ Int.toString (k mod 100)) in loop (Int.abs (9) mod 500 + 300) "" end)) in (List.take (treeLeaves (mirrorTree v5) @ [0,0,0,0,0], 5)) end) of [] => [] | (a :: rest) => rest @ [a]))))) ^ "\n");
