(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_104=" ^ (wrap (fn () => let val t = ((Br ((if (List.exists (fn x => ((9 = (~10)) andalso (if false then true else false))) (List.take (List.map (fn x => ((~5) mod (~1))) (List.tabulate (Int.abs ((~6)) mod 1500 + 500, fn i => i)), 4))) then (mirrorTree (mapTree (fn x => ((~1) div x)) (mirrorTree (Lf 1)))) else (if ((~ (~7)) < (String.size "vm47")) then (mirrorTree (mirrorTree (Lf 9))) else (if ((~10) <= 0) then (let val v1 = [(~10), 1, 9, 1] in (Lf 1) end) else (mirrorTree (Lf (~7)))))), (List.foldl (fn (x, v2) => (if (let val v3 = (not true) in (List.all (fn x => (List.exists (fn x => (List.exists (fn x => (true orelse v3)) [8, (~1), 7, 5, 7])) [2])) [(~3), 8, 4, 2]) end) then (List.length (List.take (List.map (fn x => (Int.min (v2, 8))) (List.tabulate (Int.abs (0) mod 1500 + 500, fn i => i)), 4))) else (let val n = Int.abs ((~ (~1))) mod 100 + 40 in List.foldl (fn (xs,acc) => acc + List.length xs) 0 (List.tabulate (n, fn i => List.tabulate (n, fn j => i+j))) end))) (let val t = buildTree (Int.abs ((Int.min (((~10) div 4), (Int.max ((~5), 10))))) mod 4 + 10) fun churn k = if k <= 0 then 0 else (List.tabulate (k mod 100 + 50, fn j => j+k); churn (k-1)) val _ = churn (Int.abs (((3 + 3) div (9 mod (~6)))) mod 40000 + 40000) in sumTree t end) (List.take (treeLeaves (if (7 <= (~7)) then (mirrorTree (Lf 8)) else (mapTree (fn x => (x mod 1)) (Lf 7))) @ [0,0,0,0,0], 5))), (mapTree (fn x => ((x mod x) * ((~4) - (~3)))) (mirrorTree (mapTree (fn x => (2 - (~8))) (Lf (~3)))))))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
