(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_101=" ^ (wrap (fn () => ((let val v1 = (List.foldl (fn (x, v2) => (List.foldl (fn (x, v3) => ((v2 - x) + (6 div x))) (Int.abs (let val v4 = "uv" in 2 end)) ((List.rev [(~6), (~1), (~9)]) @ (case [(~8), 4] of [] => [] | (a :: rest) => rest @ [a])))) (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((#2 (let val (a, b) = ((~8), 8) in (b, a) end))) mod 1000) 0 end) (List.take (List.map (fn x => (~ (x * x))) (List.tabulate (Int.abs (((Int.min (4, (~10))) * (0 + (~1)))) mod 1500 + 500, fn i => i)), 4))) in ((let val v5 = (if ((~7) <= 3) then (List.map (fn x => (let fun loop k acc = if k <= 0 then acc else loop (k-1) (acc + List.foldl (fn (a,b) => a+b) 0 (List.tabulate (k mod 100 + 50, fn j => j + k))) in loop (Int.abs (4) mod 4000 + 3000) 0 end)) [(~4), (~6), (~9)]) else (List.take (List.rev (List.tabulate (Int.abs (v1) mod 2000 + 1000, (fn i => (Int.abs i)))), 5))) in ((String.substring (String.concatWith "-" (List.map Int.toString (List.tabulate (Int.abs ((~8)) mod 1000 + 500, fn i => i mod 10))), 0, 9)) ^ (String.map Char.toUpper "cfk23")) end) ^ (String.substring (String.concatWith "-" (List.map Int.toString (List.tabulate (Int.abs ((Int.min (((~9) + v1), (Int.min ((~10), v1))))) mod 1000 + 500, fn i => i mod 10))), 0, 9))) end)))) ^ "\n");
