(* generated by tools/diff-corpus-gen/genprog_gc_pressure.sml -- DO NOT EDIT *)
datatype gctree = Lf of int | Br of gctree * int * gctree;
fun buildTree d = if d <= 0 then Lf d else Br (buildTree (d-1), d, buildTree (d-1));
fun sumTree (Lf n) = n | sumTree (Br (l, n, r)) = sumTree l + n + sumTree r;
fun depthTree (Lf _) = 0 | depthTree (Br (l, _, r)) = 1 + Int.max (depthTree l, depthTree r);
fun mapTree f (Lf n) = Lf (f n) | mapTree f (Br (l, n, r)) = Br (mapTree f l, f n, mapTree f r);
fun mirrorTree (Lf n) = Lf n | mirrorTree (Br (l, n, r)) = Br (mirrorTree r, n, mirrorTree l);
fun treeLeaves (Lf n) = [n] | treeLeaves (Br (l, _, r)) = treeLeaves l @ treeLeaves r;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_gc_pressure_103=" ^ (wrap (fn () => let val t = ((Br ((let val v1 = (if (let val n = Int.abs (((~6) * (~3))) mod 2000 + 500 in List.tabulate (n, fn i => i mod 7) = List.tabulate (n, fn i => i mod 7) end) then (buildTree (Int.abs ((8 - (~1))) mod 6 + 6)) else (buildTree (Int.abs ((0 mod (~1))) mod 6 + 6))) in (let val v2 = (let val p = ((~10), 8) in (#2 p, #1 p) end) in (Br ((buildTree (Int.abs (0) mod 6 + 6)), (#2 ((~7), 10)), (mapTree (fn x => (x - (~1))) v1))) end) end), (#1 (let val p = (let val (a, b) = ((~4), (~2)) in (b, a) end) in (#2 p, #1 p) end)), (if ((if (false orelse false) then (true orelse false) else (List.exists (fn x => ((~4) > 10)) [(~5), (~6)])) andalso (List.all (fn x => (let val v3 = "" in true end)) (case [9, 2, (~6)] of [] => [] | (a :: rest) => rest @ [a]))) then (Lf (List.foldl (fn (x, v4) => (let fun loop k acc = if k <= 0 then String.size acc else loop (k-1) (acc ^ Int.toString (k mod 100)) in loop (Int.abs (2) mod 500 + 300) "" end)) (#2 (2, 4)) (List.map (fn x => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~5)) mod 1000) 0 end)) [(~10), (~8)]))) else (Lf (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((10 mod 2)) mod 1000) 0 end)))))) in pr2s (sumTree t, depthTree t) end)) ^ "\n");
