(* theory_subsystem.sml — load HOL4's Theory subsystem (src/postkernel +
   its portableML/prekernel dependencies) on top of a basis+kernel poly
   checkpoint, by reconstructing HOL4's build environment by hand.
   ---------------------------------------------------------------------------
   Why this is non-trivial (see the per-project exo-self notes, 2026-05-30):
     * HOL4 normally compiles each file with `Overlay` as a prelude and loads
       COMPILED .uo artifacts from sigobj — there is no source-order list to
       copy.  This file reconstructs the equivalent for source `PolyML.use`.
     * `open Kernel` (from src/thm/Overlay.sml) OPAQUELY re-ascribes
       Type/Term/Thm, hiding leaked members (e.g. Thm.hash) that would
       otherwise shadow function parameters (the TheoryPP `pp_struct hash`
       bug).  Overlay needs Net, so we load src/0/Net first.
     * HOLsexp's reader is generated by ml-lex/ml-yacc (not checked in); we
       stub HOLsexp_parser since the reader is only used to DEserialize .dat
       files, never for in-memory work.
     * SHA1_ML's mosml impl shells out to /usr/bin/shasum; we stub it.
     * Systeml is a generated file; we provide the 3 fields actually used.
   ---------------------------------------------------------------------------
   Usage (cwd = vendor/polyml, or set HOL4_DIR):
     HOL4_DIR=<repo>/vendor/hol4 tools/sml-exp.sh /tmp/hol4_kernel \
       crates/polyml-bin/tests/hol4_support/theory_subsystem.sml
   Emits: THEORY_PREFIX_DONE, LOADED_OK n/m, STUCK_COUNT n, STUCKERR <path>…
   Current expected result on polyml-rs: LOADED_OK 50/54 (the 4 stuck are the
   theorem-DB *search* layer: DB / DBSearchParser / TheoryReader — not needed
   for Theory itself). *)

fun pr s = (print s; TextIO.flushOut TextIO.stdOut);
(* Default to the ../hol4 relative path (valid from cwd = vendor/polyml, which
   both sml-exp.sh and the Rust tests use). NB: our runtime's OS.Process.getEnv
   currently returns SOME "" for set vars, so we only honor a NON-empty value. *)
val HOL = case OS.Process.getEnv "HOL4_DIR" of
              SOME s => if s <> "" then s else "../hol4"
            | NONE => "../hol4";
fun U f = PolyML.use (HOL ^ "/" ^ f);
structure PP = HOLPP;

(* Systeml: generated upstream; only these 3 fields are referenced by the
   Theory closure (build_log_file/make_log_file = "" => logging is a no-op). *)
structure Systeml = struct
  val HOLDIR = HOL
  val release = "polyml-rs"
  val version = 0
  val build_log_file = ""
  val make_log_file = ""
end;

pr "\nTHEORY_PREFIX_START\n";

(* Opaque kernel re-ascription: Net + the real Overlay (its `open Kernel`
   hides leaked Thm.hash etc. and supplies the standard infixes). *)
U "src/0/Net.sig"; U "src/0/Net.sml";
U "src/thm/Overlay.sml";

(* sexp foundation + stubbed reader (reader only used for .dat reads). *)
U "src/portableML/HOLsexp_dtype.sml";
U "src/portableML/HOLsexp_parser.sig";
structure HOLsexp_parser :> HOLsexp_parser = struct
  type t = HOLsexp_dtype.t
  fun raw_read_stream (_ : TextIO.instream) : t =
      raise Fail "HOLsexp_parser(stub): reader disabled"
  fun raw_read_file (_ : string) : t =
      raise Fail "HOLsexp_parser(stub): reader disabled"
  fun scan (_ : (char,'a) StringCvt.reader) : (t,'a) StringCvt.reader =
      fn _ => raise Fail "HOLsexp_parser(stub): reader disabled"
end;

(* stubbed SHA1 (mosml impl shells out to shasum; only fingerprints .dat). *)
U "src/portableML/poly/SHA1_ML.sig";
structure SHA1_ML :> SHA1_ML = struct
  type 'a byte_reader = 'a * int -> Word8Vector.vector * 'a
  fun sha1 (_ : 'a byte_reader) (_ : 'a) : Word8Vector.vector =
      Word8Vector.fromList []
  fun sha1String (_ : 'a byte_reader) (_ : 'a) : string = "stub-sha1-digest"
  fun sha1_file ({filename} : {filename:string}) : string =
      "stub-sha1-" ^ filename
end;
pr "THEORY_PREFIX_DONE\n";

(* The closure (order-independent: the fixpoint loop below resolves it). *)
val files = [
  "tools/util/FunctionalRecordUpdate.sml",
  "src/portableML/smpp.sig",                  "src/portableML/smpp.sml",
  "src/portableML/UniversalType.sig",         "src/portableML/UniversalType.sml",
  "src/portableML/poly/Arbintcore.sig",       "src/portableML/poly/Arbintcore.sml",
  "src/portableML/Arbint.sig",                "src/portableML/Arbint.sml",
  "src/portableML/seq.sig",                   "src/portableML/seq.sml",
  "src/portableML/monads/optmonad.sig",       "src/portableML/monads/optmonad.sml",
  "src/portableML/HOLsexp.sig",               "src/portableML/HOLsexp.sml",
  "src/portableML/SHA1.sig",                  "src/portableML/SHA1.sml",
  "src/prekernel/Listener.sig",              "src/prekernel/Listener.sml",
  "src/prekernel/TraceMode.sig",             "src/prekernel/TraceMode.sml",
  "src/prekernel/Coding.sig",                "src/prekernel/Coding.sml",
  "src/tracing/Tracing.sig",                 "src/tracing/no/Tracing.sml",
  "tools/Holmake/hfs/holpathdb.sig",         "tools/Holmake/hfs/holpathdb.sml",
  "src/portableML/rawtheory/RawTheory_dtype.sml",
  "src/portableML/rawtheory/RawTermPP.sig",  "src/portableML/rawtheory/RawTermPP.sml",
  "src/portableML/rawtheory/RawTheoryReader.sig",
  "src/portableML/rawtheory/RawTheoryReader.sml",
  "src/postkernel/DB_dtype.sml",             "src/postkernel/ThmKind_dtype.sml",
  "src/postkernel/TheoryDelta.sml",
  "src/postkernel/ThyDataSexp.sig",          "src/postkernel/ThyDataSexp.sml",
  "src/postkernel/Termtab.sml",              "src/postkernel/Typetab.sml",
  "src/postkernel/SharingTables.sig",        "src/postkernel/SharingTables.sml",
  "src/postkernel/TheoryPP.sig",             "src/postkernel/TheoryPP.sml",
  "src/postkernel/Theory.sig",               "src/postkernel/Theory.sml",
  "src/postkernel/TheoryReader.sig",         "src/postkernel/TheoryReader.sml",
  "src/postkernel/DBSearchParser.sig",       "src/postkernel/DBSearchParser.sml",
  "src/postkernel/DB.sig",                   "src/postkernel/DB.sml",
  "src/postkernel/TheoryGraph.sig",          "src/postkernel/TheoryGraph.sml",
  "src/postkernel/HolKernel.sml"
];

(* fixpoint loader: retry each file across passes until no new one loads. *)
val errs = ref ([] : (string * string) list);
fun note (f, e) = errs := (f, e) :: (List.filter (fn (g,_) => g <> f) (!errs));
fun tryUse f = (U f; true) handle e => (note (f, exnMessage e); false);
fun pass (rem, prog) =
  case rem of [] => (prog, [])
  | f :: rest => if tryUse f
                 then let val (p,l) = pass(rest,true) in (p,l) end
                 else let val (p,l) = pass(rest,prog) in (p, f::l) end;
fun loop (rem, n) =
  if n <= 0 then rem
  else let val (_, left) = pass (rem, false)
       in if List.null left then []
          else if List.length left = List.length rem then left
          else loop (left, n - 1) end;

pr "FIXPOINT_START\n";
val stuck = loop (files, 15);
pr ("\nLOADED_OK " ^ Int.toString (List.length files - List.length stuck)
    ^ "/" ^ Int.toString (List.length files) ^ "\n");
pr ("STUCK_COUNT " ^ Int.toString (List.length stuck) ^ "\n");
List.app (fn f => pr ("STUCKERR " ^ f ^ "\n")) stuck;
pr "THEORY_SUBSYSTEM_DONE\n";
