(* diff-corpus category: arrayslice (deep sweep 2026-06-09) *)

val () = print ("@@arr_len=" ^ Int.toString (Array.length (Array.array (5, 7))) ^ "\n");
val () = print ("@@arr_fromList_sum=" ^ Int.toString (Array.foldl (op +) 0 (Array.fromList [3,1,4,1,5,9,2,6])) ^ "\n");
val () = print ("@@arr_tabulate=" ^ Int.toString (Array.foldl (op +) 0 (Array.tabulate (6, fn i => i*i))) ^ "\n");
val () = print ("@@arr_tabulate0_len=" ^ Int.toString (Array.length (Array.tabulate (0, fn i => i))) ^ "\n");
val () = print ("@@arr_sub=" ^ Int.toString (let val a = Array.fromList [10,20,30,40] in Array.sub (a, 2) end) ^ "\n");
val () = print ("@@arr_update_read=" ^ Int.toString (let val a = Array.array (3, 0) in Array.update (a, 1, 99); Array.sub (a, 1) end) ^ "\n");
val () = print ("@@arr_mutate_fold=" ^ Int.toString (let val a = Array.tabulate (5, fn i => i) val () = Array.modify (fn x => x*10) a in Array.foldl (op +) 0 a end) ^ "\n");
val () = print ("@@arr_modifyi=" ^ Int.toString (let val a = Array.array (4, 1) val () = Array.modifyi (fn (i,x) => i+x) a in Array.foldr (op +) 0 a end) ^ "\n");
val () = print ("@@arr_foldl_order=" ^ (let val a = Array.fromList [1,2,3] in Array.foldl (fn (x,acc) => acc ^ Int.toString x) "" a end) ^ "\n");
val () = print ("@@arr_foldr_order=" ^ (let val a = Array.fromList [1,2,3] in Array.foldr (fn (x,acc) => acc ^ Int.toString x) "" a end) ^ "\n");
val () = print ("@@arr_foldli=" ^ Int.toString (let val a = Array.fromList [5,5,5,5] in Array.foldli (fn (i,x,acc) => acc + i*x) 0 a end) ^ "\n");
val () = print ("@@arr_foldri=" ^ Int.toString (let val a = Array.fromList [5,5,5,5] in Array.foldri (fn (i,x,acc) => acc + i*x) 0 a end) ^ "\n");
val () = print ("@@arr_app=" ^ Int.toString (let val r = ref 0 val a = Array.fromList [2,4,6,8] in Array.app (fn x => r := !r + x) a; !r end) ^ "\n");
val () = print ("@@arr_appi=" ^ Int.toString (let val r = ref 0 val a = Array.fromList [2,4,6,8] in Array.appi (fn (i,x) => r := !r + i*x) a; !r end) ^ "\n");
val () = print ("@@arr_copy_same=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5] in Array.copy {src=a, dst=a, di=0}; Array.foldl (op +) 0 a end) ^ "\n");
val () = print ("@@arr_copy_dst=" ^ Int.toString (let val src = Array.fromList [7,8,9] val dst = Array.array (5, 0) in Array.copy {src=src, dst=dst, di=2}; Array.foldl (op +) 0 dst end) ^ "\n");
val () = print ("@@arr_copyVec=" ^ Int.toString (let val v = Vector.fromList [11,22,33] val dst = Array.array (4, 1) in Array.copyVec {src=v, dst=dst, di=1}; Array.foldl (op +) 0 dst end) ^ "\n");
val () = print ("@@arr_vector=" ^ Int.toString (let val a = Array.fromList [3,6,9] in Vector.foldl (op +) 0 (Array.vector a) end) ^ "\n");
val () = print ("@@arr_sub_oob=" ^ (let val a = Array.fromList [1,2,3] in ((Array.sub (a, 5); "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@arr_sub_neg=" ^ (let val a = Array.fromList [1,2,3] in ((Array.sub (a, ~1); "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@arr_update_oob=" ^ (let val a = Array.array (3, 0) in ((Array.update (a, 3, 1); "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@arr_neg_size=" ^ ((Array.array (~1, 0); "NO") handle Size => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@arr_copy_oob=" ^ (let val src = Array.fromList [1,2,3] val dst = Array.array (2, 0) in ((Array.copy {src=src, dst=dst, di=0}; "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@arr_copyVec_oob=" ^ (let val v = Vector.fromList [1,2,3] val dst = Array.array (2, 0) in ((Array.copyVec {src=v, dst=dst, di=0}; "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@as_full_sum=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5] in ArraySlice.foldl (op +) 0 (ArraySlice.full a) end) ^ "\n");
val () = print ("@@as_slice_sum=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5,6] val s = ArraySlice.slice (a, 1, SOME 3) in ArraySlice.foldl (op +) 0 s end) ^ "\n");
val () = print ("@@as_slice_nolen=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5,6] val s = ArraySlice.slice (a, 2, NONE) in ArraySlice.foldl (op +) 0 s end) ^ "\n");
val () = print ("@@as_length=" ^ Int.toString (let val a = Array.fromList [0,0,0,0,0,0,0] val s = ArraySlice.slice (a, 2, SOME 3) in ArraySlice.length s end) ^ "\n");
val () = print ("@@as_sub=" ^ Int.toString (let val a = Array.fromList [10,11,12,13,14] val s = ArraySlice.slice (a, 1, SOME 3) in ArraySlice.sub (s, 2) end) ^ "\n");
val () = print ("@@as_update=" ^ Int.toString (let val a = Array.fromList [0,0,0,0,0] val s = ArraySlice.slice (a, 1, SOME 3) in ArraySlice.update (s, 0, 42); Array.sub (a, 1) end) ^ "\n");
val () = print ("@@as_subslice=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5,6,7,8] val s = ArraySlice.slice (a, 1, SOME 6) val s2 = ArraySlice.subslice (s, 1, SOME 3) in ArraySlice.foldl (op +) 0 s2 end) ^ "\n");
val () = print ("@@as_modify=" ^ Int.toString (let val a = Array.fromList [1,1,1,1,1] val s = ArraySlice.slice (a, 1, SOME 3) in ArraySlice.modify (fn x => x*100) s; Array.foldl (op +) 0 a end) ^ "\n");
val () = print ("@@as_modifyi=" ^ Int.toString (let val a = Array.fromList [0,0,0,0,0] val s = ArraySlice.slice (a, 1, SOME 3) in ArraySlice.modifyi (fn (i,x) => i+1) s; Array.foldl (op +) 0 a end) ^ "\n");
val () = print ("@@as_appi=" ^ Int.toString (let val r = ref 0 val a = Array.fromList [9,9,9,9,9] val s = ArraySlice.slice (a, 2, SOME 2) in ArraySlice.appi (fn (i,x) => r := !r + i + x) s; !r end) ^ "\n");
val () = print ("@@as_foldri=" ^ (let val a = Array.fromList [1,2,3,4] val s = ArraySlice.full a in ArraySlice.foldri (fn (i,x,acc) => acc ^ Int.toString i ^ Int.toString x) "" s end) ^ "\n");
val () = print ("@@as_copy=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5,6] val s = ArraySlice.slice (a, 0, SOME 3) val dst = Array.array (5, 0) in ArraySlice.copy {src=s, dst=dst, di=1}; Array.foldl (op +) 0 dst end) ^ "\n");
val () = print ("@@as_copy_overlap=" ^ Int.toString (let val a = Array.fromList [1,2,3,4,5] val s = ArraySlice.slice (a, 0, SOME 3) in ArraySlice.copy {src=s, dst=a, di=2}; Array.foldl (op +) 0 a end) ^ "\n");
val () = print ("@@as_vector=" ^ Int.toString (let val a = Array.fromList [5,10,15,20,25] val s = ArraySlice.slice (a, 1, SOME 3) in Vector.foldl (op +) 0 (ArraySlice.vector s) end) ^ "\n");
val () = print ("@@as_isEmpty=" ^ (let val a = Array.fromList [1,2,3] val s = ArraySlice.slice (a, 1, SOME 0) in Bool.toString (ArraySlice.isEmpty s) end) ^ "\n");
val () = print ("@@as_slice_oob=" ^ (let val a = Array.fromList [1,2,3] in ((ArraySlice.slice (a, 1, SOME 5); "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@as_sub_oob=" ^ (let val a = Array.fromList [1,2,3,4] val s = ArraySlice.slice (a, 1, SOME 2) in ((ArraySlice.sub (s, 2); "NO") handle Subscript => "CAUGHT" | _ => "OTHER") end) ^ "\n");
val () = print ("@@as_getItem=" ^ Int.toString (let val a = Array.fromList [4,8,12,16] val s = ArraySlice.slice (a, 1, SOME 2) in case ArraySlice.getItem s of SOME (x, _) => x | NONE => ~1 end) ^ "\n");
