(* diff-corpus category: char_pred (deep sweep 2026-06-09) *)

val () = print ("@@isAlpha_0=" ^ Bool.toString (Char.isAlpha (Char.chr 0)) ^ "\n");
val () = print ("@@isAlpha_65=" ^ Bool.toString (Char.isAlpha #"A") ^ "\n");
val () = print ("@@isAlpha_90=" ^ Bool.toString (Char.isAlpha #"Z") ^ "\n");
val () = print ("@@isAlpha_97=" ^ Bool.toString (Char.isAlpha #"a") ^ "\n");
val () = print ("@@isAlpha_122=" ^ Bool.toString (Char.isAlpha #"z") ^ "\n");
val () = print ("@@isAlpha_48=" ^ Bool.toString (Char.isAlpha #"0") ^ "\n");
val () = print ("@@isAlpha_255=" ^ Bool.toString (Char.isAlpha (Char.chr 255)) ^ "\n");
val () = print ("@@isAlphaNum_57=" ^ Bool.toString (Char.isAlphaNum #"9") ^ "\n");
val () = print ("@@isAlphaNum_65=" ^ Bool.toString (Char.isAlphaNum #"A") ^ "\n");
val () = print ("@@isAlphaNum_32=" ^ Bool.toString (Char.isAlphaNum #" ") ^ "\n");
val () = print ("@@isDigit_47=" ^ Bool.toString (Char.isDigit (Char.chr 47)) ^ "\n");
val () = print ("@@isDigit_48=" ^ Bool.toString (Char.isDigit #"0") ^ "\n");
val () = print ("@@isDigit_57=" ^ Bool.toString (Char.isDigit #"9") ^ "\n");
val () = print ("@@isDigit_58=" ^ Bool.toString (Char.isDigit (Char.chr 58)) ^ "\n");
val () = print ("@@isHexDigit_57=" ^ Bool.toString (Char.isHexDigit #"9") ^ "\n");
val () = print ("@@isHexDigit_70=" ^ Bool.toString (Char.isHexDigit #"F") ^ "\n");
val () = print ("@@isHexDigit_71=" ^ Bool.toString (Char.isHexDigit #"G") ^ "\n");
val () = print ("@@isHexDigit_102=" ^ Bool.toString (Char.isHexDigit #"f") ^ "\n");
val () = print ("@@isHexDigit_103=" ^ Bool.toString (Char.isHexDigit #"g") ^ "\n");
val () = print ("@@isSpace_9=" ^ Bool.toString (Char.isSpace (Char.chr 9)) ^ "\n");
val () = print ("@@isSpace_10=" ^ Bool.toString (Char.isSpace (Char.chr 10)) ^ "\n");
val () = print ("@@isSpace_13=" ^ Bool.toString (Char.isSpace (Char.chr 13)) ^ "\n");
val () = print ("@@isSpace_32=" ^ Bool.toString (Char.isSpace #" ") ^ "\n");
val () = print ("@@isSpace_12=" ^ Bool.toString (Char.isSpace (Char.chr 12)) ^ "\n");
val () = print ("@@isSpace_11=" ^ Bool.toString (Char.isSpace (Char.chr 11)) ^ "\n");
val () = print ("@@isSpace_65=" ^ Bool.toString (Char.isSpace #"A") ^ "\n");
val () = print ("@@isPunct_33=" ^ Bool.toString (Char.isPunct #"!") ^ "\n");
val () = print ("@@isPunct_126=" ^ Bool.toString (Char.isPunct (Char.chr 126)) ^ "\n");
val () = print ("@@isPunct_32=" ^ Bool.toString (Char.isPunct #" ") ^ "\n");
val () = print ("@@isPunct_65=" ^ Bool.toString (Char.isPunct #"A") ^ "\n");
val () = print ("@@isGraph_32=" ^ Bool.toString (Char.isGraph #" ") ^ "\n");
val () = print ("@@isGraph_33=" ^ Bool.toString (Char.isGraph #"!") ^ "\n");
val () = print ("@@isGraph_126=" ^ Bool.toString (Char.isGraph (Char.chr 126)) ^ "\n");
val () = print ("@@isGraph_127=" ^ Bool.toString (Char.isGraph (Char.chr 127)) ^ "\n");
val () = print ("@@isPrint_31=" ^ Bool.toString (Char.isPrint (Char.chr 31)) ^ "\n");
val () = print ("@@isPrint_32=" ^ Bool.toString (Char.isPrint #" ") ^ "\n");
val () = print ("@@isPrint_126=" ^ Bool.toString (Char.isPrint (Char.chr 126)) ^ "\n");
val () = print ("@@isPrint_127=" ^ Bool.toString (Char.isPrint (Char.chr 127)) ^ "\n");
val () = print ("@@isCntrl_0=" ^ Bool.toString (Char.isCntrl (Char.chr 0)) ^ "\n");
val () = print ("@@isCntrl_31=" ^ Bool.toString (Char.isCntrl (Char.chr 31)) ^ "\n");
val () = print ("@@isCntrl_32=" ^ Bool.toString (Char.isCntrl #" ") ^ "\n");
val () = print ("@@isCntrl_127=" ^ Bool.toString (Char.isCntrl (Char.chr 127)) ^ "\n");
val () = print ("@@isCntrl_128=" ^ Bool.toString (Char.isCntrl (Char.chr 128)) ^ "\n");
val () = print ("@@isCntrl_255=" ^ Bool.toString (Char.isCntrl (Char.chr 255)) ^ "\n");
val () = print ("@@isLower_96=" ^ Bool.toString (Char.isLower (Char.chr 96)) ^ "\n");
val () = print ("@@isLower_97=" ^ Bool.toString (Char.isLower #"a") ^ "\n");
val () = print ("@@isLower_122=" ^ Bool.toString (Char.isLower #"z") ^ "\n");
val () = print ("@@isLower_123=" ^ Bool.toString (Char.isLower (Char.chr 123)) ^ "\n");
val () = print ("@@isUpper_64=" ^ Bool.toString (Char.isUpper (Char.chr 64)) ^ "\n");
val () = print ("@@isUpper_65=" ^ Bool.toString (Char.isUpper #"A") ^ "\n");
val () = print ("@@isUpper_90=" ^ Bool.toString (Char.isUpper #"Z") ^ "\n");
val () = print ("@@isUpper_91=" ^ Bool.toString (Char.isUpper (Char.chr 91)) ^ "\n");
val () = print ("@@isAscii_0=" ^ Bool.toString (Char.isAscii (Char.chr 0)) ^ "\n");
val () = print ("@@isAscii_127=" ^ Bool.toString (Char.isAscii (Char.chr 127)) ^ "\n");
val () = print ("@@isAscii_128=" ^ Bool.toString (Char.isAscii (Char.chr 128)) ^ "\n");
val () = print ("@@isAscii_255=" ^ Bool.toString (Char.isAscii (Char.chr 255)) ^ "\n");
val () = print ("@@toLower_A=" ^ Int.toString (Char.ord (Char.toLower #"A")) ^ "\n");
val () = print ("@@toLower_a=" ^ Int.toString (Char.ord (Char.toLower #"a")) ^ "\n");
val () = print ("@@toLower_0=" ^ Int.toString (Char.ord (Char.toLower #"0")) ^ "\n");
val () = print ("@@toLower_255=" ^ Int.toString (Char.ord (Char.toLower (Char.chr 255))) ^ "\n");
val () = print ("@@toUpper_a=" ^ Int.toString (Char.ord (Char.toUpper #"a")) ^ "\n");
val () = print ("@@toUpper_z=" ^ Int.toString (Char.ord (Char.toUpper #"z")) ^ "\n");
val () = print ("@@toUpper_A=" ^ Int.toString (Char.ord (Char.toUpper #"A")) ^ "\n");
val () = print ("@@toUpper_255=" ^ Int.toString (Char.ord (Char.toUpper (Char.chr 255))) ^ "\n");
val () = print ("@@ord_0=" ^ Int.toString (Char.ord (Char.chr 0)) ^ "\n");
val () = print ("@@ord_255=" ^ Int.toString (Char.ord (Char.chr 255)) ^ "\n");
val () = print ("@@chr_65=" ^ Int.toString (Char.ord (Char.chr 65)) ^ "\n");
val () = print ("@@succ_A=" ^ Int.toString (Char.ord (Char.succ #"A")) ^ "\n");
val () = print ("@@pred_B=" ^ Int.toString (Char.ord (Char.pred #"B")) ^ "\n");
val () = print ("@@succ_254=" ^ Int.toString (Char.ord (Char.succ (Char.chr 254))) ^ "\n");
val () = print ("@@pred_1=" ^ Int.toString (Char.ord (Char.pred (Char.chr 1))) ^ "\n");
val () = print ("@@contains_yes=" ^ Bool.toString (Char.contains "hello" #"e") ^ "\n");
val () = print ("@@contains_no=" ^ Bool.toString (Char.contains "hello" #"z") ^ "\n");
val () = print ("@@contains_empty=" ^ Bool.toString (Char.contains "" #"a") ^ "\n");
val () = print ("@@notContains_yes=" ^ Bool.toString (Char.notContains "hello" #"z") ^ "\n");
val () = print ("@@notContains_no=" ^ Bool.toString (Char.notContains "hello" #"e") ^ "\n");
val () = print ("@@compare_lt=" ^ (case Char.compare (#"a", #"b") of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@compare_eq=" ^ (case Char.compare (#"x", #"x") of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@compare_gt=" ^ (case Char.compare (Char.chr 255, Char.chr 0) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
