(* diff-corpus category: char_escapes (deep sweep 2026-06-09) *)

val () = print ("@@ctos_nl=" ^ Char.toString #"\n" ^ "\n");
val () = print ("@@ctos_tab=" ^ Char.toString #"\t" ^ "\n");
val () = print ("@@ctos_bslash=" ^ Char.toString #"\\" ^ "\n");
val () = print ("@@ctos_dquote=" ^ Char.toString #"\"" ^ "\n");
val () = print ("@@ctos_del=" ^ Char.toString (Char.chr 127) ^ "\n");
val () = print ("@@ctos_nul=" ^ Char.toString (Char.chr 0) ^ "\n");
val () = print ("@@ctos_esc=" ^ Char.toString (Char.chr 27) ^ "\n");
val () = print ("@@ctos_bell=" ^ Char.toString (Char.chr 7) ^ "\n");
val () = print ("@@ctos_printA=" ^ Char.toString #"A" ^ "\n");
val () = print ("@@ctos_space=" ^ Char.toString #" " ^ "\n");
val () = print ("@@ctos_high=" ^ Char.toString (Char.chr 200) ^ "\n");
val () = print ("@@ctos_max=" ^ Char.toString (Char.chr 255) ^ "\n");
val () = print ("@@ctocstr_nl=" ^ Char.toCString #"\n" ^ "\n");
val () = print ("@@ctocstr_bslash=" ^ Char.toCString #"\\" ^ "\n");
val () = print ("@@ctocstr_dquote=" ^ Char.toCString #"\"" ^ "\n");
val () = print ("@@ctocstr_squote=" ^ Char.toCString #"'" ^ "\n");
val () = print ("@@ctocstr_nul=" ^ Char.toCString (Char.chr 0) ^ "\n");
val () = print ("@@ctocstr_del=" ^ Char.toCString (Char.chr 127) ^ "\n");
val () = print ("@@ctocstr_esc=" ^ Char.toCString (Char.chr 27) ^ "\n");
val () = print ("@@ctocstr_bell=" ^ Char.toCString (Char.chr 7) ^ "\n");
val () = print ("@@cfroms_nl=" ^ (case Char.fromString "\\n" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfroms_dec=" ^ (case Char.fromString "\\200" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfroms_bad=" ^ (case Char.fromString "\\q" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfroms_empty=" ^ (case Char.fromString "" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfroms_plain=" ^ (case Char.fromString "A" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfromcstr_x=" ^ (case Char.fromCString "\\x7e" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfromcstr_nul=" ^ (case Char.fromCString "\\0" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfromcstr_oct=" ^ (case Char.fromCString "\\033" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@cfromcstr_bad=" ^ (case Char.fromCString "\\z" of SOME c => "SOME " ^ Int.toString (Char.ord c) | NONE => "NONE") ^ "\n");
val () = print ("@@stos_specials=" ^ String.toString "a\tb\nc\\d\"e" ^ "\n");
val () = print ("@@stos_ctrl=" ^ String.toString (String.implode [Char.chr 0, Char.chr 1, Char.chr 27, Char.chr 127]) ^ "\n");
val () = print ("@@stos_high=" ^ String.toString (String.implode [Char.chr 200, Char.chr 255]) ^ "\n");
val () = print ("@@stos_empty=" ^ String.toString "" ^ "\n");
val () = print ("@@sfroms_ok=" ^ (case String.fromString "a\\tb\\nc" of SOME s => s | NONE => "NONE") ^ "\n");
val () = print ("@@sfroms_gap=" ^ (case String.fromString "ab\\   \\cd" of SOME s => s | NONE => "NONE") ^ "\n");
val () = print ("@@sfroms_bad=" ^ (case String.fromString "ab\\qcd" of SOME s => s | NONE => "NONE") ^ "\n");
val () = print ("@@sfroms_empty=" ^ (case String.fromString "" of SOME s => "[" ^ s ^ "]" | NONE => "NONE") ^ "\n");
val () = print ("@@stocstr=" ^ String.toCString "a\tb\nc\\d\"e'f" ^ "\n");
val () = print ("@@sfromcstr=" ^ (case String.fromCString "a\\tb\\x7ec" of SOME s => String.toString s | NONE => "NONE") ^ "\n");
val () = print ("@@rt_all=" ^ (let val s = String.implode (List.tabulate (256, Char.chr)) in case String.fromString (String.toString s) of SOME r => Bool.toString (r = s) | NONE => "NONE" end) ^ "\n");
val () = print ("@@rt_char=" ^ (let fun ok c = (case Char.fromString (Char.toString c) of SOME r => r = c | NONE => false) in Bool.toString (List.all ok (List.tabulate (256, Char.chr))) end) ^ "\n");
val () = print ("@@rt_cstr=" ^ (let fun ok c = (case Char.fromCString (Char.toCString c) of SOME r => r = c | NONE => false) in Bool.toString (List.all ok (List.tabulate (256, Char.chr))) end) ^ "\n");
