(* diff-corpus category: fixedint — FixedInt/default-int arithmetic and OVERFLOW boundaries *)

val () = print ("@@maxint_value=" ^ Int.toString (valOf Int.maxInt) ^ "\n");
val () = print ("@@minint_value=" ^ Int.toString (valOf Int.minInt) ^ "\n");
val () = print ("@@int_precision=" ^ Int.toString (valOf Int.precision) ^ "\n");
val () = print ("@@maxint_minus1_inrange=" ^ Int.toString (valOf Int.maxInt - 1) ^ "\n");
val () = print ("@@minint_plus1_inrange=" ^ Int.toString (valOf Int.minInt + 1) ^ "\n");
val s = (Int.toString (valOf Int.maxInt + 1)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@maxint_plus1_overflow=" ^ s ^ "\n");
val s = (Int.toString (valOf Int.minInt - 1)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@minint_minus1_overflow=" ^ s ^ "\n");
val s = (Int.toString (~(valOf Int.minInt))) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@neg_minint_overflow=" ^ s ^ "\n");
val s = (Int.toString (abs (valOf Int.minInt))) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@abs_minint_overflow=" ^ s ^ "\n");
val () = print ("@@abs_maxint_inrange=" ^ Int.toString (abs (valOf Int.maxInt)) ^ "\n");
val () = print ("@@neg_maxint_inrange=" ^ Int.toString (~(valOf Int.maxInt)) ^ "\n");
val s = (Int.toString (valOf Int.minInt div ~1)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@minint_div_neg1_overflow=" ^ s ^ "\n");
val s = (Int.toString (Int.quot (valOf Int.minInt, ~1))) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@minint_quot_neg1_overflow=" ^ s ^ "\n");
val s = (Int.toString (valOf Int.maxInt * 2)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@maxint_times2_overflow=" ^ s ^ "\n");
val s = (Int.toString (3037000500 * 3037000500)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@sqrt_maxint_squared_overflow=" ^ s ^ "\n");
val () = print ("@@big_mult_inrange=" ^ Int.toString (3037000499 * 1000000000) ^ "\n");
val () = print ("@@div_neg7_2=" ^ Int.toString (~7 div 2) ^ "\n");
val () = print ("@@mod_neg7_2=" ^ Int.toString (~7 mod 2) ^ "\n");
val () = print ("@@div_7_neg2=" ^ Int.toString (7 div ~2) ^ "\n");
val () = print ("@@mod_7_neg2=" ^ Int.toString (7 mod ~2) ^ "\n");
val () = print ("@@div_neg7_neg2=" ^ Int.toString (~7 div ~2) ^ "\n");
val () = print ("@@mod_neg7_neg2=" ^ Int.toString (~7 mod ~2) ^ "\n");
val () = print ("@@quot_neg7_2=" ^ Int.toString (Int.quot (~7, 2)) ^ "\n");
val () = print ("@@rem_neg7_2=" ^ Int.toString (Int.rem (~7, 2)) ^ "\n");
val () = print ("@@quot_7_neg2=" ^ Int.toString (Int.quot (7, ~2)) ^ "\n");
val () = print ("@@rem_7_neg2=" ^ Int.toString (Int.rem (7, ~2)) ^ "\n");
val () = print ("@@rem_neg7_neg2=" ^ Int.toString (Int.rem (~7, ~2)) ^ "\n");
val () = print ("@@div_minint_2=" ^ Int.toString (valOf Int.minInt div 2) ^ "\n");
val () = print ("@@mod_minint_3=" ^ Int.toString (valOf Int.minInt mod 3) ^ "\n");
val () = print ("@@int_sign_neg=" ^ Int.toString (Int.sign (~42)) ^ "\n");
val () = print ("@@int_sign_zero=" ^ Int.toString (Int.sign 0) ^ "\n");
val () = print ("@@int_sign_minint=" ^ Int.toString (Int.sign (valOf Int.minInt)) ^ "\n");
val () = print ("@@int_samesign_negs=" ^ Bool.toString (Int.sameSign (~5, ~99)) ^ "\n");
val () = print ("@@int_samesign_zero_pos=" ^ Bool.toString (Int.sameSign (0, 7)) ^ "\n");
val () = print ("@@int_compare_max_min=" ^ (case Int.compare (valOf Int.maxInt, valOf Int.minInt) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@int_min_max_fns=" ^ Int.toString (Int.min (valOf Int.minInt, valOf Int.maxInt)) ^ "," ^ Int.toString (Int.max (valOf Int.minInt, valOf Int.maxInt)) ^ "\n");
val () = print ("@@minint_sub_self_zero=" ^ Int.toString (valOf Int.minInt - valOf Int.minInt) ^ "\n");
val s = (Int.toString (valOf Int.maxInt - valOf Int.minInt)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@maxint_minus_minint_overflow=" ^ s ^ "\n");
val () = print ("@@mod_zero_dividend=" ^ Int.toString (0 mod ~5) ^ "\n");
val () = print ("@@div_exact_neg=" ^ Int.toString (~10 div 5) ^ "," ^ Int.toString (~10 mod 5) ^ "\n");
