(* diff-corpus category: int_radix (deep sweep 2026-06-09) *)

val () = print ("@@fmt_bin_0=" ^ Int.fmt StringCvt.BIN 0 ^ "\n");
val () = print ("@@fmt_oct_0=" ^ Int.fmt StringCvt.OCT 0 ^ "\n");
val () = print ("@@fmt_dec_0=" ^ Int.fmt StringCvt.DEC 0 ^ "\n");
val () = print ("@@fmt_hex_0=" ^ Int.fmt StringCvt.HEX 0 ^ "\n");
val () = print ("@@fmt_bin_255=" ^ Int.fmt StringCvt.BIN 255 ^ "\n");
val () = print ("@@fmt_oct_255=" ^ Int.fmt StringCvt.OCT 255 ^ "\n");
val () = print ("@@fmt_dec_255=" ^ Int.fmt StringCvt.DEC 255 ^ "\n");
val () = print ("@@fmt_hex_255=" ^ Int.fmt StringCvt.HEX 255 ^ "\n");
val () = print ("@@fmt_bin_neg255=" ^ Int.fmt StringCvt.BIN (~255) ^ "\n");
val () = print ("@@fmt_oct_neg255=" ^ Int.fmt StringCvt.OCT (~255) ^ "\n");
val () = print ("@@fmt_dec_neg255=" ^ Int.fmt StringCvt.DEC (~255) ^ "\n");
val () = print ("@@fmt_hex_neg255=" ^ Int.fmt StringCvt.HEX (~255) ^ "\n");
val () = print ("@@fmt_hex_max=" ^ Int.fmt StringCvt.HEX (valOf Int.maxInt) ^ "\n");
val () = print ("@@fmt_hex_min=" ^ Int.fmt StringCvt.HEX (valOf Int.minInt) ^ "\n");
val () = print ("@@fmt_bin_min=" ^ Int.fmt StringCvt.BIN (valOf Int.minInt) ^ "\n");
val () = print ("@@fmt_dec_max=" ^ Int.fmt StringCvt.DEC (valOf Int.maxInt) ^ "\n");
val () = print ("@@fmt_dec_min=" ^ Int.fmt StringCvt.DEC (valOf Int.minInt) ^ "\n");
val () = print ("@@tostr_vs_fmtdec_max=" ^ Bool.toString (Int.toString (valOf Int.maxInt) = Int.fmt StringCvt.DEC (valOf Int.maxInt)) ^ "\n");
val () = print ("@@tostr_vs_fmtdec_min=" ^ Bool.toString (Int.toString (valOf Int.minInt) = Int.fmt StringCvt.DEC (valOf Int.minInt)) ^ "\n");
val () = print ("@@tostr_neg255=" ^ Int.toString (~255) ^ "\n");
val () = print ("@@scan_dec_42=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "42" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_hex_1F=" ^ (case StringCvt.scanString (Int.scan StringCvt.HEX) "1F" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_hex_0x1F=" ^ (case StringCvt.scanString (Int.scan StringCvt.HEX) "0x1F" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_bin_1010=" ^ (case StringCvt.scanString (Int.scan StringCvt.BIN) "1010" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_oct_777=" ^ (case StringCvt.scanString (Int.scan StringCvt.OCT) "777" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_neg5=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "~5" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_ws12=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "  12" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_99bottles=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "99bottles" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_empty=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_garbage=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "xyz" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_hex_lower_ff=" ^ (case StringCvt.scanString (Int.scan StringCvt.HEX) "ff" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_plus5=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "+5" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_hex_0xDEAD=" ^ (case StringCvt.scanString (Int.scan StringCvt.HEX) "DEAD" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@fromstr_dec_12=" ^ (case Int.fromString "12" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@fromstr_0x1F=" ^ (case Int.fromString "0x1F" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@fromstr_neg5=" ^ (case Int.fromString "~5" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@fromstr_ws12=" ^ (case Int.fromString "  12" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@fromstr_99bottles=" ^ (case Int.fromString "99bottles" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@fromstr_empty=" ^ (case Int.fromString "" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = let val s = ((case StringCvt.scanString (Int.scan StringCvt.DEC) "9223372036854775807999" of SOME n => Int.toString n | NONE => "NONE") handle Overflow => "OVERFLOW" | _ => "OTHER") in print ("@@scan_dec_overflow=" ^ s ^ "\n") end;
val () = let val s = ((case StringCvt.scanString (Int.scan StringCvt.DEC) "4611686018427387903" of SOME n => Int.toString n | NONE => "NONE") handle Overflow => "OVERFLOW" | _ => "OTHER") in print ("@@scan_dec_atmax=" ^ s ^ "\n") end;
val () = let val s = ((case StringCvt.scanString (Int.scan StringCvt.DEC) "4611686018427387904" of SOME n => Int.toString n | NONE => "NONE") handle Overflow => "OVERFLOW" | _ => "OTHER") in print ("@@scan_dec_overmax=" ^ s ^ "\n") end;
val () = let val s = ((case StringCvt.scanString (Int.scan StringCvt.DEC) "~4611686018427387905" of SOME n => Int.toString n | NONE => "NONE") handle Overflow => "OVERFLOW" | _ => "OTHER") in print ("@@scan_dec_undermin=" ^ s ^ "\n") end;
val () = print ("@@scan_hex_0x_only=" ^ (case StringCvt.scanString (Int.scan StringCvt.HEX) "0x" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_dec_leadzero=" ^ (case StringCvt.scanString (Int.scan StringCvt.DEC) "007" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_bin_2=" ^ (case StringCvt.scanString (Int.scan StringCvt.BIN) "2" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@scan_oct_8=" ^ (case StringCvt.scanString (Int.scan StringCvt.OCT) "8" of SOME n => Int.toString n | NONE => "NONE") ^ "\n");
val () = print ("@@roundtrip_max_hex=" ^ Bool.toString (StringCvt.scanString (Int.scan StringCvt.HEX) (Int.fmt StringCvt.HEX (valOf Int.maxInt)) = Int.maxInt) ^ "\n");
val () = print ("@@roundtrip_min_dec=" ^ Bool.toString (StringCvt.scanString (Int.scan StringCvt.DEC) (Int.fmt StringCvt.DEC (valOf Int.minInt)) = Int.minInt) ^ "\n");
