(* diff-corpus category: largeword (deep sweep 2026-06-09) *)

val () = print ("@@wordSize=" ^ Int.toString LargeWord.wordSize ^ "\n");
val () = print ("@@fromInt_neg1=" ^ LargeWord.toString (LargeWord.fromInt ~1) ^ "\n");
val () = print ("@@fromInt_0=" ^ LargeWord.toString (LargeWord.fromInt 0) ^ "\n");
val () = print ("@@andb=" ^ LargeWord.toString (LargeWord.andb (LargeWord.fromInt ~1, LargeWord.fromInt 255)) ^ "\n");
val () = print ("@@orb=" ^ LargeWord.toString (LargeWord.orb (LargeWord.fromInt 240, LargeWord.fromInt 15)) ^ "\n");
val () = print ("@@xorb=" ^ LargeWord.toString (LargeWord.xorb (LargeWord.fromInt ~1, LargeWord.fromInt 255)) ^ "\n");
val () = print ("@@notb0=" ^ LargeWord.toString (LargeWord.notb (LargeWord.fromInt 0)) ^ "\n");
val () = print ("@@notb_neg1=" ^ LargeWord.toString (LargeWord.notb (LargeWord.fromInt ~1)) ^ "\n");
val () = print ("@@shl_1_63=" ^ LargeWord.toString (LargeWord.<< (LargeWord.fromInt 1, Word.fromInt 63)) ^ "\n");
val () = print ("@@shl_1_64=" ^ LargeWord.toString (LargeWord.<< (LargeWord.fromInt 1, Word.fromInt 64)) ^ "\n");
val () = print ("@@shl_neg1_4=" ^ LargeWord.toString (LargeWord.<< (LargeWord.fromInt ~1, Word.fromInt 4)) ^ "\n");
val () = print ("@@lshr_neg1_60=" ^ LargeWord.toString (LargeWord.>> (LargeWord.fromInt ~1, Word.fromInt 60)) ^ "\n");
val () = print ("@@lshr_neg1_64=" ^ LargeWord.toString (LargeWord.>> (LargeWord.fromInt ~1, Word.fromInt 64)) ^ "\n");
val () = print ("@@ashr_neg1_60=" ^ LargeWord.toString (LargeWord.~>> (LargeWord.fromInt ~1, Word.fromInt 60)) ^ "\n");
val () = print ("@@ashr_neg1_64=" ^ LargeWord.toString (LargeWord.~>> (LargeWord.fromInt ~1, Word.fromInt 64)) ^ "\n");
val () = print ("@@ashr_highbit_1=" ^ LargeWord.toString (LargeWord.~>> (LargeWord.<< (LargeWord.fromInt 1, Word.fromInt 63), Word.fromInt 1)) ^ "\n");
val () = print ("@@ashr_pos_2=" ^ LargeWord.toString (LargeWord.~>> (LargeWord.fromInt 1024, Word.fromInt 2)) ^ "\n");
val () = print ("@@add_wrap=" ^ LargeWord.toString (LargeWord.+ (LargeWord.fromInt ~1, LargeWord.fromInt 1)) ^ "\n");
val () = print ("@@sub_wrap=" ^ LargeWord.toString (LargeWord.- (LargeWord.fromInt 0, LargeWord.fromInt 1)) ^ "\n");
val () = print ("@@mul_wrap=" ^ LargeWord.toString (LargeWord.* (LargeWord.fromInt ~1, LargeWord.fromInt 2)) ^ "\n");
val () = print ("@@div=" ^ LargeWord.toString (LargeWord.div (LargeWord.fromInt ~1, LargeWord.fromInt 2)) ^ "\n");
val () = print ("@@mod=" ^ LargeWord.toString (LargeWord.mod (LargeWord.fromInt ~1, LargeWord.fromInt 3)) ^ "\n");
val () = print ("@@divzero=" ^ ((LargeWord.toString (LargeWord.div (LargeWord.fromInt 5, LargeWord.fromInt 0))) handle Div => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@toInt_small=" ^ Int.toString (LargeWord.toInt (LargeWord.fromInt 12345)) ^ "\n");
val () = print ("@@toIntX_neg1=" ^ Int.toString (LargeWord.toIntX (LargeWord.fromInt ~1)) ^ "\n");
val () = print ("@@toIntX_highbit=" ^ Int.toString (LargeWord.toIntX (LargeWord.<< (LargeWord.fromInt 1, Word.fromInt 63))) ^ "\n");
val () = print ("@@toInt_overflow=" ^ ((Int.toString (LargeWord.toInt (LargeWord.fromInt ~1))) handle Overflow => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@compare_lt=" ^ (case LargeWord.compare (LargeWord.fromInt 1, LargeWord.fromInt ~1) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@less_neg=" ^ Bool.toString (LargeWord.< (LargeWord.fromInt ~1, LargeWord.fromInt 1)) ^ "\n");
val () = print ("@@fromLargeInt_big=" ^ LargeWord.toString (LargeWord.fromLargeInt 9223372036854775808) ^ "\n");
val () = print ("@@toLargeInt_neg1=" ^ LargeInt.toString (LargeWord.toLargeInt (LargeWord.fromInt ~1)) ^ "\n");
val () = print ("@@toLargeIntX_neg1=" ^ LargeInt.toString (LargeWord.toLargeIntX (LargeWord.fromInt ~1)) ^ "\n");
val () = print ("@@word_to_large=" ^ LargeWord.toString (Word.toLarge (Word.fromInt ~1)) ^ "\n");
val () = print ("@@word_to_largeX=" ^ LargeWord.toString (Word.toLargeX (Word.fromInt ~1)) ^ "\n");
val () = print ("@@large_to_word=" ^ Word.toString (Word.fromLarge (LargeWord.fromInt ~1)) ^ "\n");
val () = print ("@@max_minus_one=" ^ LargeWord.toString (LargeWord.- (LargeWord.notb (LargeWord.fromInt 0), LargeWord.fromInt 1)) ^ "\n");
val () = print ("@@mul_big=" ^ LargeWord.toString (LargeWord.* (LargeWord.fromLargeInt 4294967296, LargeWord.fromLargeInt 4294967296)) ^ "\n");
val () = print ("@@fromLargeInt_2p64m1=" ^ LargeWord.toString (LargeWord.fromLargeInt 18446744073709551615) ^ "\n");
val () = print ("@@fromLargeInt_2p64=" ^ LargeWord.toString (LargeWord.fromLargeInt 18446744073709551616) ^ "\n");
