(* diff-corpus category: listpair (deep sweep 2026-06-09) *)

val () = print ("@@zip_eqlen=" ^ Int.toString (length (ListPair.zip ([1,2,3], [4,5,6]))) ^ "\n");
val () = print ("@@zip_trunc_left=" ^ Int.toString (length (ListPair.zip ([1,2,3,4,5], [10,20]))) ^ "\n");
val () = print ("@@zip_trunc_right=" ^ Int.toString (length (ListPair.zip ([1,2], [10,20,30,40]))) ^ "\n");
val () = print ("@@zip_empty_left=" ^ Int.toString (length (ListPair.zip ([], [1,2,3]))) ^ "\n");
val () = print ("@@zip_empty_both=" ^ Int.toString (length (ListPair.zip ([]:int list, []:int list))) ^ "\n");
val () = print ("@@zip_sum=" ^ Int.toString (foldl (fn ((a,b),s) => s+a+b) 0 (ListPair.zip ([1,2,3], [10,20,30]))) ^ "\n");
val () = print ("@@unzip_fst_sum=" ^ Int.toString (foldl (op +) 0 (#1 (ListPair.unzip [(1,10),(2,20),(3,30)]))) ^ "\n");
val () = print ("@@unzip_snd_sum=" ^ Int.toString (foldl (op +) 0 (#2 (ListPair.unzip [(1,10),(2,20),(3,30)]))) ^ "\n");
val () = print ("@@unzip_empty=" ^ Int.toString (length (#1 (ListPair.unzip ([]:(int*int) list))) + length (#2 (ListPair.unzip ([]:(int*int) list)))) ^ "\n");
val () = print ("@@map_sum=" ^ Int.toString (foldl (op +) 0 (ListPair.map (fn (a,b) => a*b) ([1,2,3], [4,5,6]))) ^ "\n");
val () = print ("@@map_trunc_len=" ^ Int.toString (length (ListPair.map (fn (a,b) => a+b) ([1,2,3,4], [10,20]))) ^ "\n");
val () = print ("@@map_empty_len=" ^ Int.toString (length (ListPair.map (fn (a,b) => a+b) ([], [1,2,3]))) ^ "\n");
val () = print ("@@mapEq_eqlen_sum=" ^ Int.toString (foldl (op +) 0 (ListPair.mapEq (fn (a,b) => a+b) ([1,2,3], [10,20,30]))) ^ "\n");
val () = print ("@@mapEq_uneq=" ^ ((ignore (ListPair.mapEq (fn (a,b) => a+b) ([1,2,3], [10,20])); "NO") handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@app_sum=" ^ Int.toString (let val r = ref 0 in ListPair.app (fn (a,b) => r := !r + a + b) ([1,2,3], [10,20,30]); !r end) ^ "\n");
val () = print ("@@app_trunc_sum=" ^ Int.toString (let val r = ref 0 in ListPair.app (fn (a,b) => r := !r + a + b) ([1,2,3,4,5], [10,20]); !r end) ^ "\n");
val () = print ("@@appEq_eqlen_sum=" ^ Int.toString (let val r = ref 0 in ListPair.appEq (fn (a,b) => r := !r + a + b) ([1,2,3], [10,20,30]); !r end) ^ "\n");
val () = print ("@@appEq_uneq=" ^ ((let val r = ref 0 in ListPair.appEq (fn (a,b) => r := !r + a + b) ([1,2,3], [10,20,30,40]); Int.toString (!r) end) handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@foldl=" ^ Int.toString (ListPair.foldl (fn (a,b,s) => s + a - b) 0 ([10,20,30], [1,2,3])) ^ "\n");
val () = print ("@@foldl_trunc=" ^ Int.toString (ListPair.foldl (fn (a,b,s) => s + a + b) 0 ([1,2,3,4], [10,20])) ^ "\n");
val () = print ("@@foldr=" ^ Int.toString (ListPair.foldr (fn (a,b,s) => s + a - b) 0 ([10,20,30], [1,2,3])) ^ "\n");
val () = print ("@@foldr_order=" ^ ListPair.foldr (fn (a,b,s) => Int.toString a ^ s) "" ([1,2,3], [9,9,9]) ^ "\n");
val () = print ("@@foldl_order=" ^ ListPair.foldl (fn (a,b,s) => Int.toString a ^ s) "" ([1,2,3], [9,9,9]) ^ "\n");
val () = print ("@@foldlEq_sum=" ^ Int.toString (ListPair.foldlEq (fn (a,b,s) => s + a + b) 0 ([1,2,3], [10,20,30])) ^ "\n");
val () = print ("@@foldlEq_uneq=" ^ ((Int.toString (ListPair.foldlEq (fn (a,b,s) => s + a + b) 0 ([1,2,3], [10,20]))) handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@foldrEq_sum=" ^ Int.toString (ListPair.foldrEq (fn (a,b,s) => s + a + b) 0 ([1,2,3], [10,20,30])) ^ "\n");
val () = print ("@@foldrEq_uneq=" ^ ((Int.toString (ListPair.foldrEq (fn (a,b,s) => s + a + b) 0 ([1,2,3,4], [10,20,30]))) handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@all_true=" ^ Bool.toString (ListPair.all (fn (a,b) => a < b) ([1,2,3], [10,20,30])) ^ "\n");
val () = print ("@@all_false=" ^ Bool.toString (ListPair.all (fn (a,b) => a < b) ([1,2,30], [10,20,30])) ^ "\n");
val () = print ("@@all_trunc_true=" ^ Bool.toString (ListPair.all (fn (a,b) => a = b) ([1,2,3,999], [1,2,3])) ^ "\n");
val () = print ("@@all_empty=" ^ Bool.toString (ListPair.all (fn (a,b) => a = b) ([], [1,2,3])) ^ "\n");
val () = print ("@@allEq_true=" ^ Bool.toString (ListPair.allEq (fn (a,b) => a < b) ([1,2,3], [10,20,30])) ^ "\n");
val () = print ("@@allEq_uneq_false=" ^ Bool.toString (ListPair.allEq (fn (a,b) => a = b) ([1,2,3,4], [1,2,3])) ^ "\n");
val () = print ("@@allEq_uneq_pred_false=" ^ Bool.toString (ListPair.allEq (fn (a,b) => a = b) ([1,2,99], [1,2,3,4])) ^ "\n");
val () = print ("@@allEq_empty_true=" ^ Bool.toString (ListPair.allEq (fn (a,b) => a = b) ([]:int list, []:int list)) ^ "\n");
val () = print ("@@exists_true=" ^ Bool.toString (ListPair.exists (fn (a,b) => a = b) ([1,2,3], [9,2,9])) ^ "\n");
val () = print ("@@exists_false=" ^ Bool.toString (ListPair.exists (fn (a,b) => a = b) ([1,2,3], [9,9,9])) ^ "\n");
val () = print ("@@exists_trunc=" ^ Bool.toString (ListPair.exists (fn (a,b) => a = 99) ([1,2,99], [10,20])) ^ "\n");
val () = print ("@@exists_empty=" ^ Bool.toString (ListPair.exists (fn (a,b) => true) ([], [1,2,3])) ^ "\n");
val () = print ("@@zipEq_eqlen_len=" ^ Int.toString (length (ListPair.zipEq ([1,2,3], [4,5,6]))) ^ "\n");
val () = print ("@@zipEq_uneq=" ^ ((ignore (ListPair.zipEq ([1,2,3], [4,5])); "NO") handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@zipEq_uneq_right=" ^ ((ignore (ListPair.zipEq ([1,2], [4,5,6,7])); "NO") handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@zipEq_empty_len=" ^ Int.toString (length (ListPair.zipEq ([]:int list, []:int list))) ^ "\n");
val () = print ("@@zipEq_empty_vs_nonempty=" ^ ((ignore (ListPair.zipEq ([], [1])); "NO") handle ListPair.UnequalLengths => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@unzip_roundtrip=" ^ Int.toString (let val l = [(1,10),(2,20),(3,30)] val (a,b) = ListPair.unzip l in foldl (op +) 0 (ListPair.map (op +) (a,b)) end) ^ "\n");
