(* diff-corpus category: option_bool (deep sweep 2026-06-09) *)

val () = print ("@@getOpt_some=" ^ Int.toString (Option.getOpt (SOME 7, 99)) ^ "\n");
val () = print ("@@getOpt_none=" ^ Int.toString (Option.getOpt (NONE, 99)) ^ "\n");
val () = print ("@@isSome_some=" ^ Bool.toString (Option.isSome (SOME 0)) ^ "\n");
val () = print ("@@isSome_none=" ^ Bool.toString (Option.isSome NONE) ^ "\n");
val () = print ("@@valOf_some=" ^ Int.toString (Option.valOf (SOME ~5)) ^ "\n");
val () = print ("@@map_some=" ^ Int.toString (Option.getOpt (Option.map (fn x => x + 1) (SOME 41), ~1)) ^ "\n");
val () = print ("@@map_none=" ^ Bool.toString (Option.isSome (Option.map (fn x => x + 1) NONE)) ^ "\n");
val () = print ("@@mapPartial_some=" ^ Int.toString (Option.getOpt (Option.mapPartial (fn x => if x > 0 then SOME (x*2) else NONE) (SOME 10), ~1)) ^ "\n");
val () = print ("@@mapPartial_filterout=" ^ Bool.toString (Option.isSome (Option.mapPartial (fn x => if x > 0 then SOME x else NONE) (SOME ~3))) ^ "\n");
val () = print ("@@mapPartial_none=" ^ Bool.toString (Option.isSome (Option.mapPartial (fn x => SOME x) NONE)) ^ "\n");
val () = print ("@@compose_some=" ^ Int.toString (Option.getOpt (Option.compose (fn x => x + 100, fn y => if y then SOME 5 else NONE) true, ~1)) ^ "\n");
val () = print ("@@compose_none=" ^ Bool.toString (Option.isSome (Option.compose (fn x => x + 100, fn y => if y then SOME 5 else NONE) false)) ^ "\n");
val () = print ("@@composePartial_some=" ^ Int.toString (Option.getOpt (Option.composePartial (fn x => if x > 0 then SOME (x+1) else NONE, fn y => SOME (y * 3)) 4, ~1)) ^ "\n");
val () = print ("@@composePartial_innerNone=" ^ Bool.toString (Option.isSome (Option.composePartial (fn x => SOME x, fn y => NONE) 4)) ^ "\n");
val () = print ("@@join_somesome=" ^ Int.toString (Option.getOpt (Option.join (SOME (SOME 88)), ~1)) ^ "\n");
val () = print ("@@join_somenone=" ^ Bool.toString (Option.isSome (Option.join (SOME NONE))) ^ "\n");
val () = print ("@@join_none=" ^ Bool.toString (Option.isSome (Option.join NONE)) ^ "\n");
val () = print ("@@filter_keep=" ^ Bool.toString (Option.isSome (Option.filter (fn x => x mod 2 = 0) 4)) ^ "\n");
val () = print ("@@filter_drop=" ^ Bool.toString (Option.isSome (Option.filter (fn x => x mod 2 = 0) 5)) ^ "\n");
val () = print ("@@app_runs=" ^ (let val r = ref 0 in Option.app (fn x => r := x) (SOME 17); Int.toString (!r) end) ^ "\n");
val () = print ("@@app_skips=" ^ (let val r = ref 0 in Option.app (fn x => r := x) NONE; Int.toString (!r) end) ^ "\n");
val () = print ("@@bool_toString_t=" ^ Bool.toString true ^ "\n");
val () = print ("@@bool_toString_f=" ^ Bool.toString false ^ "\n");
val () = print ("@@bool_not_t=" ^ Bool.toString (Bool.not true) ^ "\n");
val () = print ("@@bool_fromString_true=" ^ Bool.toString (Option.getOpt (Bool.fromString "true", false)) ^ "\n");
val () = print ("@@bool_fromString_false=" ^ Bool.toString (Option.isSome (Bool.fromString "false")) ^ "\n");
val () = print ("@@bool_fromString_bad=" ^ Bool.toString (Option.isSome (Bool.fromString "yes")) ^ "\n");
val () = print ("@@bool_fromString_leadingws=" ^ Bool.toString (Option.getOpt (Bool.fromString "  true", false)) ^ "\n");
val () = print ("@@bool_fromString_trailing=" ^ Bool.toString (Option.getOpt (Bool.fromString "truex", false)) ^ "\n");
val () = print ("@@bool_fromString_empty=" ^ Bool.toString (Option.isSome (Bool.fromString "")) ^ "\n");
val () = print ("@@gen_compose=" ^ Int.toString (((fn x => x + 1) o (fn x => x * 2)) 10) ^ "\n");
val () = print ("@@gen_before=" ^ Int.toString ((let val r = ref 0 in (42 before (r := 1)) end)) ^ "\n");
val () = print ("@@tuple_fst=" ^ Int.toString (#1 (7, 8, 9)) ^ "\n");
val () = print ("@@tuple_snd=" ^ Int.toString (#2 (7, 8, 9)) ^ "\n");
val () = print ("@@gen_ignore=" ^ (case ignore (1 + 1) of () => "unit") ^ "\n");
val () = print ("@@order_less=" ^ (case Int.compare (1, 2) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@order_equal=" ^ (case Int.compare (5, 5) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@order_greater=" ^ (case Int.compare (9, 2) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@valOf_none_exn=" ^ ((Int.toString (Option.valOf NONE)) handle Option => "CAUGHT_Option" | _ => "OTHER") ^ "\n");
val () = print ("@@valOf_none_empty=" ^ ((Option.valOf (NONE : int option); "NO") handle Empty => "CAUGHT_Empty" | Option => "CAUGHT_Option" | _ => "OTHER") ^ "\n");
