(* diff-corpus category: real_fmt (deep sweep 2026-06-09) *)

val () = print ("@@fix0_zero=" ^ Real.fmt (StringCvt.FIX (SOME 0)) 0.0 ^ "\n");
val () = print ("@@fix2_zero=" ^ Real.fmt (StringCvt.FIX (SOME 2)) 0.0 ^ "\n");
val () = print ("@@fix6_negzero=" ^ Real.fmt (StringCvt.FIX (SOME 6)) (~0.0) ^ "\n");
val () = print ("@@fix0_one=" ^ Real.fmt (StringCvt.FIX (SOME 0)) 1.0 ^ "\n");
val () = print ("@@fix2_one=" ^ Real.fmt (StringCvt.FIX (SOME 2)) 1.0 ^ "\n");
val () = print ("@@fix6_negone=" ^ Real.fmt (StringCvt.FIX (SOME 6)) (~1.0) ^ "\n");
val () = print ("@@fix2_half=" ^ Real.fmt (StringCvt.FIX (SOME 2)) 0.5 ^ "\n");
val () = print ("@@fix10_pi=" ^ Real.fmt (StringCvt.FIX (SOME 10)) 3.14159265358979 ^ "\n");
val () = print ("@@fix0_pi=" ^ Real.fmt (StringCvt.FIX (SOME 0)) 3.14159265358979 ^ "\n");
val () = print ("@@fix2_e10=" ^ Real.fmt (StringCvt.FIX (SOME 2)) 1e10 ^ "\n");
val () = print ("@@fix6_em10=" ^ Real.fmt (StringCvt.FIX (SOME 6)) 1e~10 ^ "\n");
val () = print ("@@fix10_em10=" ^ Real.fmt (StringCvt.FIX (SOME 10)) 1e~10 ^ "\n");
val () = print ("@@fix6_big=" ^ Real.fmt (StringCvt.FIX (SOME 6)) 123456.789 ^ "\n");
val () = print ("@@fix0_big=" ^ Real.fmt (StringCvt.FIX (SOME 0)) 123456.789 ^ "\n");
val () = print ("@@fix2_round=" ^ Real.fmt (StringCvt.FIX (SOME 2)) 2.675 ^ "\n");
val () = print ("@@sci0_zero=" ^ Real.fmt (StringCvt.SCI (SOME 0)) 0.0 ^ "\n");
val () = print ("@@sci3_one=" ^ Real.fmt (StringCvt.SCI (SOME 3)) 1.0 ^ "\n");
val () = print ("@@sci6_pi=" ^ Real.fmt (StringCvt.SCI (SOME 6)) 3.14159265358979 ^ "\n");
val () = print ("@@sci3_e10=" ^ Real.fmt (StringCvt.SCI (SOME 3)) 1e10 ^ "\n");
val () = print ("@@sci3_em10=" ^ Real.fmt (StringCvt.SCI (SOME 3)) 1e~10 ^ "\n");
val () = print ("@@sci0_big=" ^ Real.fmt (StringCvt.SCI (SOME 0)) 123456.789 ^ "\n");
val () = print ("@@sci6_negbig=" ^ Real.fmt (StringCvt.SCI (SOME 6)) (~123456.789) ^ "\n");
val () = print ("@@gen1_zero=" ^ Real.fmt (StringCvt.GEN (SOME 1)) 0.0 ^ "\n");
val () = print ("@@gen6_one=" ^ Real.fmt (StringCvt.GEN (SOME 6)) 1.0 ^ "\n");
val () = print ("@@gen6_pi=" ^ Real.fmt (StringCvt.GEN (SOME 6)) 3.14159265358979 ^ "\n");
val () = print ("@@gen12_pi=" ^ Real.fmt (StringCvt.GEN (SOME 12)) 3.14159265358979 ^ "\n");
val () = print ("@@gen6_e10=" ^ Real.fmt (StringCvt.GEN (SOME 6)) 1e10 ^ "\n");
val () = print ("@@gen6_em10=" ^ Real.fmt (StringCvt.GEN (SOME 6)) 1e~10 ^ "\n");
val () = print ("@@gen1_big=" ^ Real.fmt (StringCvt.GEN (SOME 1)) 123456.789 ^ "\n");
val () = print ("@@gen12_big=" ^ Real.fmt (StringCvt.GEN (SOME 12)) 123456.789 ^ "\n");
val () = print ("@@exact_zero=" ^ Real.fmt StringCvt.EXACT 0.0 ^ "\n");
val () = print ("@@exact_half=" ^ Real.fmt StringCvt.EXACT 0.5 ^ "\n");
val () = print ("@@exact_one=" ^ Real.fmt StringCvt.EXACT 1.0 ^ "\n");
val () = print ("@@exact_negone=" ^ Real.fmt StringCvt.EXACT (~1.0) ^ "\n");
val () = print ("@@exact_e10=" ^ Real.fmt StringCvt.EXACT 1e10 ^ "\n");
val () = print ("@@ts_zero=" ^ Real.toString 0.0 ^ "\n");
val () = print ("@@ts_negzero=" ^ Real.toString (~0.0) ^ "\n");
val () = print ("@@ts_one=" ^ Real.toString 1.0 ^ "\n");
val () = print ("@@ts_half=" ^ Real.toString 0.5 ^ "\n");
val () = print ("@@ts_e10=" ^ Real.toString 1e10 ^ "\n");
val () = print ("@@ts_em10=" ^ Real.toString 1e~10 ^ "\n");
val () = print ("@@ts_big=" ^ Real.toString 123456.789 ^ "\n");
val () = print ("@@fmt_neg_prec=" ^ ((Real.fmt (StringCvt.FIX (SOME ~1)) 1.0) handle Size => "SIZE" | _ => "OTHER") ^ "\n");
val () = print ("@@fix8_third=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (1.0/3.0) ^ "\n");
val () = print ("@@sci6_third=" ^ Real.fmt (StringCvt.SCI (SOME 6)) (1.0/3.0) ^ "\n");
val () = print ("@@gen6_third=" ^ Real.fmt (StringCvt.GEN (SOME 6)) (1.0/3.0) ^ "\n");
val () = print ("@@fix2_neghalf=" ^ Real.fmt (StringCvt.FIX (SOME 2)) (~0.5) ^ "\n");
val () = print ("@@fix6_tiny=" ^ Real.fmt (StringCvt.FIX (SOME 6)) 4.94065645841247e~324 ^ "\n");
val () = print ("@@sci3_max=" ^ Real.fmt (StringCvt.SCI (SOME 3)) 1.7976931348623157e308 ^ "\n");
val () = print ("@@gen6_max=" ^ Real.fmt (StringCvt.GEN (SOME 6)) 1.7976931348623157e308 ^ "\n");
