(* diff-corpus category: real_arith2 (deep sweep 2026-06-09) *)

val () = print ("@@add=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (3.5 + 2.25) ^ "\n");
val () = print ("@@sub=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (1.0 - 4.5) ^ "\n");
val () = print ("@@mul=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (2.5 * 4.0) ^ "\n");
val () = print ("@@divexact=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (7.0 / 2.0) ^ "\n");
val () = print ("@@divposzero=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (1.0 / 0.0) ^ "\n");
val () = print ("@@divnegzero=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (~1.0 / 0.0) ^ "\n");
val () = print ("@@nanisnan=" ^ Bool.toString (Real.isNan (0.0 / 0.0)) ^ "\n");
val () = print ("@@inffinite=" ^ Bool.toString (Real.isFinite (1.0 / 0.0)) ^ "\n");
val () = print ("@@infisnan=" ^ Bool.toString (Real.isNan (1.0 / 0.0)) ^ "\n");
val () = print ("@@zerodivzeronan=" ^ Bool.toString (Real.isNan (0.0 / 0.0)) ^ "\n");
val () = print ("@@rempos=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.rem (7.5, 2.0)) ^ "\n");
val () = print ("@@remneg=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.rem (~7.5, 2.0)) ^ "\n");
val () = print ("@@reminfnan=" ^ Bool.toString (Real.isNan (Real.rem (1.0/0.0, 2.0))) ^ "\n");
val () = print ("@@remzero=" ^ Bool.toString (Real.isNan (Real.rem (5.0, 0.0))) ^ "\n");
val () = print ("@@abs=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.abs (~3.75)) ^ "\n");
val () = print ("@@absneginf=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.abs (~1.0/0.0)) ^ "\n");
val () = print ("@@neg=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (~ (2.5)) ^ "\n");
val () = print ("@@negzero=" ^ Bool.toString (Real.signBit (~ 0.0)) ^ "\n");
val () = print ("@@min=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.min (3.0, ~2.0)) ^ "\n");
val () = print ("@@max=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.max (3.0, ~2.0)) ^ "\n");
val () = print ("@@minnan=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.min (0.0/0.0, 5.0)) ^ "\n");
val () = print ("@@maxnan=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (Real.max (0.0/0.0, 5.0)) ^ "\n");
val () = print ("@@signpos=" ^ Int.toString (Real.sign 4.2) ^ "\n");
val () = print ("@@signneg=" ^ Int.toString (Real.sign (~4.2)) ^ "\n");
val () = print ("@@signzero=" ^ Int.toString (Real.sign 0.0) ^ "\n");
val () = print ("@@signnanexn=" ^ ((Int.toString (Real.sign (0.0/0.0))) handle Domain => "DOMAIN" | _ => "OTHER") ^ "\n");
val () = print ("@@samesignpp=" ^ Bool.toString (Real.sameSign (2.0, 3.0)) ^ "\n");
val () = print ("@@samesignpn=" ^ Bool.toString (Real.sameSign (2.0, ~3.0)) ^ "\n");
val () = print ("@@samesignnegzero=" ^ Bool.toString (Real.sameSign (~0.0, ~5.0)) ^ "\n");
val () = print ("@@cmplt=" ^ (case Real.compare (1.0, 2.0) of LESS => "L" | EQUAL => "E" | GREATER => "G") ^ "\n");
val () = print ("@@cmpeq=" ^ (case Real.compare (2.0, 2.0) of LESS => "L" | EQUAL => "E" | GREATER => "G") ^ "\n");
val () = print ("@@cmpnanexn=" ^ ((case Real.compare (0.0/0.0, 1.0) of LESS => "L" | EQUAL => "E" | GREATER => "G") handle IEEEReal.Unordered => "UNORDERED" | _ => "OTHER") ^ "\n");
val () = print ("@@cmprealU=" ^ (case Real.compareReal (0.0/0.0, 1.0) of IEEEReal.LESS => "L" | IEEEReal.EQUAL => "E" | IEEEReal.GREATER => "G" | IEEEReal.UNORDERED => "U") ^ "\n");
val () = print ("@@cmprealL=" ^ (case Real.compareReal (1.0, 2.0) of IEEEReal.LESS => "L" | IEEEReal.EQUAL => "E" | IEEEReal.GREATER => "G" | IEEEReal.UNORDERED => "U") ^ "\n");
val () = print ("@@eqtrue=" ^ Bool.toString (Real.== (1.5, 1.5)) ^ "\n");
val () = print ("@@eqnan=" ^ Bool.toString (Real.== (0.0/0.0, 0.0/0.0)) ^ "\n");
val () = print ("@@neqnan=" ^ Bool.toString (Real.!= (0.0/0.0, 0.0/0.0)) ^ "\n");
val () = print ("@@eqnegzero=" ^ Bool.toString (Real.== (~0.0, 0.0)) ^ "\n");
val () = print ("@@qmnan=" ^ Bool.toString (Real.?= (0.0/0.0, 5.0)) ^ "\n");
val () = print ("@@qmequal=" ^ Bool.toString (Real.?= (3.0, 3.0)) ^ "\n");
val () = print ("@@qmnegzero=" ^ Bool.toString (Real.?= (~0.0, 0.0)) ^ "\n");
val () = print ("@@ltinf=" ^ Bool.toString (Real.< (5.0, 1.0/0.0)) ^ "\n");
val () = print ("@@ltnan=" ^ Bool.toString (Real.< (0.0/0.0, 5.0)) ^ "\n");
val () = print ("@@lenan=" ^ Bool.toString (Real.<= (5.0, 0.0/0.0)) ^ "\n");
val () = print ("@@gtinf=" ^ Bool.toString (1.0/0.0 > 1e300) ^ "\n");
val () = print ("@@infminusinf=" ^ Bool.toString (Real.isNan (1.0/0.0 - 1.0/0.0)) ^ "\n");
val () = print ("@@infplusinf=" ^ Real.fmt (StringCvt.FIX (SOME 10)) (1.0/0.0 + 1.0/0.0) ^ "\n");
val () = print ("@@inftimeszero=" ^ Bool.toString (Real.isNan (1.0/0.0 * 0.0)) ^ "\n");
