(* diff-corpus category: real_classify (deep sweep 2026-06-09) *)

local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_zero=" ^ cs 0.0 ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_negzero=" ^ cs (~0.0) ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_norm=" ^ cs 1.5 ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_posinf=" ^ cs Real.posInf ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_neginf=" ^ cs Real.negInf ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_nan=" ^ cs (0.0/0.0) ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_minpos=" ^ cs Real.minPos ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_minnormal=" ^ cs Real.minNormalPos ^ "\n") end;
local fun cs r = (case Real.class r of IEEEReal.NORMAL => "NORMAL" | IEEEReal.ZERO => "ZERO" | IEEEReal.INF => "INF" | IEEEReal.NAN => "NAN" | IEEEReal.SUBNORMAL => "SUBNORMAL") in val () = print ("@@class_maxfinite=" ^ cs Real.maxFinite ^ "\n") end;
val () = print ("@@isnan_nan=" ^ Bool.toString (Real.isNan (0.0/0.0)) ^ "\n");
val () = print ("@@isnan_one=" ^ Bool.toString (Real.isNan 1.0) ^ "\n");
val () = print ("@@isnan_inf=" ^ Bool.toString (Real.isNan Real.posInf) ^ "\n");
val () = print ("@@isfinite_one=" ^ Bool.toString (Real.isFinite 1.0) ^ "\n");
val () = print ("@@isfinite_inf=" ^ Bool.toString (Real.isFinite Real.posInf) ^ "\n");
val () = print ("@@isfinite_neginf=" ^ Bool.toString (Real.isFinite Real.negInf) ^ "\n");
val () = print ("@@isfinite_nan=" ^ Bool.toString (Real.isFinite (0.0/0.0)) ^ "\n");
val () = print ("@@isfinite_zero=" ^ Bool.toString (Real.isFinite 0.0) ^ "\n");
val () = print ("@@signbit_pos=" ^ Bool.toString (Real.signBit 1.5) ^ "\n");
val () = print ("@@signbit_neg=" ^ Bool.toString (Real.signBit (~1.5)) ^ "\n");
val () = print ("@@signbit_negzero=" ^ Bool.toString (Real.signBit (~0.0)) ^ "\n");
val () = print ("@@signbit_poszero=" ^ Bool.toString (Real.signBit 0.0) ^ "\n");
val () = print ("@@signbit_neginf=" ^ Bool.toString (Real.signBit Real.negInf) ^ "\n");
val () = print ("@@isnormal_one=" ^ Bool.toString (Real.isNormal 1.0) ^ "\n");
val () = print ("@@isnormal_zero=" ^ Bool.toString (Real.isNormal 0.0) ^ "\n");
val () = print ("@@isnormal_minpos=" ^ Bool.toString (Real.isNormal Real.minPos) ^ "\n");
val () = print ("@@isnormal_inf=" ^ Bool.toString (Real.isNormal Real.posInf) ^ "\n");
val () = print ("@@isnormal_nan=" ^ Bool.toString (Real.isNormal (0.0/0.0)) ^ "\n");
local val {man, exp} = Real.toManExp 12.0 in val () = print ("@@manexp12_man=" ^ Real.fmt (StringCvt.FIX (SOME 8)) man ^ "_exp=" ^ Int.toString exp ^ "\n") end;
local val {man, exp} = Real.toManExp 1.0 in val () = print ("@@manexp1_man=" ^ Real.fmt (StringCvt.FIX (SOME 8)) man ^ "_exp=" ^ Int.toString exp ^ "\n") end;
local val {man, exp} = Real.toManExp 0.0 in val () = print ("@@manexp0_man=" ^ Real.fmt (StringCvt.FIX (SOME 8)) man ^ "_exp=" ^ Int.toString exp ^ "\n") end;
val () = print ("@@manexp_rt=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.fromManExp (Real.toManExp 12.5)) ^ "\n");
val () = print ("@@frommanexp=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.fromManExp {man=0.75, exp=4}) ^ "\n");
local val {whole, frac} = Real.split 3.25 in val () = print ("@@split325_whole=" ^ Real.fmt (StringCvt.FIX (SOME 8)) whole ^ "_frac=" ^ Real.fmt (StringCvt.FIX (SOME 8)) frac ^ "\n") end;
local val {whole, frac} = Real.split (~3.25) in val () = print ("@@split_neg325_whole=" ^ Real.fmt (StringCvt.FIX (SOME 8)) whole ^ "_frac=" ^ Real.fmt (StringCvt.FIX (SOME 8)) frac ^ "\n") end;
local val {whole, frac} = Real.split 5.0 in val () = print ("@@split5_whole=" ^ Real.fmt (StringCvt.FIX (SOME 8)) whole ^ "_frac=" ^ Real.fmt (StringCvt.FIX (SOME 8)) frac ^ "\n") end;
val () = print ("@@realmod_325=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realMod 3.25) ^ "\n");
val () = print ("@@realmod_neg325=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realMod (~3.25)) ^ "\n");
val () = print ("@@realmod_int=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realMod 7.0) ^ "\n");
val () = print ("@@minpos_fmt=" ^ Real.fmt (StringCvt.SCI (SOME 4)) Real.minPos ^ "\n");
val () = print ("@@maxfinite_fmt=" ^ Real.fmt (StringCvt.SCI (SOME 4)) Real.maxFinite ^ "\n");
val () = print ("@@minnormal_fmt=" ^ Real.fmt (StringCvt.SCI (SOME 4)) Real.minNormalPos ^ "\n");
val () = print ("@@nextafter_test=" ^ Bool.toString (Real.minPos > 0.0 andalso Real.minPos < Real.minNormalPos) ^ "\n");
