(* diff-corpus category: realint — real_int_boundary *)

val () = print ("@@floor_3_7=" ^ Int.toString (Real.floor 3.7) ^ "\n");
val () = print ("@@floor_neg_3_7=" ^ Int.toString (Real.floor (~3.7)) ^ "\n");
val () = print ("@@ceil_3_7=" ^ Int.toString (Real.ceil 3.7) ^ "\n");
val () = print ("@@ceil_neg_3_7=" ^ Int.toString (Real.ceil (~3.7)) ^ "\n");
val () = print ("@@trunc_3_7=" ^ Int.toString (Real.trunc 3.7) ^ "\n");
val () = print ("@@trunc_neg_3_7=" ^ Int.toString (Real.trunc (~3.7)) ^ "\n");
val () = print ("@@round_half_even_2_5=" ^ Int.toString (Real.round 2.5) ^ "\n");
val () = print ("@@round_half_even_3_5=" ^ Int.toString (Real.round 3.5) ^ "\n");
val () = print ("@@round_half_even_0_5=" ^ Int.toString (Real.round 0.5) ^ "\n");
val () = print ("@@round_half_even_neg_2_5=" ^ Int.toString (Real.round (~2.5)) ^ "\n");
val () = print ("@@round_half_even_neg_0_5=" ^ Int.toString (Real.round (~0.5)) ^ "\n");
val () = print ("@@round_1_5=" ^ Int.toString (Real.round 1.5) ^ "\n");
val () = print ("@@round_neg_3_7=" ^ Int.toString (Real.round (~3.7)) ^ "\n");
val () = print ("@@toint_to_nearest_2_5=" ^ Int.toString (Real.toInt IEEEReal.TO_NEAREST 2.5) ^ "\n");
val () = print ("@@toint_to_nearest_3_5=" ^ Int.toString (Real.toInt IEEEReal.TO_NEAREST 3.5) ^ "\n");
val () = print ("@@toint_downward_neg_2_3=" ^ Int.toString (Real.toInt IEEEReal.TO_NEGINF (~2.3)) ^ "\n");
val () = print ("@@toint_upward_2_3=" ^ Int.toString (Real.toInt IEEEReal.TO_POSINF 2.3) ^ "\n");
val () = print ("@@toint_tozero_neg_2_9=" ^ Int.toString (Real.toInt IEEEReal.TO_ZERO (~2.9)) ^ "\n");
val () = print ("@@tolargeint_nearest_7_5=" ^ IntInf.toString (Real.toLargeInt IEEEReal.TO_NEAREST 7.5) ^ "\n");
val () = print ("@@tolargeint_big=" ^ IntInf.toString (Real.toLargeInt IEEEReal.TO_ZERO 1.0e18) ^ "\n");
val () = print ("@@fromint_roundtrip=" ^ Int.toString (Real.trunc (Real.fromInt 4611686018427387)) ^ "\n");
val r = Real.fromInt (valOf Int.maxInt) * 4.0; val s = (Int.toString (Real.floor r)) handle Overflow => "CAUGHT" | _ => "OTHER"; val () = print ("@@floor_maxint_real_overflow=" ^ s ^ "\n");
val nan = 0.0 / 0.0; val s = (Int.toString (Real.round nan)) handle Overflow => "OVERFLOW" | Domain => "DOMAIN" | _ => "OTHER"; val () = print ("@@round_nan_overflow_exn=" ^ s ^ "\n");
val inf = 1.0 / 0.0; val s = (Int.toString (Real.floor inf)) handle Overflow => "OVERFLOW" | Domain => "DOMAIN" | _ => "OTHER"; val () = print ("@@floor_posinf_exn=" ^ s ^ "\n");
val () = print ("@@realfloor_2_5=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realFloor 2.5) ^ "\n");
val () = print ("@@realceil_neg_2_5=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realCeil (~2.5)) ^ "\n");
val () = print ("@@realround_half_even_2_5=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realRound 2.5) ^ "\n");
val () = print ("@@realround_half_even_3_5=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realRound 3.5) ^ "\n");
val () = print ("@@realtrunc_neg_3_9=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.realTrunc (~3.9)) ^ "\n");
val {man, exp} = Real.toManExp 12.0; val () = print ("@@tomanexp_man=" ^ Real.fmt (StringCvt.FIX (SOME 8)) man ^ ":" ^ Int.toString exp ^ "\n");
val () = print ("@@frommanexp_roundtrip=" ^ Real.fmt (StringCvt.FIX (SOME 8)) (Real.fromManExp {man=0.75, exp=4}) ^ "\n");
val {whole, frac} = Real.split 3.25; val () = print ("@@split_frac_3_25=" ^ Real.fmt (StringCvt.FIX (SOME 8)) whole ^ ":" ^ Real.fmt (StringCvt.FIX (SOME 8)) frac ^ "\n");
val s = (Real.fmt (StringCvt.FIX (SOME 8)) (Real.checkFloat 3.5)) handle Overflow => "OVERFLOW" | Div => "DIV" | _ => "OTHER"; val () = print ("@@checkfloat_normal=" ^ s ^ "\n");
val inf = 1.0 / 0.0; val s = (Real.fmt (StringCvt.FIX (SOME 8)) (Real.checkFloat inf)) handle Overflow => "OVERFLOW" | Div => "DIV" | _ => "OTHER"; val () = print ("@@checkfloat_inf_exn=" ^ s ^ "\n");
val nan = 0.0 / 0.0; val s = (Real.fmt (StringCvt.FIX (SOME 8)) (Real.checkFloat nan)) handle Overflow => "OVERFLOW" | Div => "DIV" | _ => "OTHER"; val () = print ("@@checkfloat_nan_exn=" ^ s ^ "\n");
val () = print ("@@fromint_minint_trunc=" ^ Int.toString (Real.trunc (Real.fromInt (valOf Int.minInt))) ^ "\n");
val () = print ("@@round_neg_0_4_zero=" ^ Int.toString (Real.round (~0.4)) ^ "\n");
