(* diff-corpus category: string_ops2 (deep sweep 2026-06-09) *)

val () = print ("@@concatwith_empty_sep=[" ^ String.concatWith "" ["a","b","c"] ^ "]\n");
val () = print ("@@concatwith_emptylist=[" ^ String.concatWith "," [] ^ "]\n");
val () = print ("@@concatwith_singleton=[" ^ String.concatWith "," ["x"] ^ "]\n");
val () = print ("@@concatwith_emptystrings=[" ^ String.concatWith "-" ["","",""] ^ "]\n");
val () = print ("@@fields_multi=[" ^ String.concatWith "|" (String.fields (fn c => c = #",") ",,a,,b,,") ^ "]\n");
val () = print ("@@tokens_multi=[" ^ String.concatWith "|" (String.tokens (fn c => c = #",") ",,a,,b,,") ^ "]\n");
val () = print ("@@fields_nodelim=[" ^ String.concatWith "|" (String.fields (fn c => c = #",") "abc") ^ "]\n");
val () = print ("@@tokens_empty=[" ^ String.concatWith "|" (String.tokens (fn c => c = #",") "") ^ "]\n");
val () = print ("@@fields_empty=[" ^ String.concatWith "|" (String.fields (fn c => c = #",") "") ^ "]\n");
val () = print ("@@fields_alldelim=[" ^ String.concatWith "|" (String.fields (fn c => c = #",") ",,,") ^ "]\n");
val () = print ("@@translate_dup=[" ^ String.translate (fn c => Char.toString c ^ Char.toString c) "abc" ^ "]\n");
val () = print ("@@translate_drop=[" ^ String.translate (fn c => if c = #" " then "" else Char.toString c) "a b c" ^ "]\n");
val () = print ("@@translate_empty=[" ^ String.translate (fn c => "X") "" ^ "]\n");
val () = print ("@@map_upper=[" ^ String.map Char.toUpper "Hello, World" ^ "]\n");
val () = print ("@@map_empty=[" ^ String.map Char.toUpper "" ^ "]\n");
val () = print ("@@issubstring_empty_needle=" ^ Bool.toString (String.isSubstring "" "abc") ^ "\n");
val () = print ("@@issubstring_empty_both=" ^ Bool.toString (String.isSubstring "" "") ^ "\n");
val () = print ("@@issubstring_in_empty=" ^ Bool.toString (String.isSubstring "a" "") ^ "\n");
val () = print ("@@issubstring_mid=" ^ Bool.toString (String.isSubstring "lo,W" "Hello,World") ^ "\n");
val () = print ("@@isprefix_empty=" ^ Bool.toString (String.isPrefix "" "abc") ^ "\n");
val () = print ("@@isprefix_full=" ^ Bool.toString (String.isPrefix "abc" "abc") ^ "\n");
val () = print ("@@issuffix_empty=" ^ Bool.toString (String.isSuffix "" "abc") ^ "\n");
val () = print ("@@issuffix_longer=" ^ Bool.toString (String.isSuffix "xabc" "abc") ^ "\n");
val () = print ("@@compare_prefix=" ^ (case String.compare ("abc","abcd") of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@compare_eq=" ^ (case String.compare ("abc","abc") of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@compare_empty_lhs=" ^ (case String.compare ("","a") of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@collate_prefix=" ^ (case String.collate Char.compare ("abc","abcd") of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@extract_none=[" ^ String.extract ("abcdef", 2, NONE) ^ "]\n");
val () = print ("@@extract_some=[" ^ String.extract ("abcdef", 2, SOME 3) ^ "]\n");
val () = print ("@@extract_atend=[" ^ String.extract ("abcdef", 6, NONE) ^ "]\n");
val () = print ("@@extract_zero=[" ^ String.extract ("abcdef", 3, SOME 0) ^ "]\n");
val () = print ("@@extract_bad=" ^ ((String.extract ("abc", 5, NONE)) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@substring_mid=[" ^ String.substring ("abcdef", 1, 3) ^ "]\n");
val () = print ("@@substring_zero=[" ^ String.substring ("abcdef", 2, 0) ^ "]\n");
val () = print ("@@substring_bad=" ^ ((String.substring ("abc", 2, 5)) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@implode_empty=[" ^ String.implode [] ^ "]\n");
val () = print ("@@explode_empty=" ^ Int.toString (List.length (String.explode "")) ^ "\n");
val () = print ("@@explode_roundtrip=[" ^ String.implode (String.explode "rt!") ^ "]\n");
