(* diff-corpus category: substring (deep sweep 2026-06-09) *)

val () = print ("@@full_size=" ^ Int.toString (Substring.size (Substring.full "hello")) ^ "\n");
val () = print ("@@full_empty_size=" ^ Int.toString (Substring.size (Substring.full "")) ^ "\n");
val () = print ("@@extract_mid=" ^ Substring.string (Substring.extract ("hello world", 6, SOME 5)) ^ "\n");
val () = print ("@@extract_to_end=" ^ Substring.string (Substring.extract ("hello world", 6, NONE)) ^ "\n");
val () = print ("@@extract_zero_len=[" ^ Substring.string (Substring.extract ("abcdef", 3, SOME 0)) ^ "]\n");
val () = print ("@@extract_whole=" ^ Substring.string (Substring.extract ("abcdef", 0, NONE)) ^ "\n");
val () = print ("@@extract_end_index=[" ^ Substring.string (Substring.extract ("abc", 3, SOME 0)) ^ "]\n");
val () = print ("@@extract_bad=" ^ ((Substring.string (Substring.extract ("abc", 4, NONE))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@extract_bad_len=" ^ ((Substring.string (Substring.extract ("abc", 1, SOME 5))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@substring3=" ^ Substring.string (Substring.substring ("abcdefgh", 2, 3)) ^ "\n");
val () = print ("@@substring_empty=[" ^ Substring.string (Substring.substring ("abc", 0, 0)) ^ "]\n");
val () = print ("@@base=" ^ (let val (s,i,n) = Substring.base (Substring.extract ("hello world", 6, SOME 5)) in s ^ "/" ^ Int.toString i ^ "/" ^ Int.toString n end) ^ "\n");
val () = print ("@@getc_first=" ^ (case Substring.getc (Substring.full "xyz") of SOME (c, _) => String.str c | NONE => "NONE") ^ "\n");
val () = print ("@@getc_empty=" ^ (case Substring.getc (Substring.full "") of SOME _ => "SOME" | NONE => "NONE") ^ "\n");
val () = print ("@@first_char=" ^ (case Substring.first (Substring.full "Q") of SOME c => String.str c | NONE => "NONE") ^ "\n");
val () = print ("@@first_empty=" ^ (case Substring.first (Substring.full "") of SOME c => String.str c | NONE => "NONE") ^ "\n");
val () = print ("@@triml2=" ^ Substring.string (Substring.triml 2 (Substring.full "abcdef")) ^ "\n");
val () = print ("@@triml_over=[" ^ Substring.string (Substring.triml 10 (Substring.full "abc")) ^ "]\n");
val () = print ("@@trimr2=" ^ Substring.string (Substring.trimr 2 (Substring.full "abcdef")) ^ "\n");
val () = print ("@@trimr_over=[" ^ Substring.string (Substring.trimr 10 (Substring.full "abc")) ^ "]\n");
val () = print ("@@slice=" ^ Substring.string (Substring.slice (Substring.full "abcdefgh", 2, SOME 3)) ^ "\n");
val () = print ("@@slice_none=" ^ Substring.string (Substring.slice (Substring.full "abcdefgh", 5, NONE)) ^ "\n");
val () = print ("@@slice_bad=" ^ ((Substring.string (Substring.slice (Substring.full "abc", 1, SOME 5))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@splitl=" ^ (let val (a,b) = Substring.splitl (fn c => c <> #" ") (Substring.full "foo bar baz") in Substring.string a ^ "|" ^ Substring.string b end) ^ "\n");
val () = print ("@@splitl_nomatch=" ^ (let val (a,b) = Substring.splitl (fn _ => true) (Substring.full "abc") in "[" ^ Substring.string a ^ "][" ^ Substring.string b ^ "]" end) ^ "\n");
val () = print ("@@splitr=" ^ (let val (a,b) = Substring.splitr (fn c => c <> #".") (Substring.full "a.b.c") in Substring.string a ^ "|" ^ Substring.string b end) ^ "\n");
val () = print ("@@dropl=" ^ Substring.string (Substring.dropl Char.isSpace (Substring.full "   trimmed")) ^ "\n");
val () = print ("@@dropr=" ^ Substring.string (Substring.dropr Char.isSpace (Substring.full "trimmed   ")) ^ "\n");
val () = print ("@@takel=" ^ Substring.string (Substring.takel Char.isAlpha (Substring.full "abc123")) ^ "\n");
val () = print ("@@taker=" ^ Substring.string (Substring.taker Char.isDigit (Substring.full "abc123")) ^ "\n");
val () = print ("@@position=" ^ (let val (a,b) = Substring.position "bc" (Substring.full "aabcbc") in Substring.string a ^ "|" ^ Substring.string b end) ^ "\n");
val () = print ("@@position_nomatch=" ^ (let val (a,b) = Substring.position "zz" (Substring.full "abc") in "[" ^ Substring.string a ^ "][" ^ Substring.string b ^ "]" end) ^ "\n");
val () = print ("@@position_empty=" ^ (let val (a,b) = Substring.position "" (Substring.full "abc") in "[" ^ Substring.string a ^ "][" ^ Substring.string b ^ "]" end) ^ "\n");
val () = print ("@@tokens=" ^ String.concatWith "," (map Substring.string (Substring.tokens Char.isSpace (Substring.full "  a  bb   ccc "))) ^ "\n");
val () = print ("@@tokens_count=" ^ Int.toString (length (Substring.tokens (fn c => c = #",") (Substring.full ",,a,,b,,"))) ^ "\n");
val () = print ("@@fields=" ^ String.concatWith "|" (map Substring.string (Substring.fields (fn c => c = #",") (Substring.full "a,,b,"))) ^ "\n");
val () = print ("@@fields_count=" ^ Int.toString (length (Substring.fields (fn c => c = #",") (Substring.full ",,,"))) ^ "\n");
val () = print ("@@concat=" ^ Substring.concat [Substring.full "ab", Substring.extract ("xcdz", 1, SOME 2), Substring.full "ef"] ^ "\n");
val () = print ("@@concat_empty=[" ^ Substring.concat [] ^ "]\n");
val () = print ("@@foldl=" ^ Substring.foldl (fn (c, acc) => acc ^ String.str c) "" (Substring.extract ("xyhelloz", 2, SOME 5)) ^ "\n");
val () = print ("@@foldr=" ^ Substring.foldr (fn (c, acc) => acc ^ String.str c) "" (Substring.full "abc") ^ "\n");
val () = print ("@@app=" ^ (let val r = ref "" in Substring.app (fn c => r := !r ^ String.str c) (Substring.full "QRS"); !r end) ^ "\n");
val () = print ("@@isPrefix_t=" ^ Bool.toString (Substring.isPrefix "ab" (Substring.full "abcdef")) ^ "\n");
val () = print ("@@isPrefix_f=" ^ Bool.toString (Substring.isPrefix "bc" (Substring.full "abcdef")) ^ "\n");
val () = print ("@@isPrefix_empty=" ^ Bool.toString (Substring.isPrefix "" (Substring.full "abc")) ^ "\n");
val () = print ("@@isSuffix_t=" ^ Bool.toString (Substring.isSuffix "ef" (Substring.full "abcdef")) ^ "\n");
val () = print ("@@isSuffix_f=" ^ Bool.toString (Substring.isSuffix "de" (Substring.full "abcdef")) ^ "\n");
val () = print ("@@compare_eq=" ^ (case Substring.compare (Substring.full "abc", Substring.full "abc") of EQUAL => "EQUAL" | LESS => "LESS" | GREATER => "GREATER") ^ "\n");
val () = print ("@@compare_lt=" ^ (case Substring.compare (Substring.full "abc", Substring.full "abd") of EQUAL => "EQUAL" | LESS => "LESS" | GREATER => "GREATER") ^ "\n");
val () = print ("@@compare_prefix=" ^ (case Substring.compare (Substring.full "ab", Substring.full "abc") of EQUAL => "EQUAL" | LESS => "LESS" | GREATER => "GREATER") ^ "\n");
val () = print ("@@collate=" ^ (case Substring.collate Char.compare (Substring.full "abc", Substring.full "abc") of EQUAL => "EQUAL" | LESS => "LESS" | GREATER => "GREATER") ^ "\n");
val () = print ("@@translate=" ^ Substring.translate (fn c => String.str c ^ "-") (Substring.full "abc") ^ "\n");
val () = print ("@@string_slice=" ^ Substring.string (Substring.slice (Substring.extract ("0123456789", 2, SOME 6), 1, SOME 3)) ^ "\n");
val () = print ("@@size_after_triml=" ^ Int.toString (Substring.size (Substring.triml 3 (Substring.full "abcdefg"))) ^ "\n");
