(* diff-corpus category: vectors (deep sweep 2026-06-09) *)

val () = print ("@@fromList_len=" ^ Int.toString (Vector.length (Vector.fromList [10,20,30,40])) ^ "\n");
val () = print ("@@empty_len=" ^ Int.toString (Vector.length (Vector.fromList ([]:int list))) ^ "\n");
val () = print ("@@single_sub=" ^ Int.toString (Vector.sub (Vector.fromList [99], 0)) ^ "\n");
val () = print ("@@tab_sum=" ^ Int.toString (Vector.foldl (op +) 0 (Vector.tabulate (5, fn i => i * i))) ^ "\n");
val () = print ("@@tab_empty=" ^ Int.toString (Vector.length (Vector.tabulate (0, fn i => i))) ^ "\n");
val () = print ("@@sub_oob=" ^ ((Int.toString (Vector.sub (Vector.fromList [1,2,3], 3))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@sub_neg=" ^ ((Int.toString (Vector.sub (Vector.fromList [1,2,3], ~1))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@update_val=" ^ Int.toString (Vector.sub (Vector.update (Vector.fromList [1,2,3,4], 2, 77), 2)) ^ "\n");
val () = print ("@@update_orig=" ^ (let val v = Vector.fromList [1,2,3,4] val _ = Vector.update (v, 0, 555) in Int.toString (Vector.sub (v, 0)) end) ^ "\n");
val () = print ("@@update_oob=" ^ ((Int.toString (Vector.length (Vector.update (Vector.fromList [1,2], 5, 0)))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@map_sum=" ^ Int.toString (Vector.foldl (op +) 0 (Vector.map (fn x => x * 2) (Vector.fromList [1,2,3,4]))) ^ "\n");
val () = print ("@@mapi_sum=" ^ Int.toString (Vector.foldl (op +) 0 (Vector.mapi (fn (i,x) => i + x) (Vector.fromList [10,20,30]))) ^ "\n");
val () = print ("@@foldl_str=" ^ Vector.foldl (fn (x,acc) => acc ^ Int.toString x) "" (Vector.fromList [1,2,3]) ^ "\n");
val () = print ("@@foldr_str=" ^ Vector.foldr (fn (x,acc) => acc ^ Int.toString x) "" (Vector.fromList [1,2,3]) ^ "\n");
val () = print ("@@foldli_sum=" ^ Int.toString (Vector.foldli (fn (i,x,acc) => acc + i*x) 0 (Vector.fromList [5,6,7])) ^ "\n");
val () = print ("@@foldri_str=" ^ Vector.foldri (fn (i,x,acc) => acc ^ Int.toString i ^ Int.toString x) "" (Vector.fromList [4,5]) ^ "\n");
val () = print ("@@find_some=" ^ (case Vector.find (fn x => x > 2) (Vector.fromList [1,2,3,4]) of SOME y => Int.toString y | NONE => "NONE") ^ "\n");
val () = print ("@@find_none=" ^ (case Vector.find (fn x => x > 99) (Vector.fromList [1,2,3]) of SOME y => Int.toString y | NONE => "NONE") ^ "\n");
val () = print ("@@findi_some=" ^ (case Vector.findi (fn (i,x) => x = 30) (Vector.fromList [10,20,30,40]) of SOME (i,y) => Int.toString i ^ ":" ^ Int.toString y | NONE => "NONE") ^ "\n");
val () = print ("@@exists_t=" ^ Bool.toString (Vector.exists (fn x => x = 0) (Vector.fromList [3,0,5])) ^ "\n");
val () = print ("@@exists_empty=" ^ Bool.toString (Vector.exists (fn x => true) (Vector.fromList ([]:int list))) ^ "\n");
val () = print ("@@all_t=" ^ Bool.toString (Vector.all (fn x => x > 0) (Vector.fromList [1,2,3])) ^ "\n");
val () = print ("@@all_empty=" ^ Bool.toString (Vector.all (fn x => false) (Vector.fromList ([]:int list))) ^ "\n");
val () = print ("@@collate_lt=" ^ (case Vector.collate Int.compare (Vector.fromList [1,2], Vector.fromList [1,3]) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@collate_prefix=" ^ (case Vector.collate Int.compare (Vector.fromList [1,2], Vector.fromList [1,2,3]) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@collate_eq=" ^ (case Vector.collate Int.compare (Vector.fromList [7,8], Vector.fromList [7,8]) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@concat_sum=" ^ Int.toString (Vector.foldl (op +) 0 (Vector.concat [Vector.fromList [1,2], Vector.fromList [], Vector.fromList [3,4,5]])) ^ "\n");
val () = print ("@@concat_empty=" ^ Int.toString (Vector.length (Vector.concat ([]:int vector list))) ^ "\n");
val () = print ("@@vs_full_len=" ^ Int.toString (VectorSlice.length (VectorSlice.full (Vector.fromList [1,2,3,4]))) ^ "\n");
val () = print ("@@vs_slice_sub=" ^ Int.toString (VectorSlice.sub (VectorSlice.slice (Vector.fromList [10,20,30,40,50], 1, SOME 3), 0)) ^ "\n");
val () = print ("@@vs_slice_oob=" ^ ((Int.toString (VectorSlice.sub (VectorSlice.slice (Vector.fromList [1,2,3,4,5], 1, SOME 3), 3))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@vs_subslice_sum=" ^ Int.toString (VectorSlice.foldl (op +) 0 (VectorSlice.subslice (VectorSlice.full (Vector.fromList [1,2,3,4,5,6]), 1, SOME 3))) ^ "\n");
val () = print ("@@vs_slice_nolen=" ^ Int.toString (VectorSlice.length (VectorSlice.slice (Vector.fromList [1,2,3,4,5], 2, NONE))) ^ "\n");
val () = print ("@@vs_slice_bad=" ^ ((Int.toString (VectorSlice.length (VectorSlice.slice (Vector.fromList [1,2,3], 1, SOME 5)))) handle Subscript => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@vs_getitem=" ^ (case VectorSlice.getItem (VectorSlice.slice (Vector.fromList [9,8,7], 1, SOME 2)) of SOME (x, rest) => Int.toString x ^ ":" ^ Int.toString (VectorSlice.length rest) | NONE => "NONE") ^ "\n");
val () = print ("@@vs_getitem_empty=" ^ (case VectorSlice.getItem (VectorSlice.slice (Vector.fromList [1,2,3], 0, SOME 0)) of SOME _ => "SOME" | NONE => "NONE") ^ "\n");
val () = print ("@@vs_map_sum=" ^ Int.toString (Vector.foldl (op +) 0 (VectorSlice.map (fn x => x + 1) (VectorSlice.slice (Vector.fromList [1,2,3,4], 1, SOME 2)))) ^ "\n");
val () = print ("@@vs_concat_sum=" ^ Int.toString (Vector.foldl (op +) 0 (VectorSlice.concat [VectorSlice.slice (Vector.fromList [1,2,3], 0, SOME 2), VectorSlice.full (Vector.fromList [10,20])])) ^ "\n");
val () = print ("@@vs_isempty_t=" ^ Bool.toString (VectorSlice.isEmpty (VectorSlice.slice (Vector.fromList [1,2,3], 1, SOME 0))) ^ "\n");
val () = print ("@@vs_isempty_f=" ^ Bool.toString (VectorSlice.isEmpty (VectorSlice.full (Vector.fromList [1]))) ^ "\n");
val () = print ("@@vs_base=" ^ (let val (v, i, n) = VectorSlice.base (VectorSlice.slice (Vector.fromList [1,2,3,4,5], 2, SOME 2)) in Int.toString (Vector.length v) ^ ":" ^ Int.toString i ^ ":" ^ Int.toString n end) ^ "\n");
val () = print ("@@vs_foldr_str=" ^ VectorSlice.foldr (fn (x,acc) => acc ^ Int.toString x) "" (VectorSlice.slice (Vector.fromList [1,2,3,4], 0, SOME 3)) ^ "\n");
val () = print ("@@vs_findi=" ^ (case VectorSlice.findi (fn (i,x) => x = 40) (VectorSlice.slice (Vector.fromList [10,20,30,40,50], 1, SOME 3)) of SOME (i,y) => Int.toString i ^ ":" ^ Int.toString y | NONE => "NONE") ^ "\n");
val () = print ("@@charvec_sub=" ^ Char.toString (Vector.sub (Vector.fromList [#"a", #"b", #"c"], 1)) ^ "\n");
