(* diff-corpus category: word8 (deep sweep 2026-06-09) *)

val () = print ("@@fromInt_255=" ^ Word8.toString (Word8.fromInt 255) ^ "\n");
val () = print ("@@fromInt_256_wrap=" ^ Word8.toString (Word8.fromInt 256) ^ "\n");
val () = print ("@@fromInt_257_wrap=" ^ Word8.toString (Word8.fromInt 257) ^ "\n");
val () = print ("@@fromInt_neg1_wrap=" ^ Word8.toString (Word8.fromInt ~1) ^ "\n");
val () = print ("@@fromInt_neg256_wrap=" ^ Word8.toString (Word8.fromInt ~256) ^ "\n");
val () = print ("@@fromInt_1000_wrap=" ^ Word8.toString (Word8.fromInt 1000) ^ "\n");
val () = print ("@@toInt_FF=" ^ Int.toString (Word8.toInt (Word8.fromInt 255)) ^ "\n");
val () = print ("@@toIntX_FF=" ^ Int.toString (Word8.toIntX (Word8.fromInt 255)) ^ "\n");
val () = print ("@@toIntX_80=" ^ Int.toString (Word8.toIntX (Word8.fromInt 128)) ^ "\n");
val () = print ("@@toIntX_7F=" ^ Int.toString (Word8.toIntX (Word8.fromInt 127)) ^ "\n");
val () = print ("@@toIntX_00=" ^ Int.toString (Word8.toIntX (Word8.fromInt 0)) ^ "\n");
val () = print ("@@toIntX_81=" ^ Int.toString (Word8.toIntX (Word8.fromInt 129)) ^ "\n");
val () = print ("@@andb=" ^ Word8.toString (Word8.andb (Word8.fromInt 0xF0, Word8.fromInt 0x3C)) ^ "\n");
val () = print ("@@orb=" ^ Word8.toString (Word8.orb (Word8.fromInt 0xF0, Word8.fromInt 0x0F)) ^ "\n");
val () = print ("@@xorb=" ^ Word8.toString (Word8.xorb (Word8.fromInt 0xFF, Word8.fromInt 0x0F)) ^ "\n");
val () = print ("@@notb_00=" ^ Word8.toString (Word8.notb (Word8.fromInt 0)) ^ "\n");
val () = print ("@@notb_FF=" ^ Word8.toString (Word8.notb (Word8.fromInt 255)) ^ "\n");
val () = print ("@@notb_AA=" ^ Word8.toString (Word8.notb (Word8.fromInt 0xAA)) ^ "\n");
val () = print ("@@shl_1_by7=" ^ Word8.toString (Word8.<< (Word8.fromInt 1, 0w7)) ^ "\n");
val () = print ("@@shl_1_by8_wrap=" ^ Word8.toString (Word8.<< (Word8.fromInt 1, 0w8)) ^ "\n");
val () = print ("@@shl_FF_by4=" ^ Word8.toString (Word8.<< (Word8.fromInt 0xFF, 0w4)) ^ "\n");
val () = print ("@@shl_FF_by100=" ^ Word8.toString (Word8.<< (Word8.fromInt 0xFF, 0w100)) ^ "\n");
val () = print ("@@shr_80_by7=" ^ Word8.toString (Word8.>> (Word8.fromInt 0x80, 0w7)) ^ "\n");
val () = print ("@@shr_FF_by8_zero=" ^ Word8.toString (Word8.>> (Word8.fromInt 0xFF, 0w8)) ^ "\n");
val () = print ("@@ashr_80_by1=" ^ Word8.toString (Word8.~>> (Word8.fromInt 0x80, 0w1)) ^ "\n");
val () = print ("@@ashr_80_by7=" ^ Word8.toString (Word8.~>> (Word8.fromInt 0x80, 0w7)) ^ "\n");
val () = print ("@@ashr_FF_by8=" ^ Word8.toString (Word8.~>> (Word8.fromInt 0xFF, 0w8)) ^ "\n");
val () = print ("@@ashr_7F_by1=" ^ Word8.toString (Word8.~>> (Word8.fromInt 0x7F, 0w1)) ^ "\n");
val () = print ("@@add_wrap=" ^ Word8.toString (Word8.+ (Word8.fromInt 200, Word8.fromInt 100)) ^ "\n");
val () = print ("@@add_FF_1=" ^ Word8.toString (Word8.+ (Word8.fromInt 255, Word8.fromInt 1)) ^ "\n");
val () = print ("@@sub_wrap=" ^ Word8.toString (Word8.- (Word8.fromInt 0, Word8.fromInt 1)) ^ "\n");
val () = print ("@@sub_5_10=" ^ Word8.toString (Word8.- (Word8.fromInt 5, Word8.fromInt 10)) ^ "\n");
val () = print ("@@mul_wrap=" ^ Word8.toString (Word8.* (Word8.fromInt 16, Word8.fromInt 16)) ^ "\n");
val () = print ("@@mul_FF_FF=" ^ Word8.toString (Word8.* (Word8.fromInt 255, Word8.fromInt 255)) ^ "\n");
val () = print ("@@div=" ^ Word8.toString (Word8.div (Word8.fromInt 255, Word8.fromInt 16)) ^ "\n");
val () = print ("@@mod=" ^ Word8.toString (Word8.mod (Word8.fromInt 255, Word8.fromInt 16)) ^ "\n");
val () = print ("@@div_by_zero=" ^ ((Word8.toString (Word8.div (Word8.fromInt 5, Word8.fromInt 0))) handle Div => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@mod_by_zero=" ^ ((Word8.toString (Word8.mod (Word8.fromInt 5, Word8.fromInt 0))) handle Div => "CAUGHT" | _ => "OTHER") ^ "\n");
val () = print ("@@cmp_lt=" ^ (case Word8.compare (Word8.fromInt 1, Word8.fromInt 2) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@cmp_eq=" ^ (case Word8.compare (Word8.fromInt 128, Word8.fromInt 128) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@cmp_gt_unsigned=" ^ (case Word8.compare (Word8.fromInt 255, Word8.fromInt 1) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@cmp_80_7F_unsigned=" ^ (case Word8.compare (Word8.fromInt 128, Word8.fromInt 127) of LESS => "LESS" | EQUAL => "EQUAL" | GREATER => "GREATER") ^ "\n");
val () = print ("@@lt_op=" ^ Bool.toString (Word8.< (Word8.fromInt 127, Word8.fromInt 128)) ^ "\n");
val () = print ("@@gt_op=" ^ Bool.toString (Word8.> (Word8.fromInt 255, Word8.fromInt 0)) ^ "\n");
val () = print ("@@toLarge_FF=" ^ LargeWord.toString (Word8.toLarge (Word8.fromInt 255)) ^ "\n");
val () = print ("@@toLargeX_80=" ^ LargeWord.toString (Word8.toLargeX (Word8.fromInt 0x80)) ^ "\n");
val () = print ("@@fromLarge_wrap=" ^ Word8.toString (Word8.fromLarge (LargeWord.fromInt 0x1FF)) ^ "\n");
val () = print ("@@fromLarge_300=" ^ Word8.toString (Word8.fromLarge (LargeWord.fromInt 300)) ^ "\n");
val () = print ("@@minmax_max=" ^ Word8.toString (Word8.max (Word8.fromInt 10, Word8.fromInt 200)) ^ "\n");
val () = print ("@@minmax_min=" ^ Word8.toString (Word8.min (Word8.fromInt 10, Word8.fromInt 200)) ^ "\n");
val () = print ("@@wordSize=" ^ Int.toString Word8.wordSize ^ "\n");
val () = print ("@@fromString_FF=" ^ (case Word8.fromString "FF" of SOME w => Word8.toString w | NONE => "NONE") ^ "\n");
val () = print ("@@fromString_garbage=" ^ (case Word8.fromString "zz" of SOME w => Word8.toString w | NONE => "NONE") ^ "\n");
