(* diff-corpus category: word_convert (deep sweep 2026-06-09) *)

val () = print ("@@wordSize=" ^ Int.toString Word.wordSize ^ "\n");
val () = print ("@@fromInt0=" ^ Word.toString (Word.fromInt 0) ^ "\n");
val () = print ("@@fromInt255=" ^ Word.toString (Word.fromInt 255) ^ "\n");
val () = print ("@@roundtrip_42=" ^ Int.toString (Word.toInt (Word.fromInt 42)) ^ "\n");
val () = print ("@@toIntX_neg1=" ^ Int.toString (Word.toIntX (Word.fromInt ~1)) ^ "\n");
val () = print ("@@toIntX_neg255=" ^ Int.toString (Word.toIntX (Word.fromInt ~255)) ^ "\n");
val () = print ("@@toInt_neg1_caught=" ^ ((Int.toString (Word.toInt (Word.fromInt ~1))) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@toIntX_maxint=" ^ Int.toString (Word.toIntX (Word.fromInt (valOf Int.maxInt))) ^ "\n");
val () = print ("@@toInt_maxint=" ^ Int.toString (Word.toInt (Word.fromInt (valOf Int.maxInt))) ^ "\n");
val () = print ("@@toIntX_minint=" ^ Int.toString (Word.toIntX (Word.fromInt (valOf Int.minInt))) ^ "\n");
val () = print ("@@toInt_minint_caught=" ^ ((Int.toString (Word.toInt (Word.fromInt (valOf Int.minInt)))) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@fromLargeInt_neg1_toIntX=" ^ Int.toString (Word.toIntX (Word.fromLargeInt ~1)) ^ "\n");
val () = print ("@@fromLargeInt_big_toString=" ^ Word.toString (Word.fromLargeInt 1000000000000) ^ "\n");
val () = print ("@@toLargeInt_42=" ^ LargeInt.toString (Word.toLargeInt (Word.fromInt 42)) ^ "\n");
val () = print ("@@toLargeIntX_neg1=" ^ LargeInt.toString (Word.toLargeIntX (Word.fromInt ~1)) ^ "\n");
val () = print ("@@toLargeInt_neg1_nonneg=" ^ LargeInt.toString (Word.toLargeInt (Word.fromInt ~1)) ^ "\n");
val () = print ("@@toLargeIntX_minint=" ^ LargeInt.toString (Word.toLargeIntX (Word.fromInt (valOf Int.minInt))) ^ "\n");
val () = print ("@@int_toLarge_42=" ^ LargeInt.toString (Int.toLarge 42) ^ "\n");
val () = print ("@@int_toLarge_negmax=" ^ LargeInt.toString (Int.toLarge (valOf Int.minInt)) ^ "\n");
val () = print ("@@int_fromLarge_rt=" ^ Int.toString (Int.fromLarge (Int.toLarge 123456789)) ^ "\n");
val () = print ("@@int_fromLarge_overflow=" ^ ((Int.toString (Int.fromLarge 9223372036854775807)) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@largeint_toInt_fit=" ^ Int.toString (LargeInt.toInt 4611686018427387903) ^ "\n");
val () = print ("@@largeint_toInt_overflow=" ^ ((Int.toString (LargeInt.toInt 4611686018427387904)) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@largeint_toInt_neg_overflow=" ^ ((Int.toString (LargeInt.toInt ~4611686018427387905)) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@intinf_toInt_fit=" ^ Int.toString (IntInf.toInt 100) ^ "\n");
val () = print ("@@intinf_toInt_overflow=" ^ ((Int.toString (IntInf.toInt (IntInf.pow (2, 70)))) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@intinf_toInt_neg_overflow=" ^ ((Int.toString (IntInf.toInt (~ (IntInf.pow (2, 70))))) handle Overflow => "Overflow" | _ => "OTHER") ^ "\n");
val () = print ("@@word_fromLarge_rt=" ^ LargeWord.toString (Word.toLarge (Word.fromInt 65535)) ^ "\n");
val () = print ("@@word_fromLarge_back=" ^ Word.toString (Word.fromLarge (Word.toLarge (Word.fromInt 65535))) ^ "\n");
val () = print ("@@word_toLargeX_neg1=" ^ LargeWord.toString (Word.toLargeX (Word.fromInt ~1)) ^ "\n");
val () = print ("@@largeword_wordSize=" ^ Int.toString LargeWord.wordSize ^ "\n");
val () = print ("@@word_fromLarge_truncate=" ^ Word.toString (Word.fromLarge (LargeWord.fromInt 257)) ^ "\n");
val () = print ("@@fromInt_negmax_toIntX=" ^ Int.toString (Word.toIntX (Word.fromInt ~4611686018427387903)) ^ "\n");
val () = print ("@@word_notZero_toIntX=" ^ Int.toString (Word.toIntX (Word.notb (Word.fromInt 0))) ^ "\n");
val () = print ("@@word_orb_signbit_toIntX=" ^ Int.toString (Word.toIntX (Word.<< (Word.fromInt 1, 0w62))) ^ "\n");
val () = print ("@@largeint_toLarge_id=" ^ LargeInt.toString (Int.toLarge (Int.fromLarge 999)) ^ "\n");
val () = print ("@@word8_fromInt_neg1_toIntX=" ^ Int.toString (Word8.toIntX (Word8.fromInt ~1)) ^ "\n");
val () = print ("@@word8_fromInt_neg1_toInt=" ^ Int.toString (Word8.toInt (Word8.fromInt ~1)) ^ "\n");
val () = print ("@@word8_fromInt_256=" ^ Word8.toString (Word8.fromInt 256) ^ "\n");
