(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_128=" ^ (wrap (fn () => Bool.toString (((String.size ((String.map Char.toUpper (Word.toString (0w378))) ^ (if ((~4) >= (~3)) then (Bool.toString false) else (let val v1 = false in "bi" end)))) <> (Int.abs (if ((Int.quot ((~5), 0)) <= (4 + (~8))) then ((#2 ((~8), 10)) + (~ (~1))) else (case ((false = true)) of true => (Int.min (7, (~5))) | false => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (7) mod 30) 0 end)))))))) ^ "\n");
