(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_105=" ^ (wrap (fn () => Bool.toString ((List.all (fn x => x < 100) (case (List.rev (let val v1 = (let val v2 = (5, (~5)) in [] end) in (List.filter (fn x => x mod 2 = 0) v1) end)) of [] => [] | _ :: t => t))))) ^ "\n");
