(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_140=" ^ (wrap (fn () => Int.toString (((case (List.filter (fn x => x mod 2 = 0) (List.tabulate (Int.abs ((case (true) of true => 0 | false => (~3))) mod 12, fn i => (Int.rem ((~10), i))))) of [] => 0 | x :: _ => x) - (Word.toIntX ((Word.max (((let val v1 = 6 in 0wxFFFF end) + (0w1 + 0wx7FFFFFFF)), ((Word.xorb (0wx100, 0wxFFFF)) * ((Word.fromInt 8) div 0wxFFFF)))))))))) ^ "\n");
