(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_129=" ^ (wrap (fn () => il2s ((if ((if ((Int.abs 5) < (Int.quot (7, 7))) then (Int.max ((Int.quot (2, (~2))), (Int.rem ((~1), 7)))) else ((Int.max (0, 1)) - (Word.toIntX (0wxFFFF)))) < (case (List.filter (fn x => x mod 2 = 0) (List.map (fn x => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~5)) mod 30) 0 end)) [1])) of [] => 0 | x :: _ => x)) then (List.rev (List.rev (List.map (fn x => (~ x)) (List.map (fn x => (x - x)) [(~8)])))) else (List.map (fn x => ((Int.min ((if true then 3 else (~4)), (Int.min ((~5), x)))) * (List.foldl (fn (a,b) => a + b) 0 (List.rev [(~9), (~6), (~7)])))) (List.tabulate (Int.abs ((let val v1 = ((~2), 0) in ((~5) mod 1) end)) mod 12, fn i => (Int.rem ((Word.toInt (0w828)), (i * (~2))))))))))) ^ "\n");
