(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_139=" ^ (wrap (fn () => Bool.toString ((let val v1 = (let val v2 = (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (((Word.toIntX (0w1)) + (case (((~10)) mod 5) of 0 => 1 | 1 => (~9) | 2 => (~3) | _ => 5))) mod 30) 0 end) in (let val p = (let val v3 = (let val p = ((~9), 8) in (#2 p, #1 p) end) in (v2, v2) end) in (#2 p, #1 p) end) end) in (Word.<= ((Word.min (((if false then 0w1 else 0w1) mod (Word.>> ((Word.fromInt (~4)), 0w64))), (Word.>> ((Word.notb (0wx100)), 0w19)))), (Word.fromInt ((IntInf.toInt (((IntInf.quot ((IntInf.pow (10, 15)), (1 : IntInf.int)))) mod 1000)))))) end)))) ^ "\n");
