(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_123=" ^ (wrap (fn () => Word.toString ((Word.min ((case (((~ (Int.abs (8 + (~7))))) mod 5) of 0 => (((if false then 0wx7FFFFFFF else 0w255) - (Word.andb ((Word.fromInt (~8)), 0w0))) - ((Word.~>> (0w1, 0w37)) - (Word.fromInt ((~2))))) | 1 => (Word.fromInt ((let val v1 = (Word.andb (0w0, 0w510)) in (List.foldl (fn (a,b) => a + b) 0 [6, 1, (~1), 3]) end))) | 2 => ((Word.<< ((Word.<< (0w182, 0w41)), 0w30)) mod (let val v2 = ((~9) < 3) in (Word.max ((Word.fromInt (~2)), 0w255)) end)) | _ => (Word.min (((Word.max (0w314, (Word.fromInt 6))) + (Word.orb (0wxFFFF, 0wx7FFFFFFF))), ((Word.orb (0w1, 0w255)) div (let val v3 = 2 in 0wxFFFF end))))), ((let val v4 = (Word.andb ((0wx7FFFFFFF - 0w1), (Word.notb (0w255)))) in (Word.min ((let val v5 = [1, 10, 5] in (Word.fromInt (~9)) end), (Word.xorb (0w255, v4)))) end) div ((Word.<< ((if false then 0w0 else 0wx7FFFFFFF), 0w15)) - (Word.notb ((Word.notb (0w0))))))))))) ^ "\n");
