(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_130=" ^ (wrap (fn () => il2s (((let val v1 = ((List.foldl (fn (a,b) => a + b) 0 (List.filter (fn x => x mod 2 = 0) [3, (~2), (~6), 6])) <> (Word.toIntX ((Word.>> (0wxFFFF, 0w44))))) in (#2 ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~3)) mod 30) 0 end), (Int.max (9, (~2))))) end) :: (let val v2 = (IntInf.abs ((IntInf.pow ((((462 : IntInf.int) : IntInf.int) - (31342 * 1000000007 : IntInf.int)), (Int.abs ((Int.max ((~10), (~9)))) mod 8))))) in (case ((List.rev [2, 7]) @ (7 :: [(~10), (~9)])) of [] => [] | _ :: t => t) end))))) ^ "\n");
