(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_147=" ^ (wrap (fn () => Word.toString ((Word.fromInt ((IntInf.sign ((IntInf.abs ((if ("" = "qqr") then (IntInf.abs ((IntInf.pow (2, 75)))) else (case (((~3)) mod 5) of 0 => (IntInf.pow (10, 11)) | 1 => (IntInf.pow (2, 40)) | 2 => (~57 : IntInf.int) | _ => (0 : IntInf.int)))))))))))) ^ "\n");
