(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_111=" ^ (wrap (fn () => Word.toString ((((Word.>> (((0w830 div 0w0) mod (let val v1 = ((~4), (~3)) in 0w255 end)), 0w51)) div (Word.orb ((Word.>> ((Word.~>> (0wxFFFF, 0w20)), 0w37)), (Word.max ((0w670 div (Word.fromInt 3)), (Word.orb (0wx100, 0w1))))))) div (let val v2 = (((0w0 - 0w1) - (Word.min (0w1, 0wx7FFFFFFF))) div ((Word.>> (0w255, 0w56)) * (if true then (Word.fromInt 4) else 0w255))) in (((Word.~>> (v2, 0w47)) - (Word.max (0wx7FFFFFFF, v2))) - (case (((8 * 7)) mod 5) of 0 => (Word.min (v2, v2)) | 1 => (Word.notb (0wx7FFFFFFF)) | 2 => (Word.orb (v2, v2)) | _ => (v2 * 0w0))) end))))) ^ "\n");
