(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_113=" ^ (wrap (fn () => Int.toString (((~ ((#1 (if true then (9, (~10)) else ((~6), 2))) - (#2 (let val v1 = true in (3, 9) end)))) - (Int.max (((case ((Word.< ((Word.fromInt 10), 0w134))) of true => (Int.quot ((~9), 3)) | false => (Int.rem ((~7), 8))) * (~ (#1 (6, 10)))), (IntInf.toInt (((IntInf.fromInt ((case (true) of true => (~5) | false => 8)))) mod 1000)))))))) ^ "\n");
