(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_117=" ^ (wrap (fn () => IntInf.toString ((IntInf.pow ((IntInf.min ((if ((Word.toInt (0wx100)) <> (#2 (6, 1))) then (((~ ((88321 * 1000000007 : IntInf.int) : IntInf.int)) : IntInf.int) + (((IntInf.pow (10, 26)) : IntInf.int) + (490 : IntInf.int))) else (let val v1 = ("u298" ^ "575 ") in (IntInf.max ((IntInf.pow (10, 25)), (404 : IntInf.int))) end)), (((let val v2 = (if false then (10, (~2)) else ((~1), 8)) in (((1 : IntInf.int) : IntInf.int) mod (IntInf.pow (2, 94))) end) : IntInf.int) div (IntInf.abs ((((0 : IntInf.int) : IntInf.int) * (~479 : IntInf.int))))))), (Int.abs ((#2 (if ((IntInf.sign ((~ (IntInf.pow (2, 62))))) >= (IntInf.toInt (((IntInf.pow (2, 47))) mod 1000))) then ((Word.toInt (0wxFFFF)), (case (true) of true => (~6) | false => 1)) else (if (List.null [(~1), 5, (~3), 8]) then (if false then (1, 6) else (0, (~7))) else (let val v3 = (10, 4) in (6, 9) end))))) mod 8)))))) ^ "\n");
