(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_122=" ^ (wrap (fn () => IntInf.toString ((IntInf.min ((~ ((IntInf.min ((((IntInf.quot ((~ (IntInf.pow (2, 49))), (91043 * 1000000007 : IntInf.int))) : IntInf.int) div (((IntInf.pow (2, 83)) : IntInf.int) div (0 : IntInf.int))), (IntInf.quot ((IntInf.rem ((89507 * 1000000007 : IntInf.int), (57997 * 1000000007 : IntInf.int))), (IntInf.quot ((IntInf.pow (2, 65)), (IntInf.pow (10, 11)))))))) : IntInf.int)), (let val v1 = ((case ((((Word.fromInt (~3)) : word) = 0w840)) of true => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (1) mod 30) 0 end) | false => (Word.toIntX (0wx100))), (case (((~ 3)) mod 5) of 0 => (case [] of [] => 0 | x :: _ => x) | 1 => (5 - 2) | 2 => (~ 9) | _ => (~ (~4)))) in (~ ((((IntInf.pow ((1 : IntInf.int), (Int.abs (6) mod 8))) : IntInf.int) div (((95321 * 1000000007 : IntInf.int) : IntInf.int) * (~ (IntInf.pow (2, 43))))) : IntInf.int)) end)))))) ^ "\n");
