(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_135=" ^ (wrap (fn () => Bool.toString (((IntInf.toString ((((IntInf.min ((case ((4) mod 5) of 0 => (~278 : IntInf.int) | 1 => (~ (IntInf.pow (2, 71))) | 2 => (0 : IntInf.int) | _ => (~ (IntInf.pow (2, 55)))), (((0 : IntInf.int) : IntInf.int) - (99 : IntInf.int)))) : IntInf.int) - (let val v1 = (String.concatWith "-" (List.map Int.toString [0, 6, (~10)])) in (((~ (IntInf.pow (2, 45))) : IntInf.int) * (~ (IntInf.pow (2, 51)))) end)))) = (Bool.toString ((not (((~ (IntInf.pow (2, 98))) : IntInf.int) <= (1 : IntInf.int))) orelse ((Word.toInt (0wxFFFF)) > (case [] of [] => 0 | x :: _ => x)))))))) ^ "\n");
