(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_149=" ^ (wrap (fn () => pr2s (((IntInf.toInt (((IntInf.abs ((((IntInf.quot ((~104 : IntInf.int), (IntInf.pow (10, 20)))) : IntInf.int) mod (IntInf.max ((~27 : IntInf.int), (~ (IntInf.pow (2, 87))))))))) mod 1000)), (IntInf.toInt (((((if ((~7) <= 3) then (((0 : IntInf.int) : IntInf.int) + (1 : IntInf.int)) else (IntInf.abs ((IntInf.pow (10, 13))))) : IntInf.int) - (if (List.all (fn x => x < 100) [5, (~10), 8]) then (IntInf.abs ((IntInf.pow (10, 26)))) else (IntInf.min ((1 : IntInf.int), (IntInf.pow (2, 96))))))) mod 1000)))))) ^ "\n");
