(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_152=" ^ (wrap (fn () => ((let val v1 = ((Int.abs (let val v2 = (Int.rem (8, 6)) in (Int.max ((~1), 8)) end)) * (Int.abs ((Int.abs 5) mod ((~6) mod 3)))) in (Bool.toString (if (((0wx100 mod 0w475) : word) = (0w980 + 0wx100)) then ((Int.rem (v1, v1)) = (v1 * 8)) else ((List.null []) = (List.all (fn x => x < 100) [(~4)])))) end)))) ^ "\n");
