(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_150=" ^ (wrap (fn () => Word.toString (((((Word.xorb ((if true then (Word.fromInt (~5)) else 0w255), (Word.~>> (0w255, 0w16)))) mod ((Word.max (0wx7FFFFFFF, 0wx7FFFFFFF)) * (Word.max (0w1, 0w1)))) * ((let val v1 = (List.filter (fn x => x mod 2 = 0) [(~2), 4]) in (Word.fromInt (1)) end) div (Word.andb ((Word.fromInt (0)), (0w0 * (Word.fromInt (~6))))))) + (Word.min ((Word.>> ((Word.xorb (((Word.fromInt 10) + 0wxFFFF), (Word.~>> (0wx100, 0w0)))), 0w58)), ((Word.notb ((0wx7FFFFFFF * 0wxFFFF))) div (Word.orb ((Word.andb (0w1, 0wx100)), (let val v2 = true in 0w255 end)))))))))) ^ "\n");
