(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_10=" ^ (wrap (fn () => il2s ((case (List.filter (fn x => x mod 2 = 0) (List.filter (fn x => x mod 2 = 0) (List.tabulate (Int.abs ((10 * (~9))) mod 12, fn i => (List.foldl (fn (a,b) => a + b) 0 []))))) of [] => [] | _ :: t => t)))) ^ "\n");
