(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_120=" ^ (wrap (fn () => Int.toString ((#1 (if (case (((((163 : IntInf.int) : IntInf.int) = (IntInf.pow (2, 78))) = (let val v1 = 0w1 in false end))) of true => ((Word.toInt (0wx7FFFFFFF)) >= (Int.rem ((~8), (~7)))) | false => (if (((1 : IntInf.int) : IntInf.int) = (~ (IntInf.pow (2, 79)))) then (3 = 6) else (((95268 * 1000000007 : IntInf.int) : IntInf.int) <= (IntInf.pow (2, 89))))) then (let val p = (if ((0w0 : word) = 0wx7FFFFFFF) then (8, 9) else (2, 7)) in (#2 p, #1 p) end) else (let val v2 = ((2 + (~4)) :: (List.rev [])) in (let val p = (let val v3 = v2 in ((~2), (~3)) end) in (#2 p, #1 p) end) end)))))) ^ "\n");
