(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_131=" ^ (wrap (fn () => ((String.substring ((IntInf.toString ((IntInf.rem ((((IntInf.max ((~ (IntInf.pow (2, 50))), (96843 * 1000000007 : IntInf.int))) : IntInf.int) + (IntInf.pow ((IntInf.pow (10, 20)), (Int.abs (2) mod 8)))), (((IntInf.max ((IntInf.pow (2, 76)), (~ (IntInf.pow (2, 75))))) : IntInf.int) * (((~ (IntInf.pow (2, 87))) : IntInf.int) div (~ (IntInf.pow (2, 71))))))))), 0, 1))))) ^ "\n");
