(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_127=" ^ (wrap (fn () => Word.toString ((Word.<< ((case (((#1 ((~ 10), (#1 (4, 6))))) mod 5) of 0 => (((0w0 - 0wx100) - (Word.min (0w1, 0wx7FFFFFFF))) mod (if ("2zyx " = "") then (Word.orb ((Word.fromInt (~8)), 0wx7FFFFFFF)) else (0wx100 - 0wx100))) | 1 => (Word.orb ((Word.min ((if true then 0wx100 else 0w760), (Word.andb (0w1, (Word.fromInt 6))))), (Word.min ((Word.notb (0wxFFFF)), (Word.orb (0w0, 0w1)))))) | 2 => (Word.~>> ((Word.<< ((Word.orb ((Word.fromInt 0), 0w775)), 0w45)), 0w59)) | _ => (Word.fromInt ((~ ((~3) mod 9))))), 0w62))))) ^ "\n");
