(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_101=" ^ (wrap (fn () => ((String.map Char.toUpper (Bool.toString (case (((let val v1 = "bd" in true end) orelse (true andalso false))) of true => ((Int.min (3, (~4))) <= (List.foldl (fn (a,b) => a + b) 0 [7])) | false => (((((12720 * 1000000007 : IntInf.int) : IntInf.int) * (IntInf.pow (2, 59))) : IntInf.int) = (((1 : IntInf.int) : IntInf.int) - (IntInf.pow (10, 26)))))))))) ^ "\n");
