(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_115=" ^ (wrap (fn () => ((Word.toString (((Word.max ((Word.min ((let val v1 = [] in (Word.fromInt 6) end), (Word.notb (0w255)))), ((0wx7FFFFFFF - 0wx100) mod (0w1 * 0w0)))) * (if (List.null (List.map (fn x => (Word.toInt (0wxFFFF))) [(~4), (~10), 8])) then (Word.andb ((Word.<< (0wx100, 0w20)), (Word.min (0wx7FFFFFFF, 0w0)))) else (Word.fromInt ((if true then 1 else 5)))))))))) ^ "\n");
