(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_119=" ^ (wrap (fn () => pr2s ((let val p = ((Int.rem ((#1 (let val v1 = [] in ((~4), (~8)) end)), (IntInf.sign ((if true then (378 : IntInf.int) else (~5 : IntInf.int)))))), (Int.max ((case (((case (((~6)) mod 5) of 0 => 7 | 1 => (~8) | 2 => (~4) | _ => 6)) mod 5) of 0 => (Word.toInt (0w1)) | 1 => (Int.abs (~1)) | 2 => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (0) mod 30) 0 end) | _ => (~ (~9))), (~ (IntInf.sign ((~201 : IntInf.int))))))) in (#2 p, #1 p) end)))) ^ "\n");
