(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_109=" ^ (wrap (fn () => ((String.concatWith "-" (List.map Int.toString (List.filter (fn x => x mod 2 = 0) (if (((((IntInf.pow (2, 55)) : IntInf.int) * (0 : IntInf.int)) : IntInf.int) < (IntInf.pow ((1 : IntInf.int), (Int.abs ((~2)) mod 8)))) then (List.rev (case [(~1), (~9), (~6)] of [] => [] | _ :: t => t)) else (let val v1 = (if true then (9, (~8)) else (3, 5)) in (List.tabulate (Int.abs ((~8)) mod 12, fn i => (i + i))) end)))))))) ^ "\n");
