(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_100=" ^ (wrap (fn () => il2s (((List.filter (fn x => x mod 2 = 0) (List.rev (List.filter (fn x => x mod 2 = 0) (List.map (fn x => (x - 2)) [4, 7, 2, (~9)])))) @ (List.rev (List.tabulate (Int.abs ((let val v1 = (let val v2 = (1, (~5)) in true end) in (9 mod 8) end)) mod 12, fn i => (let val v3 = (String.size "y7") in (~ (~5)) end)))))))) ^ "\n");
