(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_125=" ^ (wrap (fn () => Bool.toString ((not ((let val v1 = (Bool.toString (List.exists (fn x => x > 0) [])) in (Int.abs (IntInf.sign ((~ (IntInf.pow (2, 86)))))) end) >= (~ (case (((case (true) of true => 10 | false => 3)) mod 5) of 0 => (List.foldl (fn (a,b) => a + b) 0 [2, (~2), (~10)]) | 1 => ((~4) * (~2)) | 2 => (Int.rem (2, (~4))) | _ => (case (true) of true => 1 | false => (~2))))))))) ^ "\n");
