(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_110=" ^ (wrap (fn () => Int.toString (((Int.abs (Word.toInt ((Word.fromInt ((Int.rem ((~4), (~1)))))))) div (Int.abs ((List.foldl (fn (a,b) => a + b) 0 (List.map (fn x => (let val v1 = (~4) in 2 end)) [(~1), (~9), 6, (~3)])) - (IntInf.sign ((IntInf.pow ((0 : IntInf.int), (Int.abs (0) mod 8))))))))))) ^ "\n");
