(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_11=" ^ (wrap (fn () => Word.toString ((Word.fromInt ((Word.toIntX ((Word.<< ((Word.min ((0w255 - 0wx7FFFFFFF), (Word.~>> (0wx100, 0w65)))), 0w25))))))))) ^ "\n");
