(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_0=" ^ (wrap (fn () => Int.toString ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((Int.abs (let val v1 = (String.substring ((String.substring ("0wx", 0, 1)), 0, 1)) in ((if false then 10 else 7) mod (1 * 6)) end))) mod 30) 0 end)))) ^ "\n");
