(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_103=" ^ (wrap (fn () => Bool.toString (((((IntInf.fromInt ((Int.abs (~ 5)))) : IntInf.int) = (((IntInf.max ((~ ((IntInf.pow (10, 21)) : IntInf.int)), (((93533 * 1000000007 : IntInf.int) : IntInf.int) - (204 : IntInf.int)))) : IntInf.int) * (((if true then (90606 * 1000000007 : IntInf.int) else (IntInf.pow (10, 27))) : IntInf.int) + (IntInf.abs ((17150 * 1000000007 : IntInf.int)))))) andalso (((#1 (let val p = (0, 8) in (#2 p, #1 p) end)) - (IntInf.toInt (((IntInf.quot ((1 : IntInf.int), (IntInf.pow (2, 85))))) mod 1000))) >= (Int.min ((Int.min ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~8)) mod 30) 0 end), (Word.toIntX (0w349)))), (~ (case (true) of true => (~6) | false => (~5)))))))))) ^ "\n");
