(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_106=" ^ (wrap (fn () => Bool.toString (((#1 (let val p = (let val p = (if false then (4, 7) else ((~9), 0)) in (#2 p, #1 p) end) in (#2 p, #1 p) end)) < (String.size (let val v1 = (case (((9 div 3)) mod 5) of 0 => (List.null [9, 9, 8, 7]) | 1 => (if true then true else true) | 2 => (false = true) | _ => (List.null [0, (~7), (~6), (~10)])) in (Int.toString (Int.abs (~2))) end)))))) ^ "\n");
