(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_151=" ^ (wrap (fn () => pr2s ((if (List.null (case ((case (((~4)) mod 5) of 0 => (~1) | 1 => 4 | 2 => 4 | _ => (~3)) :: (List.map (fn x => (IntInf.sign ((~ (IntInf.pow (2, 87)))))) [3, 0, 2, 10])) of [] => [] | _ :: t => t)) then (let val p = (if ((case ((6) mod 5) of 0 => false | 1 => false | 2 => true | _ => true) andalso (if false then true else true)) then (let val p = (let val p = ((~6), (~4)) in (#2 p, #1 p) end) in (#2 p, #1 p) end) else (let val v1 = (let val v2 = 0w151 in "xq6" end) in (let val p = ((~1), (~9)) in (#2 p, #1 p) end) end)) in (#2 p, #1 p) end) else (let val v3 = (((0w121 * 0w255) div (case ((7) mod 5) of 0 => 0wxFFFF | 1 => 0wx100 | 2 => 0wx100 | _ => 0w0)) mod ((Word.notb (0w255)) mod (0wx100 div 0wx7FFFFFFF))) in (let val p = (let val v4 = (List.rev [8, 10]) in (let val p = ((~8), (~5)) in (#2 p, #1 p) end) end) in (#2 p, #1 p) end) end))))) ^ "\n");
