(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_146=" ^ (wrap (fn () => Int.toString (((~ (Word.toInt ((Word.orb ((0wxFFFF div 0wx7FFFFFFF), (Word.xorb (0wx7FFFFFFF, 0w0))))))) mod (List.length (List.tabulate (Int.abs ((IntInf.toInt (((case ((2) mod 5) of 0 => (~ (IntInf.pow (2, 67))) | 1 => (1 : IntInf.int) | 2 => (1 : IntInf.int) | _ => (0 : IntInf.int))) mod 1000))) mod 12, fn i => ((Int.min (i, (~9))) * (Int.abs i))))))))) ^ "\n");
