(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_102=" ^ (wrap (fn () => Bool.toString (((let val v1 = ((let val v2 = (let val p = ((~5), 1) in (#2 p, #1 p) end) in (let val v3 = (~5) in [10] end) end) @ ((Int.max ((~7), 4)) :: (6 :: [5, 7, (~8), 2]))) in (Int.rem ((List.foldl (fn (a,b) => a + b) 0 (let val v4 = (IntInf.pow (2, 42)) in [(~6)] end)), ((case [] of [] => 0 | x :: _ => x) * (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~1)) mod 30) 0 end)))) end) < (Word.toIntX ((Word.orb ((Word.<< ((Word.orb (0wx7FFFFFFF, 0w1)), 0w15)), (Word.min ((0w255 mod 0wx100), (0w137 + (Word.fromInt (~8))))))))))))) ^ "\n");
