(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_126=" ^ (wrap (fn () => Int.toString ((List.foldl (fn (a,b) => a + b) 0 (if ((List.length (List.tabulate (Int.abs (7) mod 12, fn i => (Int.min (i, i))))) < ((0 * 2) div (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~4)) mod 30) 0 end))) then (List.filter (fn x => x mod 2 = 0) (if (((~374 : IntInf.int) : IntInf.int) <= (0 : IntInf.int)) then (List.rev [10]) else ([(~6), (~9)] @ [(~10), (~1), 5]))) else (if ((Int.abs (~5)) <> (let val v1 = [7, 4] in 9 end)) then (List.rev (List.filter (fn x => x mod 2 = 0) [])) else (List.tabulate (Int.abs ((Int.max (6, 1))) mod 12, fn i => (List.foldl (fn (a,b) => a + b) 0 [1, (~5)]))))))))) ^ "\n");
