(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_141=" ^ (wrap (fn () => Word.toString ((Word.andb ((Word.min ((Word.~>> ((Word.~>> ((0wx7FFFFFFF mod 0wx7FFFFFFF), 0w65)), 0w6)), (Word.xorb ((if (false = false) then (Word.xorb (0w255, 0w1)) else (0w0 div 0wxFFFF)), (Word.notb ((Word.fromInt (6)))))))), (Word.notb ((let val v1 = (case (((List.foldl (fn (a,b) => a + b) 0 [3, 10, (~2)])) mod 5) of 0 => (~ ((IntInf.pow (10, 13)) : IntInf.int)) | 1 => (IntInf.fromInt ((~10))) | 2 => (((~448 : IntInf.int) : IntInf.int) div (IntInf.pow (10, 13))) | _ => (((~ (IntInf.pow (2, 59))) : IntInf.int) + (~467 : IntInf.int))) in (Word.notb ((0wx100 * 0w1))) end)))))))) ^ "\n");
