(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_14=" ^ (wrap (fn () => Word.toString ((Word.min ((((case (((let val v1 = (Word.fromInt 7) in (~6) end)) mod 5) of 0 => (Word.min (0w1, 0w990)) | 1 => (0wxFFFF - 0wxFFFF) | 2 => (0wx100 * 0wx100) | _ => (0w626 mod 0wx7FFFFFFF)) * (Word.>> ((Word.<< (0w0, 0w27)), 0w12))) + ((let val v2 = ([(~6), 6] @ []) in (Word.max (0w255, 0wx7FFFFFFF)) end) - ((0w1 + 0wxFFFF) + (Word.notb (0wxFFFF))))), ((if (List.exists (fn x => x > 0) (List.filter (fn x => x mod 2 = 0) [1])) then (Word.min ((let val v3 = "b5a" in 0w780 end), (Word.notb (0wxFFFF)))) else ((0w0 mod 0wx7FFFFFFF) + (case ((10) mod 5) of 0 => 0wxFFFF | 1 => 0w255 | 2 => 0w553 | _ => 0wx100))) - (Word.<< (((0w0 - 0w255) + (Word.orb (0w256, 0w541))), 0w19)))))))) ^ "\n");
