(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_13=" ^ (wrap (fn () => il2s ((case (List.rev (List.map (fn x => (case (((case (true) of true => 4 | false => 7)) mod 5) of 0 => (3 div x) | 1 => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end) | 2 => (Int.max (3, x)) | _ => (case ((1) mod 5) of 0 => x | 1 => (~3) | 2 => 3 | _ => (~7)))) ((case [6, 1] of [] => 0 | x :: _ => x) :: (if false then [7, (~4), 8, 0] else [0, 3, 0, (~8)])))) of [] => [] | _ :: t => t)))) ^ "\n");
