(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_121=" ^ (wrap (fn () => IntInf.toString ((((((let val v1 = (IntInf.rem ((((0 : IntInf.int) : IntInf.int) div (IntInf.pow (2, 83))), (((IntInf.pow (2, 99)) : IntInf.int) + (IntInf.pow (10, 19))))) in (IntInf.abs ((IntInf.rem (v1, v1)))) end) : IntInf.int) + (IntInf.abs ((IntInf.abs ((IntInf.abs ((438 : IntInf.int)))))))) : IntInf.int) - (IntInf.fromInt ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((Int.rem ((case [] of [] => 0 | x :: _ => x), (#1 (8, (~5)))))) mod 30) 0 end))))))) ^ "\n");
