(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_145=" ^ (wrap (fn () => il2s (((List.map (fn x => (case ((((let val v1 = "p" in (IntInf.pow (2, 67)) end) : IntInf.int) <= (((IntInf.pow (10, 23)) : IntInf.int) * (IntInf.pow (2, 98))))) of true => (Word.toInt ((Word.notb (0wx100)))) | false => (List.foldl (fn (a,b) => a + b) 0 (if true then [(~1), (~2), 0] else [7])))) ((List.tabulate (Int.abs ((Word.toIntX (0w255))) mod 12, fn i => (if true then (~6) else (~7)))) @ (List.filter (fn x => x mod 2 = 0) (List.tabulate (Int.abs ((~8)) mod 12, fn i => (Int.abs i)))))) @ (((Word.toIntX ((Word.fromInt (8)))) * (IntInf.toInt (((((80228 * 1000000007 : IntInf.int) : IntInf.int) mod (0 : IntInf.int))) mod 1000))) :: ((List.filter (fn x => x mod 2 = 0) (let val v2 = "zzq9 " in [9, (~5), (~2)] end)) @ (let val v3 = (((179 : IntInf.int) : IntInf.int) < (1 : IntInf.int)) in ((~4) :: [(~5), (~9), (~5)]) end))))))) ^ "\n");
