(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_112=" ^ (wrap (fn () => Word.toString (((Word.fromInt ((Int.quot ((List.length (List.filter (fn x => x mod 2 = 0) [1, 1, 4])), (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((if false then (~3) else 10)) mod 30) 0 end))))) * (((Word.orb ((Word.min (0w255, 0wx100)), (Word.<< (0w0, 0w52)))) mod ((0wx100 * 0w255) - (Word.notb (0wx7FFFFFFF)))) + (Word.~>> ((Word.fromInt ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (9) mod 30) 0 end))), 0w0))))))) ^ "\n");
