(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_148=" ^ (wrap (fn () => pr2s ((if (List.all (fn x => x < 100) (List.filter (fn x => x mod 2 = 0) (List.map (fn x => (Int.abs 10)) ((~8) :: [])))) then ((Int.abs (IntInf.toInt (((IntInf.quot ((18100 * 1000000007 : IntInf.int), (~ (IntInf.pow (2, 88)))))) mod 1000))), (~ (IntInf.sign ((let val v1 = (3, (~5)) in (22234 * 1000000007 : IntInf.int) end))))) else (let val p = (let val v2 = (List.map (fn x => (Int.min ((~7), (~4)))) ((~6) :: [(~8)])) in (if (Word.<= (0w0, 0wxFFFF)) then (let val v3 = (~ (IntInf.pow (2, 71))) in (5, 1) end) else (let val p = ((~2), (~1)) in (#2 p, #1 p) end)) end) in (#2 p, #1 p) end))))) ^ "\n");
