(* generated by tools/diff-corpus-gen/genprog_arith.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_arith_137=" ^ (wrap (fn () => Bool.toString ((Word.<= ((((Word.xorb ((0w0 + 0w95), (Word.andb (0wx7FFFFFFF, (Word.fromInt 5))))) * (case (((5 div (~7))) mod 5) of 0 => (Word.>> ((Word.fromInt 4), 0w20)) | 1 => (0w355 div 0w1) | 2 => (0w1 - 0w444) | _ => ((Word.fromInt 7) div 0wx100))) * ((Word.<< ((0w255 mod 0w0), 0w2)) - (if (10 < (~9)) then (let val v1 = "zffa" in 0wxFFFF end) else (0wx7FFFFFFF mod (Word.fromInt 0))))), (Word.~>> (((Word.max ((0w0 - 0w0), (Word.notb (0wx7FFFFFFF)))) - (let val v2 = (10, 8) in (Word.<< (0w255, 0w33)) end)), 0w34))))))) ^ "\n");
