(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_109=" ^ (wrap (fn () => pr2s ((if (List.all (fn x => (List.null (#1 (let val xs = [7, (~2), (~10)] val k = Int.abs ((~7)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)))) (List.map (fn x => (List.last (List.concat [[], [1, 9, (~4), 5, (~8)]]))) (List.concat [(if false then [] else [(~7), (~10), 8, (~2), (~8)]), (List.mapPartial (fn x => if (x = (~8)) then SOME ((case [6] of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) else NONE) [(~1), 4, (~10), 4, 6])]))) then (let val xs = (List.map (fn x => (Int.abs (List.last [0, (~10), 10, 6, (~10)]))) (List.mapPartial (fn x => if (List.null [(~8), 8, 8]) then SOME ((#2 (8, 7))) else NONE) (List.drop ([5, (~4), 1, 1, 8], Int.abs ((~9)) mod 7)))) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) else ((String.size (if (let val v1 = ([2], [3]) in true end) then (Bool.toString true) else ("ln" ^ ""))), (Int.min ((#2 (8, 7)), ((let val v2 = 7 in v2 end) * (2 * 7))))))))) ^ "\n");
