(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_100=" ^ (wrap (fn () => Int.toString ((case (List.rev (List.map (fn x => ((Int.min (x, x)) + (let val v1 = 8 in x end))) (List.foldr (fn (x, v2) => (List.mapPartial (fn x => if (List.null [1, 10, 4]) then SOME ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (9) mod 30) 0 end)) else NONE) v2)) [] (List.take ([], Int.abs (10) mod 7))))) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)))) ^ "\n");
