(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_108=" ^ (wrap (fn () => Int.toString (((getOpt (List.find (fn x => ((String.substring ((Bool.toString true), 0, 1)) = (String.concat (List.map (fn x => (String.concat (List.map (fn x => (String.concatWith "-" (List.map Int.toString []))) []))) (List.foldr (fn (x, v1) => (List.filter (fn x => (3 = (~4))) v1)) [] [(~4), 1, 8, (~5), (~5)]))))) (((Int.abs (~2)) div (List.last [(~4), (~2), 0])) :: (List.foldr (fn (x, v2) => (List.tabulate (Int.abs (9) mod 12, (fn i => (#2 (4, 3)))))) [] (List.concat [[(~4), 10, (~2), 6], []]))), 0)) * (Int.min ((let val v3 = (#2 (if false then (3, (~2)) else ((~6), 6))) in (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((List.foldl (fn (x, v4) => (List.last [(~10), 2, (~2)])) v3 [(~2), 1, (~4), (~9)])) mod 30) 0 end) end), (Int.min ((List.length (#2 ([], []))), (Int.abs (Int.max ((~10), (~9)))))))))))) ^ "\n");
