(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_114=" ^ (wrap (fn () => il2s ((List.filter (fn x => ((Int.max (((x - 1) * (List.foldr (fn (x, v1) => (List.last [0, (~10), (~2), 0, 9])) x [])), (#2 (let val p = ((~10), (~5)) in (#2 p, #1 p) end)))) < (hd (List.drop ((List.take ([3, (~10)], Int.abs (x) mod 7)), Int.abs ((List.nth ([7, 10, 5, 10, 7], Int.abs ((~4)) mod 7))) mod 7))))) ((String.size (String.substring (("bg" ^ "bpw"), 0, 1))) :: ((case ([(~10)], [2, (~1), (~7), 9, 9]) of (xs, ys) => List.length xs - List.length ys) :: (let val v2 = (List.mapPartial (fn x => if ((~4) < x) then SOME ((#1 (8, 8))) else NONE) [9, 10, 7, (~2)]) in (List.map (fn x => (String.size "")) v2) end))))))) ^ "\n");
