(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_117=" ^ (wrap (fn () => Int.toString ((List.foldr (fn (x, v1) => (let val v2 = (String.substring ((if (true orelse false) then (String.map Char.toUpper "6p2g") else (let val v3 = ([7, 6, 5], [0, (~10)]) in "p" end)), 0, 1)) in (Int.max (((String.size "gr") div (10 div (~10))), (#1 (let val xs = [(~1), (~7)] in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end)))) end)) (((hd (List.tabulate (Int.abs ((~2)) mod 12, (fn i => (i * 3))))) + (if (false orelse false) then (let val v4 = (0, (~8)) in (~8) end) else (String.size "jih"))) - (Int.max ((Int.max ((List.last [8, (~2)]), (hd [2, (~2), (~6)]))), (List.length (case [] of [] => [] | (a :: rest) => rest @ [a]))))) (#1 (ListPair.unzip (ListPair.zip ((#2 (let val (p, q) = (List.partition (fn x => (x = 0)) [(~8)]) in (q, p) end)), (List.take ((case ([(~10), (~9)] @ [9, (~5)]) of [] => [] | (a :: rest) => rest @ [a]), Int.abs ((hd (List.filter (fn x => (let val v5 = [(~5), (~7)] in true end)) [0, 2, 4]))) mod 7)))))))))) ^ "\n");
