(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_144=" ^ (wrap (fn () => il2s ((List.concat [(List.tabulate (Int.abs ((List.last (case (#1 (ListPair.unzip (ListPair.zip ([2, (~10), 6, (~4), 5], [4])))) of [] => [] | (a :: rest) => rest @ [a]))) mod 12, (fn i => (String.size (Bool.toString (true andalso false)))))), (List.rev (List.drop ((#1 (ListPair.unzip (ListPair.zip ((case [] of [] => [] | (a :: rest) => rest @ [a]), (List.drop ([], Int.abs ((~4)) mod 7)))))), Int.abs (((List.length []) - (Int.abs (~6)))) mod 7)))])))) ^ "\n");
