(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_115=" ^ (wrap (fn () => il2s ((#2 (List.partition (fn x => ((List.foldl (fn (x, v1) => (List.foldl (fn (x, v2) => (case [9, 8, 0, 4] of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) x [2, 10, 3])) (List.length [(~4), 8, (~8)]) (#1 (ListPair.unzip (ListPair.zip ([(~3), 3, (~3)], []))))) > (#1 (let val (a, b) = ((~2), (~3)) in (b, a) end)))) (#2 (List.partition (fn x => ((~8) < (~6))) (List.filter (fn x => (5 = (~3))) [4, (~6)])))))))) ^ "\n");
