(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_145=" ^ (wrap (fn () => Bool.toString ((List.null (#1 (ListPair.unzip (ListPair.zip ((case (List.foldr (fn (x, v1) => (List.foldr (fn (x, v2) => (case v2 of [] => [] | (a :: rest) => rest @ [a])) [] [(~2), (~3), (~7), 8])) [] (let val v3 = (~2) in [8, 7, (~3)] end)) of [] => [] | (a :: rest) => rest @ [a]), (List.map (fn x => (getOpt (List.find (fn x => (x = 2)) (#1 (ListPair.unzip (ListPair.zip ([5, 3, (~8), (~8)], [])))), 0))) (case (List.take ([(~1), 10], Int.abs (5) mod 7)) of [] => [] | (a :: rest) => rest @ [a])))))))))) ^ "\n");
