(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_124=" ^ (wrap (fn () => il2s ((List.concat [((hd (#1 (ListPair.unzip (ListPair.zip ((#1 (ListPair.unzip (ListPair.zip ([2, (~6), 9], [(~2), (~8)])))), (let val v1 = ([7], [(~1), (~4)]) in [(~5), (~9)] end)))))) :: (List.foldr (fn (x, v2) => (List.drop ((List.concat [[], v2]), Int.abs ((case [7] of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) mod 7))) [] (List.drop ((List.drop ([0, (~9), 2, 1, (~4)], Int.abs (5) mod 7)), Int.abs ((List.foldr (fn (x, v3) => (List.foldr (fn (x, v4) => (if true then v4 else (~9))) v3 [1, (~10)])) (~1) [8, (~7), 8, 8])) mod 7)))), (List.filter (fn x => ((not (if true then false else false)) andalso (if (7 < x) then ((~5) > x) else (List.exists (fn x => (x < 5)) [6, (~2), (~5), 7, (~3)])))) (let val v5 = (let val xs = ((~5) :: [1, 1, 3]) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) in (#1 (let val v6 = (~8) in ([(~8), (~1), (~1)], [(~7)]) end)) end))])))) ^ "\n");
