(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_110=" ^ (wrap (fn () => pr2s ((let val (a, b) = (let val (a, b) = (if ((List.foldr (fn (x, v1) => (List.foldl (fn (x, v2) => (10 div v2)) 6 [7, 10, 7, (~4)])) 8 [(~9), (~3)]) <= (let val v3 = (~10) in (~4) end)) then (let val xs = ([(~3), 6] @ [9, 8, 5]) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) else (let val xs = (List.mapPartial (fn x => if (List.exists (fn x => (x < x)) [(~10), 2, 6]) then SOME ((x div (~8))) else NONE) [5, 7, 1, 7, (~2)]) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end)) in (b, a) end) in (b, a) end)))) ^ "\n");
