(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_127=" ^ (wrap (fn () => pl2s ((let val xs = (List.tabulate (Int.abs ((List.length (case (List.concat [[(~3), (~4)], [(~6), (~8), 2, 3, 0]]) of [] => [] | (a :: rest) => rest @ [a]))) mod 12, (fn i => ((List.foldr (fn (x, v1) => (~ x)) (hd [(~9), (~6), (~5), 6]) (List.concat [[(~7)], [(~4), 0, (~6), (~4)]])) + (case (let val xs = [2, 2, 6] val k = Int.abs ((~2)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end) of (xs, ys) => List.length xs - List.length ys))))) val k = Int.abs ((List.nth ((case (List.concat [((~9) :: [(~5), 6, 2, 10, (~6)]), ([] @ [7, (~10), 1, 6, (~2)])]) of [] => [] | (a :: rest) => rest @ [a]), Int.abs ((case (List.rev (List.drop ([(~10), 3, 0], Int.abs ((~5)) mod 7))) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) mod 7))) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)))) ^ "\n");
