(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_10=" ^ (wrap (fn () => pr2s ((let val xs = (if ((let val v1 = (true orelse true) in (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (6) mod 30) 0 end) end) > (Int.max ((List.foldr (fn (x, v2) => (Int.abs (~4))) (~6) [(~6), 0]), (List.last [(~10)])))) then (List.concat [(let val v3 = (let val v4 = (1, (~7)) in v4 end) in (List.rev [(~10), 6, 6]) end), ((Int.min ((~4), 9)) :: (case [(~9), 2, 6] of [] => [] | (a :: rest) => rest @ [a]))]) else ((List.foldr (fn (x, v5) => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end)) (case ([3, (~6), (~4)], [6, 5, (~5)]) of (xs, ys) => List.length xs - List.length ys) (List.map (fn x => (x + x)) [3, 1, (~4), 0, 9])) :: ((if false then [4] else []) @ (if true then [8, (~2)] else [2, 6, (~2)])))) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end)))) ^ "\n");
