(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_133=" ^ (wrap (fn () => il2s ((List.rev (if (let val v1 = (let val v2 = (getOpt (List.find (fn x => (false andalso true)) [(~4), (~9), 8], 0)) in (ListPair.unzip (ListPair.zip ([10, (~7)], []))) end) in (List.all (fn x => (not true)) (List.rev [7])) end) then (#1 (ListPair.unzip (ListPair.zip ((List.take ([4, (~6), 3, 7], Int.abs (8) mod 7)), (#2 ([6, (~3), (~6)], [(~3), 0])))))) else (List.concat [(case (List.tabulate (Int.abs (7) mod 12, (fn i => (i mod i)))) of [] => [] | (a :: rest) => rest @ [a]), (#2 (List.partition (fn x => (not false)) [4, 1, (~1), (~8), 8]))])))))) ^ "\n");
