(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_140=" ^ (wrap (fn () => pl2s ((let val (p, q) = ((if ((if false then "" else "") = (let val v1 = true in "blm" end)) then ((getOpt (List.find (fn x => (let val v2 = ([(~2), (~5)], [9]) in true end)) [5, 8, 0], 0)) :: (if false then [] else [10, 10, 4])) else (#2 ([4], [(~7), 6, 5, (~6)]))), (List.rev (case ([(~5)] @ [(~3), 4, 10]) of [] => [] | (a :: rest) => rest @ [a]))) in (q, p) end)))) ^ "\n");
