(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_151=" ^ (wrap (fn () => ((let val v1 = (Bool.toString (if (((~6) :: [7]) = (List.filter (fn x => (true orelse true)) [9, (~9), (~3), (~1), 7])) then (List.all (fn x => (1 < x)) (#1 ([], [(~7), 3, (~2)]))) else (if (true orelse false) then (5 = 1) else (if false then false else false)))) in ((String.concatWith "-" (List.map Int.toString (List.concat [(let val v2 = (~7) in [5, (~6), 3, 0] end), (case [(~4)] of [] => [] | (a :: rest) => rest @ [a])]))) ^ (String.map Char.toUpper ((Int.toString 0) ^ (if false then v1 else v1)))) end)))) ^ "\n");
