(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_126=" ^ (wrap (fn () => Bool.toString (((String.substring ((let val v1 = (List.partition (fn x => (true andalso true)) (List.filter (fn x => (List.null [(~3), 3])) [])) in (let val v2 = (let val xs = [(~2), (~2), (~3), (~10), 4] val k = Int.abs (10) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end) in (String.substring ("u7", 0, 1)) end) end), 0, 1)) = (Bool.toString ((String.size (String.substring ("", 0, 1))) < (#2 ((~3), (~3))))))))) ^ "\n");
