(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_14=" ^ (wrap (fn () => il2s ((List.rev (#1 (((case ([(~2), 10, 8, (~2), 2], [1, 4, (~7), 0]) of (xs, ys) => List.length xs - List.length ys) :: (List.take ([8], Int.abs ((~3)) mod 7))), (List.filter (fn x => (10 > 3)) (if true then [1, (~8)] else [5, (~5), 2, (~2)])))))))) ^ "\n");
