(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_111=" ^ (wrap (fn () => Bool.toString (((#2 (((#1 (3, (~8))) :: (List.foldr (fn (x, v1) => (List.concat [[10, 4, 4, (~3)], [9]])) [] [(~6), 4, 9])), (List.take ((List.concat [[8], [(~2), (~6), (~8), 1]]), Int.abs ((#1 (8, 5))) mod 7)))) = ((getOpt (List.find (fn x => (not (isSome (List.find (fn x => (true andalso true)) [])))) (List.mapPartial (fn x => if (x > 9) then SOME ((x - x)) else NONE) (List.tabulate (Int.abs ((~1)) mod 12, (fn i => (Int.max (i, i)))))), 0)) :: ((String.size (String.concatWith "-" (List.map Int.toString [(~9), 10, (~10)]))) :: (List.take ((List.mapPartial (fn x => if ((~5) < x) then SOME ((#1 ((~10), 5))) else NONE) [(~8), 4, 3, 1, 8]), Int.abs ((getOpt (List.find (fn x => (List.null [5, (~8), 0, (~8)])) [1, (~4), 10, 4], 0))) mod 7)))))))) ^ "\n");
