(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_137=" ^ (wrap (fn () => il2s ((List.foldr (fn (x, v1) => (#1 (let val (p, q) = (let val (p, q) = (let val (p, q) = ([0, 5, 2, (~7), (~3)], [6, 6]) in (q, p) end) in (q, p) end) in (q, p) end))) [] (List.concat [(List.tabulate (Int.abs ((Int.abs (Int.abs (~7)))) mod 12, (fn i => (List.last (0 :: [(~7), 7, (~2)]))))), ((#1 ([(~5), 4, 2, 1], [])) @ (#1 (let val xs = [7, 1, (~7), (~8)] val k = Int.abs ((~3)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)))]))))) ^ "\n");
