(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_121=" ^ (wrap (fn () => Bool.toString (((not ((if (not false) then (List.null [(~6)]) else (List.all (fn x => (x = x)) [3, 8, 8])) andalso (([4, (~2), (~2), 2] = [(~2), 6, 9, (~7), 1]) andalso (not false)))) andalso (let val v1 = (String.substring ((String.concatWith "-" (List.map Int.toString (List.rev [7, (~6)]))), 0, 1)) in (let val v2 = (String.concat (List.map (fn x => (Int.toString x)) (case [2] of [] => [] | (a :: rest) => rest @ [a]))) in (not ((~2) > (~6))) end) end))))) ^ "\n");
