(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_125=" ^ (wrap (fn () => pl2s ((let val v1 = (Int.toString ((List.last ((~6) :: [(~3), (~9)])) * (let val v2 = (5 div 1) in (let val v3 = ([3, 1, 5], []) in v2 end) end))) in (ListPair.unzip (ListPair.zip ((List.take ((List.drop ((List.mapPartial (fn x => if ("x" = "tz") then SOME ((3 - x)) else NONE) [7]), Int.abs ((case [7, (~3), (~10), 5, (~10)] of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) mod 7)), Int.abs ((Int.max ((2 mod 5), ((~9) * 7)))) mod 7)), (List.filter (fn x => (List.all (fn x => (not true)) (let val v4 = false in [(~8), (~5), 10, (~2)] end))) (#2 (List.partition (fn x => (List.all (fn x => (List.null [(~10)])) [6])) [8, 3, (~8), 6, 1])))))) end)))) ^ "\n");
