(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_116=" ^ (wrap (fn () => pr2s ((let val p = (let val xs = (List.foldr (fn (x, v1) => (if (4 <= 1) then (#2 ([0], [6, 5, 0])) else (if false then [(~9), (~9)] else v1))) [] (List.drop ((#1 ([(~5), 2, (~9), 6, (~5)], [(~2), (~9), 6, (~6)])), Int.abs ((String.size "3oq2")) mod 7))) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) in (#2 p, #1 p) end)))) ^ "\n");
