(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_107=" ^ (wrap (fn () => ((String.concat (List.map (fn x => (String.concat (List.map (fn x => (String.concatWith "-" (List.map Int.toString (List.foldr (fn (x, v1) => (List.drop ([6, 7, (~2), 5], Int.abs (x) mod 7))) [] (List.take ([2, 2, 8, 0, 3], Int.abs (2) mod 7)))))) (List.map (fn x => (List.nth ((List.concat [[], [9, (~4), (~8), (~4)]]), Int.abs ((getOpt (List.find (fn x => (x < (~10))) [], 0))) mod 7))) (List.mapPartial (fn x => if (isSome (List.find (fn x => (true andalso false)) [(~2), (~1), 1, (~10), 0])) then SOME ((List.nth ([9], Int.abs ((~5)) mod 7))) else NONE) (List.concat [[4, (~8), (~8), 8], [10, 1]])))))) ((List.filter (fn x => ((not true) andalso ((~5) = x))) (case (#2 ([8, 3, (~2), 5], [7, 7, 6])) of [] => [] | (a :: rest) => rest @ [a])) @ (#2 (if (let val v2 = ((~1), 7) in false end) then (List.partition (fn x => (if true then false else true)) [6, 5, (~6)]) else (let val xs = [(~9), 1, (~8), 4, (~10)] val k = Int.abs ((~1)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end))))))))) ^ "\n");
