(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_148=" ^ (wrap (fn () => Int.toString ((((case (if (isSome (List.find (fn x => ("kv7" = "7z7")) [8])) then (List.concat [[0, 7, (~1)], [2, 0]]) else ([(~1)] @ [])) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b) div (Int.min (((Int.max (3, 9)) - (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (8) mod 30) 0 end)), (#2 (let val v1 = ([(~7), (~1), (~3), 8, (~1)], [8, (~8), 10, 3, (~1)]) in ((~2), (~1)) end))))) mod (Int.max ((((getOpt (List.find (fn x => ("du" = "e o")) [(~4), (~1), (~2), (~6)], 0)) div (List.foldl (fn (x, v2) => (~ x)) 10 [5, (~1), 1, (~6), (~3)])) div (case (let val v3 = true in ([(~7), 7, 0, 8], [2]) end) of (xs, ys) => List.length xs - List.length ys)), (Int.abs (case (ListPair.unzip (ListPair.zip ([(~7), (~1), (~10), 5, 7], [(~7)]))) of (xs, ys) => List.length xs - List.length ys)))))))) ^ "\n");
