(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_131=" ^ (wrap (fn () => il2s ((case (List.mapPartial (fn x => if (List.all (fn x => (List.exists (fn x => (if false then false else false)) (List.map (fn x => (let val v1 = x in x end)) []))) (#1 (List.partition (fn x => ([] = [0, (~10), 10, (~9)])) [7, (~2), 2]))) then SOME ((Int.abs (#2 (let val (a, b) = ((~9), 6) in (b, a) end)))) else NONE) (let val v2 = ((Int.min (7, (~3))) :: (List.concat [[7, 10], [1, (~2), 7, 10, 6]])) in (List.take ((#1 ([(~8), 6, 7, (~7), (~3)], [(~3), 0, (~5), 10, 9])), Int.abs (((~10) + (~2))) mod 7)) end)) of [] => [] | (a :: rest) => rest @ [a])))) ^ "\n");
