(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_135=" ^ (wrap (fn () => il2s ((List.foldr (fn (x, v1) => (#2 (List.partition (fn x => (not ((~2) > 9))) (List.rev (List.mapPartial (fn x => if (x > x) then SOME ((hd [9, 7, (~2), (~9)])) else NONE) []))))) [] (#1 (List.partition (fn x => ((x div x) = (~ 3))) (List.map (fn x => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end)) (#1 (ListPair.unzip (ListPair.zip ([], [0, (~6)]))))))))))) ^ "\n");
