(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_106=" ^ (wrap (fn () => pr2s ((let val (a, b) = (let val p = (if ((String.concat (List.map (fn x => (if false then "b5" else "zjrit")) [6, 3])) = (Int.toString 9)) then ((List.foldr (fn (x, v1) => (List.last [(~10), (~7), 3])) 1 [4, (~2), (~8)]), (hd [])) else ((Int.min ((~8), 3)), (hd [0, (~1), 4]))) in (#2 p, #1 p) end) in (b, a) end)))) ^ "\n");
