(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_134=" ^ (wrap (fn () => Int.toString ((List.length (List.filter (fn x => ((if (isSome (List.find (fn x => (let val v1 = false in v1 end)) [(~10), 9, (~10)])) then (List.null []) else (List.null [0, (~6), (~2), 10])) orelse (isSome (List.find (fn x => ("73c" = "ch608")) (let val v2 = false in [(~9), 9, (~7), 10] end))))) (#1 (let val v3 = ((~6) <= 9) in (if v3 then ([(~10)], [(~10), (~9), 2]) else ([6, 5, 5, 7], [0, (~1), 8])) end))))))) ^ "\n");
