(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_132=" ^ (wrap (fn () => il2s ((#1 (ListPair.unzip (ListPair.zip ((#1 (ListPair.unzip (ListPair.zip ((List.rev (let val v1 = (Bool.toString true) in (List.drop ([(~3)], Int.abs ((~2)) mod 7)) end)), (((case [(~10), 9, 8] of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b) * (10 + (~6))) :: (([5] @ [(~9)]) @ (List.drop ([1], Int.abs (7) mod 7)))))))), (#1 (List.partition (fn x => (([(~9), (~8), 8, 1, 10] = []) andalso (false orelse true))) (#2 (let val v2 = "" in ([1], [(~8), 10, (~2), (~8)]) end))))))))))) ^ "\n");
