(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_130=" ^ (wrap (fn () => il2s ((List.concat [(List.take ((List.drop ((let val v1 = (let val v2 = ([10], []) in "r" end) in (5 :: [0]) end), Int.abs ((case (List.foldr (fn (x, v3) => (v3 @ v3)) [] [9, 10, 4, 6, (~5)]) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) mod 7)), Int.abs ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((Int.max ((List.length [(~9), (~3), (~7)]), (#2 (4, 5))))) mod 30) 0 end)) mod 7)), (List.tabulate (Int.abs ((let val v4 = ((List.take ([1, (~3)], Int.abs ((~4)) mod 7)), (List.rev [5, 9, 5, 9])) in (getOpt (List.find (fn x => ([] = [(~6)])) (List.filter (fn x => (x < 2)) [10, 7, 4, (~7)]), 0)) end)) mod 12, (fn i => (Int.min ((let val v5 = (if false then (3, 9) else (0, (~3))) in (String.size "p") end), (#1 (let val v6 = "" in (4, 0) end)))))))])))) ^ "\n");
