(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_128=" ^ (wrap (fn () => ((Bool.toString (isSome (List.find (fn x => ((List.filter (fn x => (List.all (fn x => (true orelse true)) [(~3), 10, 4, 5, (~3)])) (List.take ([6, 2, 3], Int.abs (3) mod 7))) = (List.take ((List.foldr (fn (x, v1) => (List.drop (v1, Int.abs (x) mod 7))) [] [0, (~10), (~9), 0]), Int.abs ((Int.max (6, x))) mod 7)))) (#1 (if (List.null [(~4), 1, (~10), (~8)]) then ([], [(~3)]) else (let val (p, q) = ([4, (~3), (~4), 2, (~4)], [2]) in (q, p) end))))))))) ^ "\n");
