(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_129=" ^ (wrap (fn () => Int.toString ((((#2 (let val xs = (List.map (fn x => (Int.min (x, (~1)))) [(~4)]) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end)) mod ((#2 (let val (a, b) = ((~6), (~6)) in (b, a) end)) - (let val v1 = (let val v2 = [(~4), 4, (~10)] in ([], []) end) in (Int.min (10, (~10))) end))) mod (Int.abs (List.foldr (fn (x, v3) => (List.nth ((List.mapPartial (fn x => if (x > 8) then SOME ((List.last [(~3), (~2), 5, 10])) else NONE) []), Int.abs ((Int.abs 8)) mod 7))) (~ (List.length [(~7), 10, (~1)])) ((#2 ([], [6, (~4), (~3), 8])) @ (#1 ([10, (~3), (~2)], [8]))))))))) ^ "\n");
