(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_149=" ^ (wrap (fn () => il2s ((List.map (fn x => (case (List.take ((let val v1 = (x :: [(~6), (~5), 0, 7]) in (case v1 of [] => [] | (a :: rest) => rest @ [a]) end), Int.abs ((if ((~10) > x) then (List.foldl (fn (x, v2) => (#1 (7, (~7)))) x [5, 0, (~6), 5]) else (x mod 1))) mod 7)) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) ((case (List.rev (case [6, 1, (~10), (~3)] of [] => [] | (a :: rest) => rest @ [a])) of [] => [] | (a :: rest) => rest @ [a]) @ (List.mapPartial (fn x => if ((String.map Char.toUpper "pzfw") = (let val v3 = [10, (~2), 0] in "8jsc" end)) then SOME ((case (if true then ([6, 7, 2, (~9)], [9]) else ([(~4), 5, 1, 4], [3, 5, 5, 1])) of (xs, ys) => List.length xs - List.length ys)) else NONE) (List.concat [(List.filter (fn x => (1 > 4)) [10, (~8), 2, 8, 10]), (List.drop ([1, (~1), (~7)], Int.abs ((~7)) mod 7))]))))))) ^ "\n");
