(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_142=" ^ (wrap (fn () => Int.toString ((hd (List.foldr (fn (x, v1) => (List.map (fn x => (#1 (x, x))) (List.filter (fn x => (x < x)) (List.tabulate (Int.abs ((~3)) mod 12, (fn i => (Int.min (i, i)))))))) [] (#1 (ListPair.unzip (ListPair.zip (((case [] of [] => [] | (a :: rest) => rest @ [a]) @ (List.concat [[], [4, (~10), 3, 4]])), (List.filter (fn x => (x <= 0)) (case [4, 8, (~6)] of [] => [] | (a :: rest) => rest @ [a]))))))))))) ^ "\n");
