(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_119=" ^ (wrap (fn () => il2s ((List.foldr (fn (x, v1) => (List.drop ((List.mapPartial (fn x => if ((false andalso false) orelse (let val v2 = [(~6)] in false end)) then SOME ((let val v3 = (List.foldr (fn (x, v4) => (Int.min ((~10), 7))) 10 [(~2)]) in (List.foldl (fn (x, v5) => (Int.abs x)) v3 v1) end)) else NONE) ((List.length [10, (~10)]) :: (List.filter (fn x => (x <= 5)) v1))), Int.abs (((if (false orelse false) then (#2 ((~2), 4)) else (List.length [1, (~8), 7, (~7)])) div (List.length (List.rev [5])))) mod 7))) [] (List.rev (List.concat [(#1 (ListPair.unzip (ListPair.zip ((#1 ([7, 10, 4, 10], [(~2), (~9), (~1), (~2)])), (List.tabulate (Int.abs ((~5)) mod 12, (fn i => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (i) mod 30) 0 end)))))))), (let val v6 = (String.substring ("0yoa", 0, 1)) in (List.foldr (fn (x, v7) => ((~6) :: v7)) [] [5, (~4), (~6), (~3)]) end)])))))) ^ "\n");
