(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_152=" ^ (wrap (fn () => Bool.toString ((((List.drop (((List.tabulate (Int.abs ((~1)) mod 12, (fn i => (String.size "xzi")))) @ (#1 ([9], [(~4), (~7), 10]))), Int.abs ((List.length (List.foldr (fn (x, v1) => (#2 ([5], []))) [] [(~3), 10, (~8), (~1)]))) mod 7)) = (#1 (ListPair.unzip (ListPair.zip (((List.nth ([(~2), 2, 2], Int.abs ((~10)) mod 7)) :: (#1 ([], []))), (List.filter (fn x => (let val v2 = [(~10), (~6)] in false end)) (case [(~9), (~5), (~7), (~3)] of [] => [] | (a :: rest) => rest @ [a]))))))) andalso (List.all (fn x => ((if (x < 1) then (List.foldr (fn (x, v3) => (getOpt (List.find (fn x => ("zgadk" = "addb")) [], 0))) 1 [1]) else (x * x)) <= ((#1 ((~6), 0)) + ((~3) * 4)))) (let val v4 = (let val (p, q) = (ListPair.unzip (ListPair.zip ([5, 5, 4, 8, 9], [9]))) in (q, p) end) in (#1 (let val xs = [] val k = Int.abs ((~7)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)) end)))))) ^ "\n");
