(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_102=" ^ (wrap (fn () => Int.toString ((#2 (let val xs = (List.concat [(List.concat [(let val v1 = false in [7, 5, (~1), (~1)] end), (if true then [(~3), (~2), (~1), (~1)] else [0, 1, 2, 9, 3])]), (case (List.mapPartial (fn x => if (List.all (fn x => (true andalso true)) []) then SOME (((~9) * (~10))) else NONE) [3, 6]) of [] => [] | (a :: rest) => rest @ [a])]) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end))))) ^ "\n");
