(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_12=" ^ (wrap (fn () => pl2s ((if (List.exists (fn x => (not (List.exists (fn x => (let val v1 = ((~9), (~4)) in false end)) ([6, (~1)] @ [0, 9, (~7), (~4), (~1)])))) (List.tabulate (Int.abs (((String.size "66xx") div (List.foldl (fn (x, v2) => (#1 (1, 4))) (~6) [(~5), 10, (~9)]))) mod 12, (fn i => (Int.max ((#1 ((~8), (~5))), (~ i))))))) then (ListPair.unzip (ListPair.zip ((#2 ((List.concat [[3, 10, (~5), 3, 8], []]), (List.mapPartial (fn x => if ("b 4" = "aig") then SOME ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (1) mod 30) 0 end)) else NONE) [5]))), (List.drop ((List.foldr (fn (x, v3) => (3 :: v3)) [] (List.tabulate (Int.abs ((~3)) mod 12, (fn i => (Int.abs i))))), Int.abs ((getOpt (List.find (fn x => (" 3" = "rmk")) (#1 (ListPair.unzip (ListPair.zip ([6, 4], [(~5), (~6), 6])))), 0))) mod 7))))) else (List.partition (fn x => (not ((if true then false else true) orelse (not true)))) (case (case (List.drop ([9, (~5)], Int.abs ((~2)) mod 7)) of [] => [] | (a :: rest) => rest @ [a]) of [] => [] | (a :: rest) => rest @ [a])))))) ^ "\n");
