(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_13=" ^ (wrap (fn () => pr2s ((let val (a, b) = (let val (a, b) = (let val v1 = (List.map (fn x => (#1 ((~8), 7))) (List.take ([6, (~6)], Int.abs ((~7)) mod 7))) in (if (List.exists (fn x => (true orelse false)) [0, 7, (~1), (~3)]) then (if true then (6, (~2)) else ((~9), 6)) else (let val (a, b) = (3, (~4)) in (b, a) end)) end) in (b, a) end) in (b, a) end)))) ^ "\n");
