(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_113=" ^ (wrap (fn () => pl2s ((let val xs = (List.tabulate (Int.abs ((case (List.mapPartial (fn x => if (List.null [(~10), (~8), (~9), 4]) then SOME (((~8) div x)) else NONE) (#1 ([(~9), (~2), (~9), (~6), (~2)], [(~8)]))) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) mod 12, (fn i => (Int.abs (case (if false then ([(~3), (~6), 6, 8], []) else ([8], [4])) of (xs, ys) => List.length xs - List.length ys))))) val k = Int.abs ((let val v1 = (let val v2 = (let val v3 = (ListPair.unzip (ListPair.zip ([(~10)], [4, (~5), 0]))) in ((~3) = 0) end) in (let val p = (let val xs = [] in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) in (#2 p, #1 p) end) end) in (List.last (List.foldr (fn (x, v4) => (List.tabulate (Int.abs ((~4)) mod 12, (fn i => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end))))) [] (List.concat [[(~2), (~8), 3, 6], [(~8)]]))) end)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)))) ^ "\n");
