(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_136=" ^ (wrap (fn () => Int.toString (((List.length (case (List.map (fn x => (x mod (~8))) (List.tabulate (Int.abs ((~5)) mod 12, (fn i => (~ (~5)))))) of [] => [] | (a :: rest) => rest @ [a])) + (hd (#2 (let val xs = (#1 ([0, 3, 7], [5])) val k = Int.abs ((9 * 8)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end))))))) ^ "\n");
