(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_122=" ^ (wrap (fn () => pr2s ((let val (a, b) = (let val xs = (if ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (0) mod 30) 0 end) <= (6 div (~10))) then (List.take ((List.map (fn x => (if true then 7 else x)) [(~6), 4, 9, (~9)]), Int.abs ((String.size "019xe")) mod 7)) else (List.map (fn x => (Int.min (8, 1))) (#1 ([(~4), (~1), 2, 6, 8], [1, 10, (~8), (~2)])))) in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) in (b, a) end)))) ^ "\n");
