(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_104=" ^ (wrap (fn () => pl2s ((List.partition (fn x => ((case (List.drop ((List.tabulate (Int.abs (x) mod 12, (fn i => (i mod (~7))))), Int.abs ((~ x)) mod 7)) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b) <= (List.nth ((List.concat [(#2 ([], [])), (List.tabulate (Int.abs (x) mod 12, (fn i => (let val v1 = "" in 1 end))))]), Int.abs ((String.size (String.substring ("", 0, 1)))) mod 7)))) (List.foldr (fn (x, v2) => (List.take ((List.map (fn x => ((~3) * 8)) (List.take (v2, Int.abs (x) mod 7))), Int.abs ((Int.min ((List.last []), (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end)))) mod 7))) [] (List.foldr (fn (x, v3) => (List.map (fn x => (List.foldl (fn (x, v4) => ((~6) + 2)) 0 [(~5), 10, 5, (~6)])) (List.tabulate (Int.abs ((~5)) mod 12, (fn i => (List.foldr (fn (x, v5) => (#1 (4, 8))) (~1) v3)))))) [] (List.take ((List.foldr (fn (x, v6) => (List.drop ([], Int.abs ((~3)) mod 7))) [] [2, 6]), Int.abs ((List.nth ([(~7), (~2), (~4)], Int.abs ((~1)) mod 7))) mod 7)))))))) ^ "\n");
