(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_123=" ^ (wrap (fn () => ((String.concat (List.map (fn x => (String.map Char.toUpper (let val v1 = (let val v2 = (9 > x) in (String.concatWith "-" (List.map Int.toString [(~10), (~9)])) end) in (Bool.toString (if false then true else true)) end))) (if (((List.concat [[2, 0, (~6), 2], [8, (~7), 6, (~4), 10]]) @ (#2 ([(~7), (~3), (~1), 7, (~6)], [9, (~5), (~8), 10, 4]))) = (if (8 > 6) then (List.tabulate (Int.abs (0) mod 12, (fn i => ((~7) - 0)))) else (List.tabulate (Int.abs ((~10)) mod 12, (fn i => (List.nth ([(~4), (~8), (~10), (~5)], Int.abs (1) mod 7))))))) then ((#1 (List.partition (fn x => (if false then false else true)) [(~7), 6])) @ (List.take ((List.tabulate (Int.abs (9) mod 12, (fn i => (String.size "y")))), Int.abs (((~2) div (~8))) mod 7))) else (List.rev ((Int.max ((~10), 2)) :: (List.filter (fn x => (isSome (List.find (fn x => (x > 7)) []))) [3]))))))))) ^ "\n");
