(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_141=" ^ (wrap (fn () => pr2s (((let val v1 = (List.all (fn x => (not ("0t" = "l"))) (#1 ([(~9), 2, (~2)], [7, 4]))) in (List.nth (((List.drop ([(~8), (~10)], Int.abs (0) mod 7)) @ ([] @ [])), Int.abs (((List.foldr (fn (x, v2) => (if v1 then x else v2)) (~7) [5, 1, 10, (~9)]) mod (Int.max ((~8), (~9))))) mod 7)) end), (getOpt (List.find (fn x => (List.null (List.mapPartial (fn x => if (x < 4) then SOME ((case ([(~2)], [8, 7]) of (xs, ys) => List.length xs - List.length ys)) else NONE) ([7] @ [3, (~7), 8, 2])))) (#1 (let val xs = (case [(~8), 0] of [] => [] | (a :: rest) => rest @ [a]) val k = Int.abs ((case ([3], [(~7)]) of (xs, ys) => List.length xs - List.length ys)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)), 0)))))) ^ "\n");
