(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_150=" ^ (wrap (fn () => il2s ((List.filter (fn x => (isSome (List.find (fn x => (((hd [(~2), 3, (~8)]) + (Int.min (x, (~8)))) > (Int.max ((case ([9, (~9), (~3), (~3)], [(~7), 8, (~7), (~4), (~7)]) of (xs, ys) => List.length xs - List.length ys), (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end))))) ((List.foldl (fn (x, v1) => (let val v2 = ([(~1), 8, (~5)], [(~6), (~6)]) in (~10) end)) (List.foldr (fn (x, v3) => (Int.min (x, 9))) 4 [(~9)]) (List.mapPartial (fn x => if ("" = "") then SOME ((Int.abs 5)) else NONE) [7, (~2), 6])) :: ((List.take ([(~5)], Int.abs ((~6)) mod 7)) @ (#1 ([(~4), 0, 6], [6]))))))) (#1 (List.partition (fn x => ((Int.toString x) = (String.substring ("q", 0, 1)))) (List.concat [([5, 2, 2, (~9)] @ [2, (~9), 2]), (List.mapPartial (fn x => if (false andalso true) then SOME ((8 - (~4))) else NONE) [(~4), 4, 5, (~1)])]))))))) ^ "\n");
