(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_0=" ^ (wrap (fn () => il2s ((#2 (let val xs = (List.filter (fn x => ((List.length [2]) = (Int.min (x, x)))) (List.mapPartial (fn x => if (let val v1 = ([1, 6], []) in false end) then SOME ((#2 ((~6), 7))) else NONE) (List.mapPartial (fn x => if (not true) then SOME ((#2 (8, (~7)))) else NONE) [(~9), 4]))) val k = Int.abs ((#2 (let val v2 = (if false then " 6" else "q") in (let val xs = [(~1), (~9)] in (List.length xs, List.foldl (fn (a,b) => a + b) 0 xs) end) end))) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end))))) ^ "\n");
