(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_153=" ^ (wrap (fn () => Bool.toString (((Int.min ((hd (List.map (fn x => (case [(~6), 1, 7, 5, 1] of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b)) (List.foldr (fn (x, v1) => (let val v2 = "3" in v1 end)) [] [5, 1]))), (List.length (case (List.filter (fn x => (if true then true else true)) [2, (~7), (~9), (~2)]) of [] => [] | (a :: rest) => rest @ [a])))) <= (String.size ((String.substring ((let val v3 = [(~4)] in "" end), 0, 1)) ^ (String.map Char.toUpper (Int.toString 8)))))))) ^ "\n");
