(* generated by tools/diff-corpus-gen/genprog_lists_hof.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun pl2s (xs,ys) = "(" ^ il2s xs ^ "," ^ il2s ys ^ ")";
val () = print ("@@genprog_lists_hof_120=" ^ (wrap (fn () => Int.toString ((List.foldl (fn (x, v1) => (List.last (#2 (let val xs = (case [3, (~2)] of [] => [] | (a :: rest) => rest @ [a]) val k = Int.abs ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (x) mod 30) 0 end)) mod 7 in (List.take (xs, Int.min (k, List.length xs)), List.drop (xs, Int.min (k, List.length xs))) end)))) (#2 ((Int.max ((10 mod (~7)), ((~7) + (~10)))), (case (List.filter (fn x => ((~10) = x)) [0, 8, 3, (~6), 7]) of [] => 0 | [a] => a | [a, b] => a + b | (a :: b :: _) => a - b))) (case (List.foldr (fn (x, v2) => (if (List.null v2) then (List.map (fn x => (hd [])) [(~1), (~1)]) else (#2 ([3, 0], [1, (~7)])))) [] (#2 (if false then ([(~5), 9], [(~2), (~10)]) else ([2], [(~3), 2, (~3), 2])))) of [] => [] | (a :: rest) => rest @ [a]))))) ^ "\n");
