(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_109=" ^ (wrap (fn () => Int.toString (((List.length (List.map Char.toUpper (let val v1 = (String.map Char.toUpper "rqm1") in ([(#"."), (#"2"), (#"b")] @ [(#"6")]) end))) + (#2 ((Char.ord (String.sub (",6y", 0))), ((fn v2 => (Int.abs (~4))) ((fn z => z ^ "b0 i") "j-3a")))))))) ^ "\n");
