(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_112=" ^ (wrap (fn () => Char.toString ((case ((List.filter Char.isAlpha (String.explode (Substring.string (Substring.dropr Char.isSpace (Substring.full "z6"))))) @ ((let val v1 = (let val cap = 4 in (fn v2 => String.size v2 + cap) end) in (let val v3 = "" in [(#"f"), (#"4"), (#"j"), (#"a")] end) end) @ (if ((#"t") = (#"t")) then (List.filter Char.isAlpha [(#"3")]) else (List.map Char.toUpper [(#"s"), (#"c")])))) of [] => #"?" | c :: _ => c)))) ^ "\n");
