(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_147=" ^ (wrap (fn () => Int.toString (((String.size (Substring.string (Substring.dropl Char.isSpace (Substring.full (String.concat (List.map (fn z => String.map Char.toUpper z) ["h.aq"])))))) * ((let val g = (fn a => fn b => a + b * (~8)) in g (List.length ("q5qd" :: ["d", "mea", "e5mk"])) end) (String.size (String.str (let val v2 = (fn z => String.implode (List.tabulate (Int.abs z mod 5, fn _ => #"x"))) in (#".") end)))))))) ^ "\n");
