(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_103=" ^ (wrap (fn () => Char.toString ((if ((Substring.string (Substring.triml (Int.abs ((List.length (List.rev [(#"8"), (#"e"), (#"2")]))) mod 4) (Substring.full (String.extract ((if false then "jd" else ""), Int.abs ((List.length (String.explode ""))) mod 4, NONE))))) = (Substring.string (Substring.full (String.concatWith "-" (String.fields (fn c => c = #",") "a9v2"))))) then (if (((#2 (1, (~1))) - (let val adder = (fn a => fn b => a + b) in ((adder (~4)) 5) end)) = (case Int.fromString (String.concat []) of SOME n => n | NONE => ~1)) then (case (List.map Char.toUpper (List.rev [(#"p"), (#"i"), (#"e")])) of [] => #"?" | c :: _ => c) else (String.sub ((if ((#"y") = (#"v")) then (String.map Char.toUpper "iu88c") else ("z" ^ "w0")), 0))) else (let val v1 = (fn z => Int.toString z) in (case (List.rev (let val v3 = (fn z => String.implode (List.rev (String.explode z))) in [(#"r"), (#"u")] end)) of [] => #"?" | c :: _ => c) end))))) ^ "\n");
