(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_149=" ^ (wrap (fn () => cl2s ((if ((Substring.string (Substring.dropr Char.isSpace (Substring.full (Substring.string (Substring.dropl Char.isSpace (Substring.full (String.concat []))))))) = (Int.toString (if (not true) then ((~1) + 0) else ((fn z => case Int.fromString z of SOME n => n | NONE => ~1) "")))) then (if (Char.isDigit (let val v1 = (List.rev [(~10), 0, 6, (~3)]) in (Char.chr (Int.abs ((~9)) mod 128)) end)) then (String.explode (Bool.toString (let val v2 = false in false end))) else (String.explode (((fn z => String.implode (List.rev (String.explode z))) o (fn z => String.map Char.toUpper z)) ("s2s" ^ ".a")))) else (let val v4 = (((fn z => z + (~9)) (List.length [])), (if (true andalso true) then (List.length [(#"4"), (#"5"), (#",")]) else (if true then (~9) else 9))) in (List.map Char.toUpper (List.filter Char.isAlpha (String.explode "o"))) end))))) ^ "\n");
