(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_153=" ^ (wrap (fn () => Char.toString ((let val v1 = (case (List.map Char.toUpper (String.explode (String.implode [(#"f"), (#"9"), (#"7"), (#"o")]))) of [] => #"?" | c :: _ => c) in (Char.toUpper (Char.chr (Int.abs (((let val g = (fn a => fn b => a + b * 6) in g 0 end) ((~8) - (~5)))) mod 128))) end)))) ^ "\n");
