(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_125=" ^ (wrap (fn () => pr2s ((let val v1 = (let val v2 = ((((~8) * 6) - (case [(~9), 8] of [] => 0 | x :: _ => x)), (String.size (String.implode [(#"6"), (#"r"), (#"9")]))) in (let val v3 = (fn z => List.length (String.explode z)) in (let val v5 = (7, (~4)) in ((~2), 2) end) end) end) in (let val v6 = ((let val v7 = (7, (~2)) in (String.map Char.toLower "3hr,6") end) :: (let val v8 = (fn v9 => (#1 v1)) in (let val v10 = (#".") in [",y ."] end) end)) in (let val p = (let val p = (let val v11 = (#"5") in (0, (~1)) end) in (#2 p, #1 p) end) in (#2 p, #1 p) end) end) end)))) ^ "\n");
