(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_118=" ^ (wrap (fn () => il2s (((((if (Char.isAlpha (#"r")) then (List.map Char.ord [(#"8"), (#"a"), (#".")]) else (List.map (fn z => ~ z) [4])) @ ((if false then 7 else 7) :: (List.map Char.ord [(#"2"), (#"z"), (#"h")]))) @ (List.map (fn z => z * (~3)) (let val v2 = ("vgw8" = "rhu") in ((~8) :: []) end))) @ (List.map Char.ord (let val v3 = (List.map (let val cap = (~6) in (fn v4 => String.size v4 + cap) end) (if true then ["by.", "", "jki"] else ["", "q"])) in (List.rev (List.map Char.toUpper [(#"o"), (#"i")])) end)))))) ^ "\n");
