(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_134=" ^ (wrap (fn () => il2s (((List.map (fn z => case Int.fromString z of SOME n => n | NONE => ~1) (((Substring.string (Substring.full "xng7e")) ^ (Substring.string (Substring.triml (Int.abs ((~2)) mod 4) (Substring.full "pad5")))) :: (if (String.isPrefix "e6" "ky") then (List.rev ["z2", "3j1oj"]) else ("t" :: [])))) @ (let val v2 = (List.map (let val cap = (8 - 7) in (fn v3 => (let val v4 = (#"p") in 9 end) + cap) end) (List.map (fn v5 => (let val adder = (fn a => fn b => a + b) in ((adder 2) 1) end)) (["0acpb"] @ []))) in ((let val v6 = (let val cap = (~10) in (fn v7 => String.size v7 + cap) end) in (List.map (fn z => String.size z) ["-ppy", "7k7", ",sl5b"]) end) @ (List.rev ((~3) :: v2))) end))))) ^ "\n");
