(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_123=" ^ (wrap (fn () => Int.toString ((case Int.fromString (if (Char.isDigit (Char.toUpper (Char.chr (Int.abs (2) mod 128)))) then (String.extract ((Substring.string (Substring.full ((fn z => String.implode (List.rev (String.explode z))) "3,"))), Int.abs ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((List.length [])) mod 30) 0 end)) mod 4, NONE)) else (String.translate (fn c => String.str c ^ String.str c) ((fn z => String.implode (List.rev (String.explode z))) (Substring.string (Substring.dropl Char.isSpace (Substring.full "1q")))))) of SOME n => n | NONE => ~1)))) ^ "\n");
