(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_150=" ^ (wrap (fn () => sl2s ((let val v1 = (fn v2 => (String.extract ((String.map Char.toUpper (String.implode [(#"f"), (#"k"), (#"i"), (#"h")])), Int.abs ((if (not true) then (let val adder = (fn a => fn b => a + b) in ((adder 5) (~3)) end) else (case Int.fromString v2 of SOME n => n | NONE => ~1))) mod 4, NONE))) in (List.map (fn z => z ^ "7 b77") (let val v4 = (let val v5 = ((~6) :: [(~1)]) in (Char.toUpper (#"p")) end) in (("z-" :: ["8,6", "b,u l", "od68r"]) @ ("" :: ["llstm", "55", "o"])) end)) end)))) ^ "\n");
