(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_100=" ^ (wrap (fn () => pr2s ((if ((Substring.string (Substring.dropl Char.isSpace (Substring.full (if (if true then true else false) then (String.concat [""]) else (Substring.string (Substring.triml (Int.abs ((~1)) mod 4) (Substring.full "4w26"))))))) = (Int.toString (case Int.fromString (String.str (#"q")) of SOME n => n | NONE => ~1))) then ((let val adder = (fn a => fn b => a + b) in ((adder (#1 (let val p = (1, 1) in (#2 p, #1 p) end))) (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((List.length (String.explode ""))) mod 30) 0 end)) end), (List.length ((String.explode "ag1ee") @ (List.map Char.toUpper [])))) else (((if (List.exists Char.isUpper [(#"0"), (#"a"), (#"o"), (#"w")]) then (List.length [(#"e")]) else (let val v1 = 4 in v1 end)) - (List.length (let val v2 = (4, (~4)) in [(#"t"), (#"z"), (#"1")] end))), (case (List.map (fn z => z * 10) (let val v4 = ["x4-zb", "", "qyir "] in [(~4), (~8), (~10)] end)) of [] => 0 | x :: _ => x)))))) ^ "\n");
