(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_137=" ^ (wrap (fn () => sl2s ((List.rev (((String.substring ((String.map Char.toUpper "6r7 2"), Int.abs (((fn z => List.length (String.explode z)) "jmfa8")) mod 4, Int.abs (((~1) - (~4))) mod 4)) :: (String.fields (fn c => c = #",") ((fn z => Int.toString z) (~3)))) @ ((String.str (Char.toLower (#"p"))) :: (String.fields (fn c => c = #",") (Int.toString 10)))))))) ^ "\n");
