(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_14=" ^ (wrap (fn () => il2s ((((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((case Int.fromString (String.concat ["z18", "3sx"]) of SOME n => n | NONE => ~1)) mod 30) 0 end) - (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs (((fn v1 => (#1 (1, (~5)))) (String.size "hh0kd"))) mod 30) 0 end)) :: (if ((String.size ((fn z => Int.toString z) 0)) = ((Int.abs 7) - (List.length (String.explode "")))) then (List.map Char.ord (([(#"w"), (#"6"), (#"c"), (#"9")] @ []) @ (if true then [(#"j"), (#"e"), (#"o"), (#"n")] else []))) else (List.map (let val cap = (Int.abs 2) in (fn v2 => String.size v2 + cap) end) (if (not false) then (if true then ["c", "vz", "j86ri"] else ["-xms0", "43c7", "o2pvu"]) else (if false then [] else [])))))))) ^ "\n");
