(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_152=" ^ (wrap (fn () => pr2s (((#2 (if (Char.isDigit (if false then (#"-") else (#"s"))) then (let val p = (let val p = (3, 5) in (#2 p, #1 p) end) in (#2 p, #1 p) end) else (let val v1 = (fn z => String.size z) in (if false then ((~5), 10) else ((~7), (~3))) end))), ((((let val v3 = (fn z => Int.toString (z + (~1))) in 7 end) - ((fn z => String.size z) "68.3")) + (Char.ord (Char.chr (Int.abs (9) mod 128)))) + (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((List.length (let val v4 = [] in [(#"x")] end))) mod 30) 0 end)))))) ^ "\n");
