(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_133=" ^ (wrap (fn () => pr2s ((let val v1 = (String.map Char.toLower (Bool.toString (Char.isAlpha (let val v2 = true in (#"7") end)))) in (((case (if true then [] else []) of [] => 0 | x :: _ => x) - ((let val v3 = ((~2), 10) in 9 end) - (if true then 3 else 9))), (Char.ord (let val v4 = (v1 :: ["om", " dn"]) in (Char.toUpper (#"5")) end))) end)))) ^ "\n");
