(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_114=" ^ (wrap (fn () => sl2s ((((List.map (let val cap = (String.str (#"j")) in (fn v1 => v1 ^ cap) end) (if (if false then true else true) then (String.fields (fn c => c = #",") "y130q") else (String.fields (fn c => c = #",") "l4b"))) @ (List.map (((fn z => String.implode (List.rev (String.explode z))) o (fn z => String.implode (List.rev (String.explode z)))) o (fn v4 => (Int.toString (~10)))) (List.map (fn v5 => (Int.toString 9)) (List.map (fn z => z ^ "5us") ["v,li"])))) @ (List.rev (let val v6 = (fn z => Int.toString (z + 7)) in (String.fields (fn c => c = #",") (String.extract ("qnz-", Int.abs (7) mod 4, NONE))) end)))))) ^ "\n");
