(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_146=" ^ (wrap (fn () => sl2s (((if ((if (List.exists Char.isUpper [(#"a"), (#"r"), (#"c"), (#"l")]) then (Substring.string (Substring.triml (Int.abs ((~10)) mod 4) (Substring.full ""))) else ("k9" ^ "pny")) < (String.implode (List.map Char.toUpper []))) then ((String.tokens Char.isSpace (String.implode [])) @ (String.tokens Char.isSpace (Substring.string (Substring.full "bqq")))) else (List.rev (List.map (let val cap = "" in (fn v1 => v1 ^ cap) end) (String.tokens Char.isSpace "t")))) @ (List.map (fn v2 => (Bool.toString (if true then false else false))) (let val v3 = (List.rev ([(~4), 8] @ [(~6), 6, (~9), 3])) in (List.map ((fn z => z ^ ",b") o (fn z => z ^ "7")) (String.fields (fn c => c = #",") "")) end)))))) ^ "\n");
