(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_135=" ^ (wrap (fn () => String.toString ((if (List.exists Char.isUpper (let val v1 = (fn v2 => (List.length (String.explode "ayn."))) in (List.map Char.toUpper (List.filter Char.isAlpha [(#"z")])) end)) then (Substring.string (Substring.dropl Char.isSpace (Substring.full (Substring.string (Substring.triml (Int.abs ((case (List.map (fn z => case Int.fromString z of SOME n => n | NONE => ~1) ["-s ", "p"]) of [] => 0 | x :: _ => x)) mod 4) (Substring.full (Bool.toString (Char.isDigit (#"p"))))))))) else (String.extract ((Substring.string (Substring.triml (Int.abs ((List.length (String.explode (String.translate (fn c => String.str c ^ String.str c) "9")))) mod 4) (Substring.full (String.extract (((fn z => String.implode (List.rev (String.explode z))) "ccr"), Int.abs ((#2 ((~4), 4))) mod 4, NONE))))), Int.abs ((Int.abs (Char.ord (Char.toLower (#" "))))) mod 4, NONE)))))) ^ "\n");
