(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_11=" ^ (wrap (fn () => Char.toString ((if (((String.sub ((Bool.toString true), 0)) = (let val v1 = (fn z => List.length (String.explode z)) in (Char.chr (Int.abs (7) mod 128)) end)) andalso (if (if (false andalso false) then (false andalso true) else (2 < (~10))) then (if (Char.isAlpha (#"z")) then ((#"5") = (#"5")) else ("" < "fu-yi")) else (String.isPrefix (Substring.string (Substring.dropl Char.isSpace (Substring.full ""))) (Int.toString 0)))) then (String.sub ((String.translate (fn c => String.str c ^ String.str c) (let val v3 = ((fn z => z - 10) o (fn z => z + 3)) in (String.str (#"7")) end)), 0)) else (Char.toLower (Char.toLower (String.sub (("0.wz" ^ "st3"), 0)))))))) ^ "\n");
