(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_131=" ^ (wrap (fn () => sl2s ((let val v1 = (Char.toLower (Char.toLower (case (List.map Char.toUpper [(#"7"), (#"8"), (#"4")]) of [] => #"?" | c :: _ => c))) in (String.fields (fn c => c = #",") ((fn z => Int.toString z) (Char.ord (if false then (#"5") else v1)))) end)))) ^ "\n");
