(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_122=" ^ (wrap (fn () => Bool.toString ((((if (((fn z => String.map Char.toUpper z) "c") < (String.map Char.toUpper "-xm")) then (case (if true then [(#"n")] else []) of [] => #"?" | c :: _ => c) else (Char.chr (Int.abs (((fn z => Int.abs z) 1)) mod 128))) = (case (List.rev (String.explode "s")) of [] => #"?" | c :: _ => c)) andalso (((case ([(#"4")] @ [(#"e"), (#"1"), (#"m"), (#"4")]) of [] => #"?" | c :: _ => c) = (String.sub ((Int.toString 2), 0))) andalso (String.isPrefix (Substring.string (Substring.dropr Char.isSpace (Substring.full (Substring.string (Substring.triml (Int.abs ((~8)) mod 4) (Substring.full "jx")))))) (((fn z => String.implode (List.tabulate (Int.abs z mod 5, fn _ => #"x"))) o (fn z => z - 1)) (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((~7)) mod 30) 0 end)))))))) ^ "\n");
