(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_140=" ^ (wrap (fn () => pr2s (((Int.abs (case (List.map (fn v1 => ((fn z => z * (~4)) v1)) (if true then [3] else [2, (~9), 1, 7])) of [] => 0 | x :: _ => x)), (List.length ((if (10 < (~3)) then (if false then (#" ") else (#"p")) else (Char.toUpper (#"l"))) :: ((case [(#"y"), (#"s"), (#"l"), (#"6")] of [] => #"?" | c :: _ => c) :: (List.filter Char.isAlpha [(#"4"), (#"1")])))))))) ^ "\n");
