(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_124=" ^ (wrap (fn () => pr2s (((Char.ord (Char.toUpper (String.sub ((String.concatWith "-" ["d"]), 0)))), (if (Char.isAlpha (String.sub ((Substring.string (Substring.triml (Int.abs (8) mod 4) (Substring.full "f"))), 0))) then ((fn v1 => (Int.abs 8)) (String.implode (List.rev [(#"r"), (#"l")]))) else (#1 (let val p = (if true then (6, 3) else ((~4), 5)) in (#2 p, #1 p) end))))))) ^ "\n");
