(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_12=" ^ (wrap (fn () => Int.toString ((if ((Int.abs ((let val g = (fn a => fn b => a + b * 0) in g (~5) end) (List.length ["70gf", "8gq "]))) < (String.size (String.concat (String.tokens Char.isSpace "w0i")))) then ((#1 (if (List.exists Char.isUpper [(#"8")]) then ((~6), 9) else (let val v2 = (fn z => case Int.fromString z of SOME n => n | NONE => ~1) in ((~6), 4) end))) - (case Int.fromString (String.extract ((String.extract ("", Int.abs (6) mod 4, NONE)), Int.abs ((if true then (~8) else (~4))) mod 4, NONE)) of SOME n => n | NONE => ~1)) else (String.size (((fn z => String.implode (List.rev (String.explode z))) o (fn z => String.map Char.toUpper z)) (String.substring ((Bool.toString false), Int.abs ((let val adder = (fn a => fn b => a + b) in ((adder (~7)) 4) end)) mod 4, Int.abs ((5 + 7)) mod 4)))))))) ^ "\n");
