(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_111=" ^ (wrap (fn () => cl2s (((Char.toUpper (let val v1 = (let val v2 = (let val g = (fn a => fn b => a + b * 2) in g 2 end) in (let val p = ((~8), 4) in (#2 p, #1 p) end) end) in (Char.toUpper (let val v4 = (fn z => z * 6) in (#"j") end)) end)) :: (if ((Int.toString (List.length (String.explode "3d"))) < (String.str (case [(#"m")] of [] => #"?" | c :: _ => c))) then (let val v5 = ((Char.chr (Int.abs ((~8)) mod 128)) = (case [(#"p")] of [] => #"?" | c :: _ => c)) in ((List.filter Char.isAlpha [(#"s"), (#"a"), (#"a"), (#"3")]) @ ((#"d") :: [(#"-"), (#"j"), (#"0")])) end) else (((let val v6 = [] in (#"r") end) :: ([(#" "), (#"v"), (#"c")] @ [(#"c"), (#"e"), (#"c")])) @ (if (let val v7 = ((~7), 10) in true end) then (List.rev [(#"y"), (#"6"), (#"t"), (#"a")]) else (List.map Char.toUpper [(#"o"), (#"q")])))))))) ^ "\n");
