(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_13=" ^ (wrap (fn () => il2s ((List.map (fn v1 => (let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((#1 (let val p = (0, (~5)) in (#2 p, #1 p) end))) mod 30) 0 end)) (String.fields (fn c => c = #",") (Substring.string (Substring.dropl Char.isSpace (Substring.full (Bool.toString (Char.isSpace (#"a"))))))))))) ^ "\n");
