(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_107=" ^ (wrap (fn () => pr2s ((if (Char.isSpace (case (String.explode (String.translate (fn c => String.str c ^ String.str c) "d")) of [] => #"?" | c :: _ => c)) then ((String.size (let val v1 = (fn v2 => (String.extract ("c9", Int.abs (v2) mod 4, NONE))) in ("at1" ^ "4dd75") end)), (#2 ((2 * 5), (List.length [(#"s"), (#"o"), (#"h")])))) else (((fn z => case Int.fromString z of SOME n => n | NONE => ~1) (String.implode ([(#"9")] @ [(#"8"), (#"t")]))), (case (((fn z => String.size z) "s3fm") :: ([5, (~10)] @ [(~8), 6])) of [] => 0 | x :: _ => x)))))) ^ "\n");
