(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_120=" ^ (wrap (fn () => pr2s ((if (String.isPrefix (String.concat ((String.implode [(#"j"), (#"7"), (#"2")]) :: ([] @ ["m", "m.mfx", "o"]))) (Substring.string (Substring.dropr Char.isSpace (Substring.full ((fn z => String.map Char.toUpper z) ((fn z => String.map Char.toUpper z) "2kcr")))))) then (if (Char.isDigit (case (if true then [(#"u"), (#" "), (#"s")] else []) of [] => #"?" | c :: _ => c)) then (let val v2 = (let val cap = (Int.abs (~4)) in (fn v3 => String.size v3 + cap) end) in (if (false andalso false) then (if false then (7, 9) else (1, (~6))) else (3, 0)) end) else (if (((~7) = (~8)) andalso (5 = 1)) then (let val p = (let val p = (0, 7) in (#2 p, #1 p) end) in (#2 p, #1 p) end) else ((#2 ((~3), 7)), (Char.ord (#"i"))))) else (let val p = (let val p = (let val v4 = (Char.toUpper (#"t")) in (let val v5 = (fn z => z + (~6)) in ((~2), 7) end) end) in (#2 p, #1 p) end) in (#2 p, #1 p) end))))) ^ "\n");
