(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_127=" ^ (wrap (fn () => pr2s ((if (Char.isDigit (Char.toLower (Char.chr (Int.abs ((if false then 10 else 6)) mod 128)))) then (((String.size (String.str (#"b"))) * (case (List.map (fn z => z * 9) [(~3)]) of [] => 0 | x :: _ => x)), (List.length (String.explode (String.map Char.toLower (String.translate (fn c => String.str c ^ String.str c) "0h7vg"))))) else (if (Char.isSpace (case (List.rev [(#"h"), (#"d"), (#"0")]) of [] => #"?" | c :: _ => c)) then (let val p = (let val p = ((~9), (~4)) in (#2 p, #1 p) end) in (#2 p, #1 p) end) else (let val v1 = (Int.abs (if true then 2 else 9)) in (if (let val v2 = (fn z => String.map Char.toUpper z) in false end) then ((~3), v1) else (if true then ((~6), (~1)) else (10, (~1)))) end)))))) ^ "\n");
