(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_119=" ^ (wrap (fn () => Char.toString ((let val v1 = ((List.length (String.tokens Char.isSpace (Int.toString (~6)))), (#2 ((#1 (2, (~6))), (case [1, (~10)] of [] => 0 | x :: _ => x)))) in (Char.toUpper (let val v2 = ((fn v4 => (case Int.fromString "5if2" of SOME n => n | NONE => ~1)) o (let val cap = 5 in (fn v5 => (case Int.fromString ",vrx7" of SOME n => n | NONE => ~1) + cap) end)) in (Char.toUpper (String.sub ("ll", 0))) end)) end)))) ^ "\n");
