(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_116=" ^ (wrap (fn () => cl2s ((let val v1 = ((String.sub ((Bool.toString (List.exists Char.isUpper [])), 0)) :: (if (Char.isDigit (if true then (#"c") else (#"6"))) then (List.map Char.toUpper (List.map Char.toUpper [])) else (String.explode (let val v2 = (fn z => Int.toString z) in "9 " end)))) in ((case (String.explode (Substring.string (Substring.triml (Int.abs ((~5)) mod 4) (Substring.full "yr6")))) of [] => #"?" | c :: _ => c) :: (List.filter Char.isAlpha (List.map Char.toUpper (String.explode "v")))) end)))) ^ "\n");
