(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_139=" ^ (wrap (fn () => il2s (((List.length ((List.rev ("v78" :: ["l0-", "1ke", "qtjb"])) @ (List.map (let val cap = "" in (fn v1 => v1 ^ cap) end) (String.fields (fn c => c = #",") "-8")))) :: (List.rev ((if (let val v2 = [] in false end) then (List.map Char.ord [(#"v"), (#"d")]) else (if false then [4, 7] else [5, 5, (~6), 9])) @ ((List.rev [6]) @ (List.rev [(~3), (~5)])))))))) ^ "\n");
