(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_102=" ^ (wrap (fn () => Int.toString ((case (List.map Char.ord (String.explode (String.extract ((Substring.string (Substring.dropl Char.isSpace (Substring.full ""))), Int.abs ((List.length ["rj-s-", "4r0", "iby9"])) mod 4, NONE)))) of [] => 0 | x :: _ => x)))) ^ "\n");
