(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_145=" ^ (wrap (fn () => String.toString ((Bool.toString (String.isPrefix (Substring.string (Substring.full (String.substring ((Substring.string (Substring.full "rs85")), Int.abs ((let val adder = (fn a => fn b => a + b) in ((adder 5) (~3)) end)) mod 4, Int.abs ((#1 (3, (~9)))) mod 4)))) (Substring.string (Substring.full (Substring.string (Substring.dropr Char.isSpace (Substring.full (Substring.string (Substring.dropl Char.isSpace (Substring.full "4f"))))))))))))) ^ "\n");
