(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_142=" ^ (wrap (fn () => il2s (((List.map Char.ord (String.explode (String.implode (String.explode "ge")))) @ (List.map ((let val cap = ((fn z => List.length (String.explode z)) "") in (fn v2 => String.size v2 + cap) end) o ((fn v4 => (String.map Char.toUpper "aw0t")) o (fn v5 => (Bool.toString true)))) ((Substring.string (Substring.dropl Char.isSpace (Substring.full (String.map Char.toUpper "9")))) :: (List.map (fn z => z ^ "1-x") (if false then ["ef9g", "r0r", "mc6q"] else ["", "g6yn"])))))))) ^ "\n");
