(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_126=" ^ (wrap (fn () => String.toString ((Substring.string (Substring.triml (Int.abs (((String.size (Bool.toString (let val v1 = (#" ") in true end))) * (#2 (let val v2 = (Char.toUpper (#"o")) in (if true then (6, 10) else (6, (~2))) end)))) mod 4) (Substring.full (String.str (String.sub (((let val cap = "w0nq" in (fn v3 => v3 ^ cap) end) (String.substring ("dx", Int.abs ((~8)) mod 4, Int.abs ((~7)) mod 4))), 0))))))))) ^ "\n");
