(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_10=" ^ (wrap (fn () => cl2s ((List.filter Char.isAlpha (let val v1 = (String.implode (let val v2 = (let val v3 = (fn z => String.implode (List.tabulate (Int.abs z mod 5, fn _ => #"x"))) in ["ae"] end) in ([(#"c"), (#"2")] @ [(#"u")]) end)) in (let val v4 = (fn v5 => (String.map Char.toLower "poa")) in (List.map Char.toUpper (String.explode v1)) end) end))))) ^ "\n");
