(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_141=" ^ (wrap (fn () => String.toString (((fn z => Int.toString (z + 3)) (#2 ((let fun f n acc = if n <= 0 then acc else f (n-1) (acc+n) in f (Int.abs ((case [9] of [] => 0 | x :: _ => x)) mod 30) 0 end), (#1 (let val p = ((~7), (~4)) in (#2 p, #1 p) end)))))))) ^ "\n");
