(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_104=" ^ (wrap (fn () => sl2s (((if ((Char.ord (if false then (#"4") else (#"t"))) < (let val v1 = (List.filter Char.isAlpha [(#"7"), (#"q"), (#"r"), (#"m")]) in (String.size "") end)) then (String.fields (fn c => c = #",") (String.substring ((let val v2 = [] in "dd4w3" end), Int.abs ((#1 ((~6), (~8)))) mod 4, Int.abs ((Char.ord (#"8"))) mod 4))) else ((let val v3 = (fn v4 => (5 * 4)) in (List.map (fn z => String.map Char.toUpper z) ["", "", ""]) end) @ (String.fields (fn c => c = #",") (String.str (#"1"))))) @ (((String.fields (fn c => c = #",") (Substring.string (Substring.dropr Char.isSpace (Substring.full "y7,")))) @ (if ("84q0u" < "4x") then (let val v5 = true in [",3y.", ""] end) else (String.tokens Char.isSpace ""))) @ ((Substring.string (Substring.dropl Char.isSpace (Substring.full (Substring.string (Substring.triml (Int.abs (1) mod 4) (Substring.full "3o")))))) :: ((String.extract ("a", Int.abs (2) mod 4, NONE)) :: (List.map (fn z => String.map Char.toUpper z) ["d92", "t8rn", "z"])))))))) ^ "\n");
