(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_101=" ^ (wrap (fn () => Char.toString ((let val v1 = (Char.toUpper (Char.toLower (Char.chr (Int.abs ((List.length ["a0.", ","])) mod 128)))) in (if (String.isSubstring (String.map Char.toLower (String.map Char.toLower "312")) (Substring.string (Substring.triml (Int.abs ((case [(~4), 3] of [] => 0 | x :: _ => x)) mod 4) (Substring.full (String.extract ("", Int.abs ((~6)) mod 4, NONE)))))) then (case (let val v2 = (Char.isSpace v1) in (String.explode "") end) of [] => #"?" | c :: _ => c) else (Char.toLower (let val v3 = (List.filter Char.isAlpha [(#"j")]) in (String.sub ("-v-", 0)) end))) end)))) ^ "\n");
