(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_121=" ^ (wrap (fn () => String.toString ((Substring.string (Substring.full (String.substring (((String.translate (fn c => String.str c ^ String.str c) (Substring.string (Substring.dropr Char.isSpace (Substring.full "jyiqe")))) ^ (String.substring ((Substring.string (Substring.triml (Int.abs (3) mod 4) (Substring.full "da4l"))), Int.abs ((8 * 6)) mod 4, Int.abs (((fn z => Int.abs z) 9)) mod 4))), Int.abs ((let val v1 = ((let val adder = (fn a => fn b => a + b) in ((adder 8) (~10)) end), (let val adder = (fn a => fn b => a + b) in ((adder 10) 1) end)) in (Char.ord (String.sub ("n", 0))) end)) mod 4, Int.abs ((List.length (List.map Char.toUpper (List.filter Char.isAlpha [(#"7"), (#"5"), (#".")])))) mod 4))))))) ^ "\n");
