(* generated by tools/diff-corpus-gen/genprog_strings_closures.sml -- DO NOT EDIT *)
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Chr => "CHR" | Option => "OPT"
  | Match => "MATCH" | Bind => "BIND" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun cl2s xs = "[" ^ String.concatWith "," (List.map Char.toString xs) ^ "]";
fun sl2s xs = "[" ^ String.concatWith "," (List.map String.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
val () = print ("@@genprog_sc_138=" ^ (wrap (fn () => Int.toString ((Int.abs (Char.ord (if ((3 + 6) < (case Int.fromString "f" of SOME n => n | NONE => ~1)) then (case (List.filter Char.isAlpha [(#"g"), (#"7")]) of [] => #"?" | c :: _ => c) else (Char.chr (Int.abs ((0 + (~1))) mod 128)))))))) ^ "\n");
