(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_108=" ^ (wrap (fn () => pr2s ((((let val p = (((let val p = ((((~8), (~1)) handle E2 => ((~6), 3)) handle E1 v1 => ((~6), 8) | _ => ((~10), 8)) in (#2 p, #1 p) end) handle E2 => (let val p = (let val p = ((~4), 5) in (#2 p, #1 p) end) in (#2 p, #1 p) end)) handle E1 v2 => (if (true andalso false) then (let val t = (Leaf 2) in (treeSum t, treeDepth t) end) else (let val v3 = (Lft (~1)) in (3, 1) end)) | _ => (let val p = (if false then (10, (~7)) else (2, 4)) in (#2 p, #1 p) end)) in (#2 p, #1 p) end) handle E2 => (let val v5 = (Rgt (Int.toString ((~7) * (~8)))) in (let val p = ((if false then (1, 9) else (10, 4)) handle E1 v6 => (if true then ((~9), (~2)) else (5, (~3))) | _ => (0, 5)) in (#2 p, #1 p) end) end)) handle E1 v4 => (let val t = (let val v14 = (listToTree (List.rev [2, (~8), (~9)])) in (treeMap (fn x => (List.foldl (fn (a,b) => a + b) 0 [])) (Leaf (~2))) end) in (treeSum t, treeDepth t) end) | _ => (let val p = ((let val p = ((((~3), (~8)) handle E2 => ((~10), 10)) handle E1 v7 => (9, 3) | _ => (8, 8)) in (#2 p, #1 p) end) handle E1 v8 => ((v8 handle E1 v13 => 9 | _ => v8), (8 div v8)) | _ => (if (if false then true else false) then (let val v9 = (Leaf 7) in (5, (~7)) end) else (let val t = (Leaf 4) in (treeSum t, treeDepth t) end))) in (#2 p, #1 p) end))))) ^ "\n");
