(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_140=" ^ (wrap (fn () => treeShow ((Br (((let val v1 = (((String.map Char.toUpper "qizz") handle E1 v2 => raise E2) handle E2 => (Bool.toString false) | _ => (String.concatWith "-" (List.map Int.toString [7, 6, (~7), 2]))) in (listToTree (if true then [] else [6, 6, 8, 3])) end) handle E1 v3 => (let val v7 = (let val v8 = (if true then [(~5), (~9), (~6), (~7)] else [(~8)]) in (if true then (Leaf (~2)) else (Leaf 0)) end) in (let val v9 = (v3 + 3) in (if true then v7 else v7) end) end) | _ => (Br ((Br ((if true then (Leaf 7) else (Leaf 6)), (Br ((Leaf 2), (Leaf (~2)))))), (if ((false handle E2 => false) handle E1 v4 => true | _ => false) then (Leaf 3) else ((Leaf 6) handle E1 v5 => (Leaf (~5)) | _ => (Leaf 5)))))), (treeMap (fn x => (let val v10 = (if (true andalso false) then (((Leaf (~2)) handle E2 => (Leaf (~6))) handle E1 v11 => (Leaf (~3)) | _ => (Leaf 6)) else (((Leaf 5) handle E1 v12 => raise E2) handle E2 => (Leaf (~10)) | _ => (Leaf 2))) in ((Int.max (x, x)) - (x - (~1))) end)) ((((Leaf (~10)) handle E1 v13 => raise E2) handle E2 => (Br ((Leaf (~7)), (Leaf (~3)))) | _ => ((Leaf (~3)) handle E1 v14 => (Leaf 7) | _ => (Leaf 2))) handle E1 v15 => (Br ((listToTree [8]), (Br ((Leaf (~8)), (Leaf 1))))) | _ => (Leaf (List.length [(~3), 1, (~8), 5]))))))))) ^ "\n");
