(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_113=" ^ (wrap (fn () => ((((if (List.all (fn x => x < 100) ((List.map (fn x => if x < 0 then raise E1 x else x + 1) (List.map (fn x => ((x handle E2 => x) handle E1 v1 => x | _ => 2)) [])) handle E1 _ => [])) then (String.map Char.toUpper (Bool.toString (if true then true else true))) else (case (Rgt (String.map Char.toUpper "p3is")) of Lft n => "L" ^ Int.toString n | Rgt s => "R" ^ s)) handle E2 => (if (List.null ((treeDepth (Leaf 10)) :: ([] @ [(~4), (~8), (~1), 2]))) then (Bool.toString ((String.size "") > (#1 (8, (~3))))) else (String.substring ((Bool.toString (List.null [])), 0, 1)))) handle E1 v2 => (Bool.toString (let val v6 = ((treeDepth (Leaf (~10))), ((~1) * v2)) in (("" ^ "") = (" " ^ "5a")) end)) | _ => (case (((Rgt (let val v3 = (Leaf (~1)) in "oo" end)) handle E2 => (let val n = ((case Non of Som n => n | Non => raise E1 (~1)) handle E1 k => k) in if n mod 2 = 0 then Lft n else Rgt (Int.toString n) end)) handle E1 v4 => (if ((~9) < v4) then (Lft v4) else (((Rgt "asilq") handle E1 v5 => raise E2) handle E2 => (Lft 8) | _ => (Rgt "u1"))) | _ => (if (not true) then (Rgt "l2") else (Lft (~3)))) of Lft n => "L" ^ Int.toString n | Rgt s => "R" ^ s))))) ^ "\n");
