(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_106=" ^ (wrap (fn () => pr2s ((let val v1 = (Som ((String.size (String.concatWith "-" (List.map Int.toString [(~1), (~3), (~6), 5]))) + ((Int.max (4, (~8))) mod ((~4) + (~6))))) in (((if (List.exists (fn x => x > 0) (treeFlat (Leaf (~5)))) then (let val v2 = (String.concatWith "-" (List.map Int.toString [8])) in (let val t = (Leaf (~7)) in (treeSum t, treeDepth t) end) end) else ((String.size "zi3jb"), (#2 (6, 0)))) handle E2 => (let val v4 = ((List.foldl (fn (a,b) => a + b) 0 []) + (0 div (~1))) in ((7 - v4), (case (Rgt "iwz2") of Lft n => n | Rgt s => String.size s)) end)) handle E1 v3 => (let val p = (let val v6 = (Int.toString v3) in (v3, 9) end) in (#2 p, #1 p) end) | _ => (let val p = (let val t = (((Leaf 8) handle E1 v5 => raise E2) handle E2 => (Leaf 9) | _ => (Leaf (~3))) in (treeSum t, treeDepth t) end) in (#2 p, #1 p) end)) end)))) ^ "\n");
