(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_136=" ^ (wrap (fn () => pr2s ((((if (not (treeAny (((Leaf 3) handle E2 => (Leaf (~7))) handle E1 v1 => (Leaf (~1)) | _ => (Leaf 5)))) then (if ((String.size "") < (#1 (1, (~3)))) then (let val v2 = (if false then Non else Non) in ((((~3), (~10)) handle E2 => (8, 4)) handle E1 v3 => ((~1), 9) | _ => ((~9), 7)) end) else (if (let val v4 = [(~3), (~9), (~9), 6] in true end) then (3, (~6)) else (let val v5 = "i" in ((~2), 0) end))) else (if ((#1 ((~6), (~3))) = (treeDepth (Leaf (~5)))) then ((((4, 8) handle E2 => (5, (~1))) handle E1 v6 => (6, (~6)) | _ => (2, 8)) handle E1 v7 => (let val t = (Leaf 10) in (treeSum t, treeDepth t) end) | _ => ((8, 6) handle E1 v8 => ((~4), (~7)) | _ => ((~3), (~5)))) else (if ((~6) = 6) then ((~9), (~6)) else (((~1), (~8)) handle E1 v10 => ((~1), 0) | _ => ((~9), 2))))) handle E1 v11 => raise E2) handle E2 => (if ((treeShow (let val v12 = (Leaf 9) in v12 end)) = (treeShow (let val v13 = "lhkvw" in (Leaf (~4)) end))) then (let val t = (if (treeAny (Leaf (~4))) then (Leaf 8) else (Br ((Leaf 9), (Leaf 7)))) in (treeSum t, treeDepth t) end) else ((let val t = (((Leaf 3) handle E2 => (Leaf 2)) handle E1 v14 => (Leaf 2) | _ => (Leaf 8)) in (treeSum t, treeDepth t) end) handle E1 v15 => (if (true orelse false) then (5, (~2)) else (let val t = (Leaf (~6)) in (treeSum t, treeDepth t) end)) | _ => (let val t = (((Leaf 5) handle E1 v16 => raise E2) handle E2 => (Leaf 7) | _ => (Leaf (~9))) in (treeSum t, treeDepth t) end))) | _ => ((#1 ((#1 ((~10), 8)), (1 mod (~9)))), (List.length (if (if true then false else false) then (treeFlat (Leaf 6)) else (case [(~10), 6, (~4)] of [] => [] | _ :: t => t)))))))) ^ "\n");
