(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_152=" ^ (wrap (fn () => (case ((if ((case (let val v1 = (("bjih" handle E1 v2 => raise E2) handle E2 => "fzi" | _ => "") in (Rgt "vwj") end) of Lft _ => true | Rgt _ => false) orelse (if ((case (Lft 8) of Lft n => n | Rgt s => String.size s) > (case (Som (~7)) of Non => 0 | Som 0 => 100 | Som n => n)) then ((String.substring ("0", 0, 1)) = (Bool.toString true)) else (if (4 <= (~10)) then (let val v3 = 9 in false end) else ((~1) > 7)))) then (let val n = (case (let val v4 = (treeFind (Leaf 2)) in (treeFind (Leaf 2)) end) of Non => 0 | Som 0 => 100 | Som n => n) in if n mod 2 = 0 then Lft n else Rgt (Int.toString n) end) else (((((if true then (Rgt "8 5b") else (Rgt "irp")) handle E1 v5 => (Lft 10) | _ => (let val v6 = true in (Rgt "v") end)) handle E1 v7 => (Rgt (String.substring ("3c1 ", 0, 1))) | _ => (if (case Non of Non => false | Som _ => true) then (let val v8 = "qdn" in (Rgt "bb") end) else (((Lft (~5)) handle E2 => (Lft (~2))) handle E1 v9 => (Rgt "03kik") | _ => (Rgt "")))) handle E2 => (let val n = (case (((Som 0) handle E1 v11 => raise E2) handle E2 => (Som 0) | _ => Non) of Non => 0 | Som 0 => 100 | Som n => n) in if n mod 2 = 0 then Lft n else Rgt (Int.toString n) end)) handle E1 v10 => (if ((Int.max (v10, 10)) <= (~ (~9))) then (if (false handle E1 v15 => false | _ => false) then (if false then (Rgt "") else (Rgt "fy ")) else (Lft 1)) else (let val v16 = ((1, (~2)) handle E1 v17 => (2, 2) | _ => (3, 10)) in (if false then (Lft 7) else (Lft 10)) end)) | _ => (if (List.null ([0, (~5), (~4), (~6)] @ [(~5)])) then (((((Lft 5) handle E2 => (Rgt "8")) handle E1 v12 => (Rgt "") | _ => (Lft (~6))) handle E2 => (Rgt "72y")) handle E1 v13 => (let val v14 = true in (Lft (~8)) end) | _ => (Rgt "")) else (Rgt (case (Som 7) of Non => "none" | Som n => "some:" ^ Int.toString n)))))) of Lft n => "L" ^ Int.toString n | Rgt s => "R" ^ s))) ^ "\n");
