(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_130=" ^ (wrap (fn () => treeShow (((Leaf (List.length ((if true then [3, 9, 9, (~5)] else [9, (~8), 9, (~1)]) @ (List.filter (fn x => x mod 2 = 0) [2, (~4)])))) handle E1 v1 => (if (List.all (fn x => x < 100) (case (v1 :: [7, (~3), 2, 3]) of [] => [] | _ :: t => t)) then (let val v5 = (let val v6 = (Br ((Leaf (~8)), (Leaf 5))) in (let val t = v6 in (treeSum t, treeDepth t) end) end) in (Br ((((Leaf (~4)) handle E1 v7 => raise E2) handle E2 => (Leaf 6) | _ => (Leaf (~2))), ((Leaf (~3)) handle E1 v8 => (Leaf (~1)) | _ => (Leaf (~10))))) end) else ((listToTree (case [(~2)] of [] => [] | _ :: t => t)) handle E1 v9 => (Leaf (v9 mod (~8))) | _ => (Br ((treeMap (fn x => (if false then v1 else (~7))) (Leaf 6)), (let val v10 = [] in (Leaf 0) end))))) | _ => (Br ((((treeMap (fn x => (List.foldl (fn (a,b) => a + b) 0 [(~9)])) (treeMap (fn x => (Int.abs (~5))) (Leaf (~5)))) handle E2 => (Leaf (treeDepth (Leaf 10)))) handle E1 v2 => (listToTree (List.rev [(~10)])) | _ => (Br ((Leaf (~9)), (let val v3 = ((~5), 6) in (Leaf 6) end)))), (listToTree ((3 handle E1 v4 => v4 | _ => 2) :: (List.rev []))))))))) ^ "\n");
