(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_12=" ^ (wrap (fn () => Int.toString (((if (case (treeFind (Leaf (~5))) of Non => false | Som _ => true) then (treeProd (Leaf (~ (~1)))) else (Int.max ((treeProd (Br ((Leaf 6), (Leaf (~8))))), (List.length ([(~7), 3] @ [4]))))) * (~ (treeSum (Leaf (treeDepth (Leaf (~1)))))))))) ^ "\n");
