(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_105=" ^ (wrap (fn () => (case ((let val v1 = ((((Int.abs (String.size "v")), ((0 div 7) * (treeDepth (Leaf (~1))))) handle E2 => (((let val p = ((~8), (~4)) in (#2 p, #1 p) end) handle E2 => (((let val t = (Leaf (~9)) in (treeSum t, treeDepth t) end) handle E2 => (let val t = (Leaf 2) in (treeSum t, treeDepth t) end)) handle E1 v4 => (let val t = (Leaf 3) in (treeSum t, treeDepth t) end) | _ => (let val t = (Leaf 8) in (treeSum t, treeDepth t) end))) handle E1 v3 => (((v3, v3) handle E2 => (((10, (~1)) handle E1 v7 => raise E2) handle E2 => ((~4), (~2)) | _ => (10, (~6)))) handle E1 v6 => (let val p = ((~2), (~4)) in (#2 p, #1 p) end) | _ => (let val p = (1, (~1)) in (#2 p, #1 p) end)) | _ => (let val v5 = (Rgt "8pg") in (let val p = ((~3), (~10)) in (#2 p, #1 p) end) end))) handle E1 v2 => ((case (Som 7) of Non => 0 | Som 0 => 100 | Som n => n), ((v2 div v2) div (case Non of Non => 0 | Som 0 => 100 | Som n => n))) | _ => (if (((case (Som (~1)) of Non => false | Som _ => true) handle E2 => (treeAny (Leaf (~9)))) handle E1 v8 => ("aexne" = "7fq") | _ => (List.exists (fn x => x > 0) [(~2)])) then (let val v9 = (Leaf 3) in (let val t = v9 in (treeSum t, treeDepth t) end) end) else (if (List.exists (fn x => x > 0) [10]) then (let val v10 = "u53x" in ((~1), (~9)) end) else ((~1), (~9))))) in (Rgt (String.concatWith "-" (List.map Int.toString (case (let val v11 = "s0hl" in [10, (~7), (~3), (~3)] end) of [] => [] | _ :: t => t)))) end)) of Lft n => "L" ^ Int.toString n | Rgt s => "R" ^ s))) ^ "\n");
