(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_117=" ^ (wrap (fn () => il2s ((List.map (fn x => ((((case (case (Som 2) of Non => Non | Som n => Som (n + 1)) of Som n => n | Non => raise E1 (~1)) handle E1 k => k) + (#2 (let val v1 = (Leaf 0) in (8, (~1)) end))) - (treeDepth (if (if false then true else false) then (listToTree []) else (let val v2 = (Som 2) in (Leaf (~9)) end))))) ((((((List.map (fn x => if x < 0 then raise E1 x else x + 1) (treeFlat (Leaf 9))) handle E1 _ => []) handle E2 => (List.rev (treeFlat (Leaf (~7))))) handle E1 v3 => (List.filter (fn x => x mod 2 = 0) (List.rev [(~10), 2])) | _ => (((case (Som (~2)) of Som n => n | Non => raise E1 (~1)) handle E1 k => k) :: (if false then [(~3)] else [3, (~10), 7, (~2)]))) handle E2 => (let val v5 = Non in (case ([(~10), 3, (~4)] @ [0, (~8), 4, (~7)]) of [] => [] | _ :: t => t) end)) handle E1 v4 => (if (((case Non of Non => false | Som _ => true) handle E1 v6 => raise E2) handle E2 => (4 < 6) | _ => (true orelse false)) then (List.filter (fn x => x mod 2 = 0) (case [2, (~9), 9, 5] of [] => [] | _ :: t => t)) else (let val v7 = (let val v8 = (Leaf 8) in true end) in (if true then [6, (~10), 2] else [2, (~8), 4]) end)) | _ => (List.filter (fn x => x mod 2 = 0) (List.map (fn x => (Int.abs x)) ((~1) :: [0, 1, 1, 3])))))))) ^ "\n");
