(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_143=" ^ (wrap (fn () => pr2s ((let val v1 = (let val v2 = (let val v3 = (treeFind (treeMap (fn x => (treeSum (Leaf 1))) (Leaf (~4)))) in ((((4, (~6)) handle E1 v4 => (9, 1) | _ => ((~4), (~5))) handle E2 => (let val t = (Leaf 7) in (treeSum t, treeDepth t) end)) handle E1 v5 => (if true then (1, (~10)) else (3, (~7))) | _ => (let val t = (Leaf (~6)) in (treeSum t, treeDepth t) end)) end) in (let val v6 = (listToTree ((List.map (fn x => if x < 0 then raise E1 x else x + 1) [9]) handle E1 _ => [])) in ((Rgt "") handle E1 v7 => (Rgt "jp") | _ => (let val n = 2 in if n mod 2 = 0 then Lft n else Rgt (Int.toString n) end)) end) end) in ((let val v9 = ((let val n = 4 in if n mod 2 = 0 then Lft n else Rgt (Int.toString n) end) handle E1 v10 => (Rgt " ") | _ => (let val v11 = [(~8), (~7), (~1)] in (Lft 5) end)) in (List.foldl (fn (a,b) => a + b) 0 (([] handle E1 v13 => raise E2) handle E2 => [(~9), (~8), 0, 5] | _ => [])) end), (Int.min ((Int.min ((Int.min (0, 1)), (treeProd (Leaf (~7))))), (((List.foldl (fn (a,b) => a + b) 0 [4]) handle E2 => (treeDepth (Leaf (~9)))) handle E1 v14 => (case (Lft (~7)) of Lft n => n | Rgt s => String.size s) | _ => (if false then (~4) else 2))))) end)))) ^ "\n");
