(* generated by tools/diff-corpus-gen/genprog_dre.sml -- DO NOT EDIT *)
datatype itree = Leaf of int | Br of itree * itree;
datatype ibox = Non | Som of int;
datatype ieither = Lft of int | Rgt of string;
exception E1 of int;
exception E2;
fun wrap f = (f ()) handle Overflow => "OVF" | Div => "DIV"
  | Subscript => "SUB" | Size => "SIZE" | Empty => "EMPTY"
  | Match => "MATCH" | Bind => "BIND"
  | E1 _ => "USR1" | E2 => "USR2" | _ => "EXN";
fun il2s xs = "[" ^ String.concatWith "," (List.map Int.toString xs) ^ "]";
fun pr2s (a,b) = "(" ^ Int.toString a ^ "," ^ Int.toString b ^ ")";
fun treeSum (Leaf n) = n
  | treeSum (Br (l, r)) = treeSum l + treeSum r;
fun treeDepth (Leaf _) = 1
  | treeDepth (Br (l, r)) = 1 + Int.max (treeDepth l, treeDepth r);
fun treeProdAux (Leaf 0) = raise E1 0
  | treeProdAux (Leaf n) = n
  | treeProdAux (Br (l, r)) = treeProdAux l * treeProdAux r;
fun treeProd t = (treeProdAux t) handle E1 _ => 0;
fun treeAny (Leaf n) = n > 0
  | treeAny (Br (l, r)) = treeAny l orelse treeAny r;
fun treeFlat (Leaf n) = [n]
  | treeFlat (Br (l, r)) = treeFlat l @ treeFlat r;
fun treeMap f (Leaf n) = Leaf (f n)
  | treeMap f (Br (l, r)) = Br (treeMap f l, treeMap f r);
fun treeShow (Leaf n) = "L" ^ Int.toString n
  | treeShow (Br (l, r)) = "(" ^ treeShow l ^ "+" ^ treeShow r ^ ")";
fun treeFindAux (Leaf n) = if n > 0 then raise E1 n else ()
  | treeFindAux (Br (l, r)) = (treeFindAux l; treeFindAux r);
fun treeFind t = ((treeFindAux t; Non) handle E1 k => Som k);
fun listToTree [] = Leaf 0
  | listToTree [x] = Leaf x
  | listToTree xs =
      let val n = List.length xs
          val h = n div 2
          fun take (0, _) = [] | take (_, []) = [] | take (k, y::ys) = y :: take (k-1, ys)
          fun drop (0, ys) = ys | drop (_, []) = [] | drop (k, _::ys) = drop (k-1, ys)
      in Br (listToTree (take (h, xs)), listToTree (drop (h, xs))) end;
val () = print ("@@genprog_dre_145=" ^ (wrap (fn () => pr2s ((if (List.null (((List.rev (case [(~10), (~8), (~9)] of [] => [] | _ :: t => t)) handle E1 v1 => raise E2) handle E2 => (if (false andalso true) then ((~4) :: [10]) else (if false then [(~6), (~2)] else [(~8)])) | _ => (if ((~5) > 10) then (case [(~6), 6, 8, (~4)] of [] => [] | _ :: t => t) else (case [(~6)] of [] => [] | _ :: t => t)))) then (let val v2 = (if (case Non of Non => false | Som _ => true) then (if ((~9) > (~10)) then (case (Som (~5)) of Non => Non | Som n => Som (n + 1)) else (treeFind (Leaf (~2)))) else Non) in (let val t = (treeMap (fn x => (#1 (2, 1))) (((Leaf 1) handle E2 => (Leaf (~2))) handle E1 v3 => (Leaf 4) | _ => (Leaf (~4)))) in (treeSum t, treeDepth t) end) end) else (let val p = ((let val t = (Br ((Leaf (~8)), (Leaf 3))) in (treeSum t, treeDepth t) end) handle E1 v4 => (if (if true then true else false) then (if false then (7, (~8)) else (0, (~10))) else (if true then (9, 1) else ((~6), (~7)))) | _ => (let val t = (Leaf (~8)) in (treeSum t, treeDepth t) end)) in (#2 p, #1 p) end))))) ^ "\n");
